/* Generated by Nim Compiler v0.17.2 */
/*   (c) 2017 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w  -I/home/vlad/Nim/lib -o /home/vlad/Sandbox/learnopengl/lighting/nimcache/glm_quat.o /home/vlad/Sandbox/learnopengl/lighting/nimcache/glm_quat.c */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#include <math.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef powerpc
#undef unix
typedef struct tyObject_Quat_8OGz1DWD3GbPw26YwmEgFA tyObject_Quat_8OGz1DWD3GbPw26YwmEgFA;
typedef struct tyObject_Mat_rRXFRTYKpgDJ5Kn1m7tKHA tyObject_Mat_rRXFRTYKpgDJ5Kn1m7tKHA;
typedef struct tyObject_Mat_T4xVXfJBjoFESt9b1eXqtYg tyObject_Mat_T4xVXfJBjoFESt9b1eXqtYg;
typedef struct tyObject_Vec_8lp09c9aJ6sSqRDc8uUVfyuA tyObject_Vec_8lp09c9aJ6sSqRDc8uUVfyuA;
typedef struct tyObject_Vec_nc2ATn3mNKEC36f9a1o6BCw tyObject_Vec_nc2ATn3mNKEC36f9a1o6BCw;
typedef struct tyObject_Quat_yJAd1NQB8I67sGeTRIsbNw tyObject_Quat_yJAd1NQB8I67sGeTRIsbNw;
typedef struct tyObject_Mat_heEQpaDfEb6loQ9cBE724ag tyObject_Mat_heEQpaDfEb6loQ9cBE724ag;
typedef struct tyObject_Mat_HtRb1O5aOVprrfb4PBLHfQ tyObject_Mat_HtRb1O5aOVprrfb4PBLHfQ;
typedef struct tyObject_Vec_S5njPDIR1N39afJ9a6EQzdbA tyObject_Vec_S5njPDIR1N39afJ9a6EQzdbA;
typedef struct tyObject_Vec_ajluWiFZ8tTU9b0kwuUOFAQ tyObject_Vec_ajluWiFZ8tTU9b0kwuUOFAQ;
typedef NF32 tyArray_9aTCwbdg1cSQimdVd0OEKVw[4];
struct tyObject_Quat_8OGz1DWD3GbPw26YwmEgFA {
tyArray_9aTCwbdg1cSQimdVd0OEKVw arr;
};
typedef NF32 tyArray_mXNbtvWKAiZn9bWV4uCjiKg[3];
struct tyObject_Vec_8lp09c9aJ6sSqRDc8uUVfyuA {
tyArray_mXNbtvWKAiZn9bWV4uCjiKg arr;
};
typedef tyObject_Vec_8lp09c9aJ6sSqRDc8uUVfyuA tyArray_gMPLzijF49bL6LaDnzjidvg[3];
struct tyObject_Mat_T4xVXfJBjoFESt9b1eXqtYg {
tyArray_gMPLzijF49bL6LaDnzjidvg arr;
};
struct tyObject_Vec_nc2ATn3mNKEC36f9a1o6BCw {
tyArray_9aTCwbdg1cSQimdVd0OEKVw arr;
};
typedef tyObject_Vec_nc2ATn3mNKEC36f9a1o6BCw tyArray_Vwko69bN4O2Unwiy9crf9a1iQ[4];
struct tyObject_Mat_rRXFRTYKpgDJ5Kn1m7tKHA {
tyArray_Vwko69bN4O2Unwiy9crf9a1iQ arr;
};
typedef NF tyArray_jOGfJgrdxgfAJsLC7WNNEw[4];
struct tyObject_Quat_yJAd1NQB8I67sGeTRIsbNw {
tyArray_jOGfJgrdxgfAJsLC7WNNEw arr;
};
typedef NF tyArray_9ce69c9a1NzlPVqY9aKHS79b5IQ[3];
struct tyObject_Vec_S5njPDIR1N39afJ9a6EQzdbA {
tyArray_9ce69c9a1NzlPVqY9aKHS79b5IQ arr;
};
typedef tyObject_Vec_S5njPDIR1N39afJ9a6EQzdbA tyArray_g1Wwy4MqSojCcyAwDZZ0dg[3];
struct tyObject_Mat_HtRb1O5aOVprrfb4PBLHfQ {
tyArray_g1Wwy4MqSojCcyAwDZZ0dg arr;
};
struct tyObject_Vec_ajluWiFZ8tTU9b0kwuUOFAQ {
tyArray_jOGfJgrdxgfAJsLC7WNNEw arr;
};
typedef tyObject_Vec_ajluWiFZ8tTU9b0kwuUOFAQ tyArray_PWeDMgRgWxdaA1WjZ09bmiA[4];
struct tyObject_Mat_heEQpaDfEb6loQ9cBE724ag {
tyArray_PWeDMgRgWxdaA1WjZ09bmiA arr;
};
static N_INLINE(tyObject_Quat_8OGz1DWD3GbPw26YwmEgFA, quatf_B3Tk7ibspUCeUKLupWvG9cQquat)(NF32 x, NF32 y, NF32 z, NF32 w);
static N_INLINE(void, nimFrame)(TFrame* s);
N_NOINLINE(void, stackOverflow_II46IjNZztN9bmbxUD8dt8g)(void);
static N_INLINE(void, popFrame)(void);
N_NIMCALL(tyObject_Quat_8OGz1DWD3GbPw26YwmEgFA, quat_fPOtxpkVq1yw860ZwYu9cdw)(tyObject_Mat_rRXFRTYKpgDJ5Kn1m7tKHA* mat);
N_NIMCALL(tyObject_Quat_8OGz1DWD3GbPw26YwmEgFA, quat_Anu8hOIKhcfXwGCygNeQgg)(tyObject_Mat_T4xVXfJBjoFESt9b1eXqtYg* m);
static N_INLINE(NF32, X5BX5D__1laBXuXKeK8f9aVhwaW9bDCAquat)(tyObject_Vec_8lp09c9aJ6sSqRDc8uUVfyuA v, NI ix);
N_NOINLINE(void, raiseIndexError)(void);
static N_INLINE(tyObject_Vec_8lp09c9aJ6sSqRDc8uUVfyuA, X5BX5D__rEXZMo9bL1J1n1McYQKstrgquat)(tyObject_Mat_T4xVXfJBjoFESt9b1eXqtYg* v, NI ix);
N_NIMCALL(void, weq__GCNEa8PrHZJD7kPbvColTQ)(tyObject_Quat_8OGz1DWD3GbPw26YwmEgFA* q, NF32 v);
N_NIMCALL(void, X5BX5Deq__nlZ7Qp0P2yr0mVKOy1aWjg)(tyObject_Quat_8OGz1DWD3GbPw26YwmEgFA* q, NI i, NF32 val);
N_NIMCALL(void, xeq__GCNEa8PrHZJD7kPbvColTQ_2)(tyObject_Quat_8OGz1DWD3GbPw26YwmEgFA* q, NF32 v);
N_NIMCALL(void, yeq__GCNEa8PrHZJD7kPbvColTQ_3)(tyObject_Quat_8OGz1DWD3GbPw26YwmEgFA* q, NF32 v);
N_NIMCALL(void, zeq__GCNEa8PrHZJD7kPbvColTQ_4)(tyObject_Quat_8OGz1DWD3GbPw26YwmEgFA* q, NF32 v);
N_NIMCALL(tyObject_Mat_T4xVXfJBjoFESt9b1eXqtYg, mat3_a0uQJfXiy9aQlYR4iveqxUw)(tyObject_Vec_8lp09c9aJ6sSqRDc8uUVfyuA a, tyObject_Vec_8lp09c9aJ6sSqRDc8uUVfyuA b, tyObject_Vec_8lp09c9aJ6sSqRDc8uUVfyuA c);
static N_INLINE(tyObject_Vec_8lp09c9aJ6sSqRDc8uUVfyuA, xyz_SaRAHeaZESnlNsRWeM6zKQquat)(tyObject_Vec_nc2ATn3mNKEC36f9a1o6BCw v);
static N_INLINE(tyObject_Vec_nc2ATn3mNKEC36f9a1o6BCw, X5BX5D__eheLjiNw9aBDJp8bmeHHY9awquat)(tyObject_Mat_rRXFRTYKpgDJ5Kn1m7tKHA* v, NI ix);
N_NIMCALL(tyObject_Quat_8OGz1DWD3GbPw26YwmEgFA, quat_e4AGEGAbBg8gnjMDiPwKVQ)(tyObject_Vec_8lp09c9aJ6sSqRDc8uUVfyuA axis, NF32 angle);
static N_INLINE(NF32, x_Xbi8c1XUPkUTWFDNj5l5oQvec)(tyObject_Vec_8lp09c9aJ6sSqRDc8uUVfyuA v);
static N_INLINE(NF32, y_Xbi8c1XUPkUTWFDNj5l5oQ_2vec)(tyObject_Vec_8lp09c9aJ6sSqRDc8uUVfyuA v);
static N_INLINE(NF32, z_Xbi8c1XUPkUTWFDNj5l5oQ_3vec)(tyObject_Vec_8lp09c9aJ6sSqRDc8uUVfyuA v);
static N_INLINE(tyObject_Quat_8OGz1DWD3GbPw26YwmEgFA, quat_B3Tk7ibspUCeUKLupWvG9cQ_2quat)(NF32 x, NF32 y, NF32 z, NF32 w);
N_NIMCALL(tyObject_Quat_8OGz1DWD3GbPw26YwmEgFA, quat_uw0g7WVS8gj0wu9cw8Tz9c9aw)(tyObject_Vec_8lp09c9aJ6sSqRDc8uUVfyuA u, tyObject_Vec_8lp09c9aJ6sSqRDc8uUVfyuA v);
N_NIMCALL(tyObject_Vec_8lp09c9aJ6sSqRDc8uUVfyuA, cross_u30ZqBLCPuracR4Z1FBPOQ)(tyObject_Vec_8lp09c9aJ6sSqRDc8uUVfyuA v1, tyObject_Vec_8lp09c9aJ6sSqRDc8uUVfyuA v2);
static N_INLINE(NF32, dot_fVg9b9b1P9aDx1N4voq9cgRWhQquat)(tyObject_Vec_8lp09c9aJ6sSqRDc8uUVfyuA u, tyObject_Vec_8lp09c9aJ6sSqRDc8uUVfyuA v);
static N_INLINE(void, pluseq__0Q9c9ccOr82GxaUx3qtv9aCoQquat)(NF32* x, NF32 y);
static N_INLINE(NI, addInt)(NI a, NI b);
N_NOINLINE(void, raiseOverflow)(void);
N_NIMCALL(tyObject_Quat_8OGz1DWD3GbPw26YwmEgFA, normalize_9aGq4tI0kJTht8uYKISPt2Q)(tyObject_Quat_8OGz1DWD3GbPw26YwmEgFA q);
N_NIMCALL(tyObject_Quat_8OGz1DWD3GbPw26YwmEgFA, star__ACy88Lzc9cgWeEVEtOIkXEA)(tyObject_Quat_8OGz1DWD3GbPw26YwmEgFA q, NF32 s);
N_NIMCALL(NF32, X5BX5D__O1OvuULnXFY9b2jyEcFfrLA)(tyObject_Quat_8OGz1DWD3GbPw26YwmEgFA q, NI i);
N_NIMCALL(NF32, length_kG7Dk1nvxm5ySomPiPJnFQ)(tyObject_Quat_8OGz1DWD3GbPw26YwmEgFA q);
N_NIMCALL(NF32, length2_kG7Dk1nvxm5ySomPiPJnFQ_2)(tyObject_Quat_8OGz1DWD3GbPw26YwmEgFA q);
static N_INLINE(tyObject_Vec_8lp09c9aJ6sSqRDc8uUVfyuA, yzx_QNKRCIoL02fVO14FHlc10Qvec)(tyObject_Vec_8lp09c9aJ6sSqRDc8uUVfyuA v);
static N_INLINE(tyObject_Vec_8lp09c9aJ6sSqRDc8uUVfyuA, zxy_QNKRCIoL02fVO14FHlc10Q_2vec)(tyObject_Vec_8lp09c9aJ6sSqRDc8uUVfyuA v);
static N_INLINE(tyObject_Vec_8lp09c9aJ6sSqRDc8uUVfyuA, star__J7vWjOv59bjwwYcDHMIUtEg_2vec)(tyObject_Vec_8lp09c9aJ6sSqRDc8uUVfyuA v, tyObject_Vec_8lp09c9aJ6sSqRDc8uUVfyuA u);
static N_INLINE(tyObject_Vec_8lp09c9aJ6sSqRDc8uUVfyuA, minus__J7vWjOv59bjwwYcDHMIUtEgvec)(tyObject_Vec_8lp09c9aJ6sSqRDc8uUVfyuA v, tyObject_Vec_8lp09c9aJ6sSqRDc8uUVfyuA u);
N_NIMCALL(tyObject_Quat_8OGz1DWD3GbPw26YwmEgFA, quatf_e4AGEGAbBg8gnjMDiPwKVQ_2)(tyObject_Vec_8lp09c9aJ6sSqRDc8uUVfyuA axis, NF32 angle);
N_NIMCALL(tyObject_Quat_8OGz1DWD3GbPw26YwmEgFA, quatf_uw0g7WVS8gj0wu9cw8Tz9c9aw_2)(tyObject_Vec_8lp09c9aJ6sSqRDc8uUVfyuA u, tyObject_Vec_8lp09c9aJ6sSqRDc8uUVfyuA v);
N_NIMCALL(tyObject_Quat_8OGz1DWD3GbPw26YwmEgFA, quatf_X0cGfWDayZC5Zp1XKZFtKg)(tyObject_Mat_T4xVXfJBjoFESt9b1eXqtYg* mat);
N_NIMCALL(tyObject_Quat_8OGz1DWD3GbPw26YwmEgFA, quatf_PGZ6hsyjJ6sePt0ul8pKjw)(void);
static N_INLINE(tyObject_Quat_yJAd1NQB8I67sGeTRIsbNw, quatd_0lqGzO7AmX7PhRWVxaVspQquat)(NF x, NF y, NF z, NF w);
N_NIMCALL(tyObject_Quat_yJAd1NQB8I67sGeTRIsbNw, quat_YgjR5GQ2DyEtw5vNWaVUjw)(tyObject_Mat_heEQpaDfEb6loQ9cBE724ag* mat);
N_NIMCALL(tyObject_Quat_yJAd1NQB8I67sGeTRIsbNw, quat_9bg9b9a9bGItEerqpTBegmuR1w)(tyObject_Mat_HtRb1O5aOVprrfb4PBLHfQ* m);
static N_INLINE(NF, X5BX5D__HoOotoUjRplz2l22Kg9bGJQquat)(tyObject_Vec_S5njPDIR1N39afJ9a6EQzdbA* v, NI ix);
static N_INLINE(tyObject_Vec_S5njPDIR1N39afJ9a6EQzdbA, X5BX5D__DFRvm3Wm5fJ7q7ShD5ku3wquat)(tyObject_Mat_HtRb1O5aOVprrfb4PBLHfQ* v, NI ix);
N_NIMCALL(void, weq__hUQCTX9aE3AffSKdLKY7vjw)(tyObject_Quat_yJAd1NQB8I67sGeTRIsbNw* q, NF v);
N_NIMCALL(void, X5BX5Deq__CXmgG9aNgIv0zqBZasUbPGg)(tyObject_Quat_yJAd1NQB8I67sGeTRIsbNw* q, NI i, NF val);
N_NIMCALL(void, xeq__hUQCTX9aE3AffSKdLKY7vjw_2)(tyObject_Quat_yJAd1NQB8I67sGeTRIsbNw* q, NF v);
N_NIMCALL(void, yeq__hUQCTX9aE3AffSKdLKY7vjw_3)(tyObject_Quat_yJAd1NQB8I67sGeTRIsbNw* q, NF v);
N_NIMCALL(void, zeq__hUQCTX9aE3AffSKdLKY7vjw_4)(tyObject_Quat_yJAd1NQB8I67sGeTRIsbNw* q, NF v);
N_NIMCALL(tyObject_Mat_HtRb1O5aOVprrfb4PBLHfQ, mat3_GnV39c9bfQfKHmgIWBodVH8A)(tyObject_Vec_S5njPDIR1N39afJ9a6EQzdbA* a, tyObject_Vec_S5njPDIR1N39afJ9a6EQzdbA* b, tyObject_Vec_S5njPDIR1N39afJ9a6EQzdbA* c);
static N_INLINE(tyObject_Vec_S5njPDIR1N39afJ9a6EQzdbA, xyz_PjuPWi0lAXGKqBB2kytmngquat)(tyObject_Vec_ajluWiFZ8tTU9b0kwuUOFAQ* v);
static N_INLINE(tyObject_Vec_ajluWiFZ8tTU9b0kwuUOFAQ, X5BX5D__bDnwjaYhlA4Lch0wvQp59bAquat)(tyObject_Mat_heEQpaDfEb6loQ9cBE724ag* v, NI ix);
N_NIMCALL(tyObject_Quat_yJAd1NQB8I67sGeTRIsbNw, quat_0gnPEPPD5U13KUM09ao5wFA)(tyObject_Vec_S5njPDIR1N39afJ9a6EQzdbA* axis, NF angle);
static N_INLINE(NF, x_NpfOyWKi6CLtEhMWqkmyuQvec)(tyObject_Vec_S5njPDIR1N39afJ9a6EQzdbA* v);
static N_INLINE(NF, y_NpfOyWKi6CLtEhMWqkmyuQ_2vec)(tyObject_Vec_S5njPDIR1N39afJ9a6EQzdbA* v);
static N_INLINE(NF, z_NpfOyWKi6CLtEhMWqkmyuQ_3vec)(tyObject_Vec_S5njPDIR1N39afJ9a6EQzdbA* v);
static N_INLINE(tyObject_Quat_yJAd1NQB8I67sGeTRIsbNw, quat_0lqGzO7AmX7PhRWVxaVspQ_2quat)(NF x, NF y, NF z, NF w);
N_NIMCALL(tyObject_Quat_yJAd1NQB8I67sGeTRIsbNw, quat_jmZHZx59bLLTLSoCQp31v9bw)(tyObject_Vec_S5njPDIR1N39afJ9a6EQzdbA* u, tyObject_Vec_S5njPDIR1N39afJ9a6EQzdbA* v);
N_NIMCALL(tyObject_Vec_S5njPDIR1N39afJ9a6EQzdbA, cross_xqD7SU75nzFLAQWqOYjycQ)(tyObject_Vec_S5njPDIR1N39afJ9a6EQzdbA* v1, tyObject_Vec_S5njPDIR1N39afJ9a6EQzdbA* v2);
static N_INLINE(NF, dot_IcSwLAapwm3k9a3IG4M9bUSQquat)(tyObject_Vec_S5njPDIR1N39afJ9a6EQzdbA* u, tyObject_Vec_S5njPDIR1N39afJ9a6EQzdbA* v);
static N_INLINE(void, pluseq__7kHiltrvRlcg6wSYR3CxAw_2strutils)(NF* x, NF y);
N_NIMCALL(tyObject_Quat_yJAd1NQB8I67sGeTRIsbNw, normalize_e2ZcyGv6dIwdw8RgF6Ck2g)(tyObject_Quat_yJAd1NQB8I67sGeTRIsbNw* q);
N_NIMCALL(tyObject_Quat_yJAd1NQB8I67sGeTRIsbNw, star__XWgUovB1XZVq9curgVFw4Qg)(tyObject_Quat_yJAd1NQB8I67sGeTRIsbNw* q, NF s);
N_NIMCALL(NF, X5BX5D__W9bJigMDx5Mue3nTmF9bxFPw)(tyObject_Quat_yJAd1NQB8I67sGeTRIsbNw* q, NI i);
N_NIMCALL(NF, length_e0H9aq8ETGjS9by7Evwdd3dA)(tyObject_Quat_yJAd1NQB8I67sGeTRIsbNw* q);
N_NIMCALL(NF, length2_e0H9aq8ETGjS9by7Evwdd3dA_2)(tyObject_Quat_yJAd1NQB8I67sGeTRIsbNw* q);
static N_INLINE(tyObject_Vec_S5njPDIR1N39afJ9a6EQzdbA, yzx_MSvCTTpbc9cWSB9cTnDV2tBAvec)(tyObject_Vec_S5njPDIR1N39afJ9a6EQzdbA* v);
static N_INLINE(tyObject_Vec_S5njPDIR1N39afJ9a6EQzdbA, zxy_MSvCTTpbc9cWSB9cTnDV2tBA_2vec)(tyObject_Vec_S5njPDIR1N39afJ9a6EQzdbA* v);
static N_INLINE(tyObject_Vec_S5njPDIR1N39afJ9a6EQzdbA, star__btEXTJnnMEuPmjWOn1TWIA_2vec)(tyObject_Vec_S5njPDIR1N39afJ9a6EQzdbA* v, tyObject_Vec_S5njPDIR1N39afJ9a6EQzdbA* u);
static N_INLINE(tyObject_Vec_S5njPDIR1N39afJ9a6EQzdbA, minus__btEXTJnnMEuPmjWOn1TWIAvec)(tyObject_Vec_S5njPDIR1N39afJ9a6EQzdbA* v, tyObject_Vec_S5njPDIR1N39afJ9a6EQzdbA* u);
N_NIMCALL(tyObject_Quat_yJAd1NQB8I67sGeTRIsbNw, quatd_0gnPEPPD5U13KUM09ao5wFA_2)(tyObject_Vec_S5njPDIR1N39afJ9a6EQzdbA* axis, NF angle);
N_NIMCALL(tyObject_Quat_yJAd1NQB8I67sGeTRIsbNw, quatd_jmZHZx59bLLTLSoCQp31v9bw_2)(tyObject_Vec_S5njPDIR1N39afJ9a6EQzdbA* u, tyObject_Vec_S5njPDIR1N39afJ9a6EQzdbA* v);
N_NIMCALL(tyObject_Quat_yJAd1NQB8I67sGeTRIsbNw, quatd_sweJ0yMi9azrhhhxjXHoEUw)(tyObject_Mat_HtRb1O5aOVprrfb4PBLHfQ* mat);
N_NIMCALL(tyObject_Quat_yJAd1NQB8I67sGeTRIsbNw, quatd_xt2xY9c8l9akDPgVM2pv5aLw)(void);
extern TFrame* framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
NIM_CONST tyArray_9aTCwbdg1cSQimdVd0OEKVw TM_puszxb5eHZKmsb5EP4KzKQ_7 = {0.0f,
0.0,
0.0,
1.0000000000000000e+00}
;
NIM_CONST tyArray_jOGfJgrdxgfAJsLC7WNNEw TM_puszxb5eHZKmsb5EP4KzKQ_13 = {0.0,
0.0,
0.0,
1.0000000000000000e+00}
;

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI T1_;
	T1_ = (NI)0;
	{
		if (!(framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw == NIM_NIL)) goto LA4_;
		T1_ = ((NI) 0);
	}
	goto LA2_;
	LA4_: ;
	{
		T1_ = ((NI) ((NI16)((*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).calldepth + ((NI16) 1))));
	}
	LA2_: ;
	(*s).calldepth = ((NI16) (T1_));
	(*s).prev = framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9_;
		stackOverflow_II46IjNZztN9bmbxUD8dt8g();
	}
	LA9_: ;
}

static N_INLINE(void, popFrame)(void) {
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = (*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).prev;
}

static N_INLINE(tyObject_Quat_8OGz1DWD3GbPw26YwmEgFA, quatf_B3Tk7ibspUCeUKLupWvG9cQquat)(NF32 x, NF32 y, NF32 z, NF32 w) {
	tyObject_Quat_8OGz1DWD3GbPw26YwmEgFA result;
	tyObject_Quat_8OGz1DWD3GbPw26YwmEgFA T1_;
	nimfr_("quatf", "quat.nim");
	memset((void*)(&result), 0, sizeof(result));
	nimln_(335, "quat.nim");
	memset((void*)(&T1_), 0, sizeof(T1_));
	T1_.arr[0] = x;
	T1_.arr[1] = y;
	T1_.arr[2] = z;
	T1_.arr[3] = w;
	result = T1_;
	popFrame();
	return result;
}

static N_INLINE(NF32, X5BX5D__1laBXuXKeK8f9aVhwaW9bDCAquat)(tyObject_Vec_8lp09c9aJ6sSqRDc8uUVfyuA v, NI ix) {
	NF32 result;
	nimfr_("[]", "vec.nim");
	result = (NF32)0;
	nimln_(149, "vec.nim");
	if ((NU)(ix) > (NU)(2)) raiseIndexError();
	result = v.arr[(ix)- 0];
	popFrame();
	return result;
}

static N_INLINE(tyObject_Vec_8lp09c9aJ6sSqRDc8uUVfyuA, X5BX5D__rEXZMo9bL1J1n1McYQKstrgquat)(tyObject_Mat_T4xVXfJBjoFESt9b1eXqtYg* v, NI ix) {
	tyObject_Vec_8lp09c9aJ6sSqRDc8uUVfyuA result;
	nimfr_("[]", "mat.nim");
	memset((void*)(&result), 0, sizeof(result));
	nimln_(36, "mat.nim");
	if ((NU)(ix) > (NU)(2)) raiseIndexError();
	result = (*v).arr[(ix)- 0];
	popFrame();
	return result;
}

N_NIMCALL(void, X5BX5Deq__nlZ7Qp0P2yr0mVKOy1aWjg)(tyObject_Quat_8OGz1DWD3GbPw26YwmEgFA* q, NI i, NF32 val) {
	nimfr_("[]=", "quat.nim");
	if ((NU)(i) > (NU)(3)) raiseIndexError();
	nimln_(16, "quat.nim");
	(*q).arr[(i)- 0] = val;
	popFrame();
}

N_NIMCALL(void, weq__GCNEa8PrHZJD7kPbvColTQ)(tyObject_Quat_8OGz1DWD3GbPw26YwmEgFA* q, NF32 v) {
	nimfr_("w=", "quat.nim");
	nimln_(61, "quat.nim");
	X5BX5Deq__nlZ7Qp0P2yr0mVKOy1aWjg(q, ((NI) 3), v);
	popFrame();
}

N_NIMCALL(void, xeq__GCNEa8PrHZJD7kPbvColTQ_2)(tyObject_Quat_8OGz1DWD3GbPw26YwmEgFA* q, NF32 v) {
	nimfr_("x=", "quat.nim");
	nimln_(52, "quat.nim");
	X5BX5Deq__nlZ7Qp0P2yr0mVKOy1aWjg(q, ((NI) 0), v);
	popFrame();
}

N_NIMCALL(void, yeq__GCNEa8PrHZJD7kPbvColTQ_3)(tyObject_Quat_8OGz1DWD3GbPw26YwmEgFA* q, NF32 v) {
	nimfr_("y=", "quat.nim");
	nimln_(55, "quat.nim");
	X5BX5Deq__nlZ7Qp0P2yr0mVKOy1aWjg(q, ((NI) 1), v);
	popFrame();
}

N_NIMCALL(void, zeq__GCNEa8PrHZJD7kPbvColTQ_4)(tyObject_Quat_8OGz1DWD3GbPw26YwmEgFA* q, NF32 v) {
	nimfr_("z=", "quat.nim");
	nimln_(58, "quat.nim");
	X5BX5Deq__nlZ7Qp0P2yr0mVKOy1aWjg(q, ((NI) 2), v);
	popFrame();
}

N_NIMCALL(tyObject_Quat_8OGz1DWD3GbPw26YwmEgFA, quat_Anu8hOIKhcfXwGCygNeQgg)(tyObject_Mat_T4xVXfJBjoFESt9b1eXqtYg* m) {
	tyObject_Quat_8OGz1DWD3GbPw26YwmEgFA result;
	NF32 fourXSquaredMinus1;
	tyObject_Vec_8lp09c9aJ6sSqRDc8uUVfyuA T1_;
	NF32 T2_;
	tyObject_Vec_8lp09c9aJ6sSqRDc8uUVfyuA T3_;
	NF32 T4_;
	tyObject_Vec_8lp09c9aJ6sSqRDc8uUVfyuA T5_;
	NF32 T6_;
	NF32 fourYSquaredMinus1;
	tyObject_Vec_8lp09c9aJ6sSqRDc8uUVfyuA T7_;
	NF32 T8_;
	tyObject_Vec_8lp09c9aJ6sSqRDc8uUVfyuA T9_;
	NF32 T10_;
	tyObject_Vec_8lp09c9aJ6sSqRDc8uUVfyuA T11_;
	NF32 T12_;
	NF32 fourZSquaredMinus1;
	tyObject_Vec_8lp09c9aJ6sSqRDc8uUVfyuA T13_;
	NF32 T14_;
	tyObject_Vec_8lp09c9aJ6sSqRDc8uUVfyuA T15_;
	NF32 T16_;
	tyObject_Vec_8lp09c9aJ6sSqRDc8uUVfyuA T17_;
	NF32 T18_;
	NF32 fourWSquaredMinus1;
	tyObject_Vec_8lp09c9aJ6sSqRDc8uUVfyuA T19_;
	NF32 T20_;
	tyObject_Vec_8lp09c9aJ6sSqRDc8uUVfyuA T21_;
	NF32 T22_;
	tyObject_Vec_8lp09c9aJ6sSqRDc8uUVfyuA T23_;
	NF32 T24_;
	NI biggestIndex;
	NF32 fourBiggestSquaredMinus1;
	NF32 biggestVal;
	NF32 T37_;
	NF32 mult;
	nimfr_("quat", "quat.nim");
	memset((void*)(&result), 0, sizeof(result));
	nimln_(80, "quat.nim");
	T1_ = X5BX5D__rEXZMo9bL1J1n1McYQKstrgquat(m, ((NI) 0));
	T2_ = (NF32)0;
	T2_ = X5BX5D__1laBXuXKeK8f9aVhwaW9bDCAquat(T1_, ((NI) 0));
	T3_ = X5BX5D__rEXZMo9bL1J1n1McYQKstrgquat(m, ((NI) 1));
	T4_ = (NF32)0;
	T4_ = X5BX5D__1laBXuXKeK8f9aVhwaW9bDCAquat(T3_, ((NI) 1));
	T5_ = X5BX5D__rEXZMo9bL1J1n1McYQKstrgquat(m, ((NI) 2));
	T6_ = (NF32)0;
	T6_ = X5BX5D__1laBXuXKeK8f9aVhwaW9bDCAquat(T5_, ((NI) 2));
	fourXSquaredMinus1 = ((NF32)(((NF32)(T2_) - (NF32)(T4_))) - (NF32)(T6_));
	nimln_(81, "quat.nim");
	T7_ = X5BX5D__rEXZMo9bL1J1n1McYQKstrgquat(m, ((NI) 1));
	T8_ = (NF32)0;
	T8_ = X5BX5D__1laBXuXKeK8f9aVhwaW9bDCAquat(T7_, ((NI) 1));
	T9_ = X5BX5D__rEXZMo9bL1J1n1McYQKstrgquat(m, ((NI) 0));
	T10_ = (NF32)0;
	T10_ = X5BX5D__1laBXuXKeK8f9aVhwaW9bDCAquat(T9_, ((NI) 0));
	T11_ = X5BX5D__rEXZMo9bL1J1n1McYQKstrgquat(m, ((NI) 2));
	T12_ = (NF32)0;
	T12_ = X5BX5D__1laBXuXKeK8f9aVhwaW9bDCAquat(T11_, ((NI) 2));
	fourYSquaredMinus1 = ((NF32)(((NF32)(T8_) - (NF32)(T10_))) - (NF32)(T12_));
	nimln_(82, "quat.nim");
	T13_ = X5BX5D__rEXZMo9bL1J1n1McYQKstrgquat(m, ((NI) 2));
	T14_ = (NF32)0;
	T14_ = X5BX5D__1laBXuXKeK8f9aVhwaW9bDCAquat(T13_, ((NI) 2));
	T15_ = X5BX5D__rEXZMo9bL1J1n1McYQKstrgquat(m, ((NI) 0));
	T16_ = (NF32)0;
	T16_ = X5BX5D__1laBXuXKeK8f9aVhwaW9bDCAquat(T15_, ((NI) 0));
	T17_ = X5BX5D__rEXZMo9bL1J1n1McYQKstrgquat(m, ((NI) 1));
	T18_ = (NF32)0;
	T18_ = X5BX5D__1laBXuXKeK8f9aVhwaW9bDCAquat(T17_, ((NI) 1));
	fourZSquaredMinus1 = ((NF32)(((NF32)(T14_) - (NF32)(T16_))) - (NF32)(T18_));
	nimln_(83, "quat.nim");
	T19_ = X5BX5D__rEXZMo9bL1J1n1McYQKstrgquat(m, ((NI) 0));
	T20_ = (NF32)0;
	T20_ = X5BX5D__1laBXuXKeK8f9aVhwaW9bDCAquat(T19_, ((NI) 0));
	T21_ = X5BX5D__rEXZMo9bL1J1n1McYQKstrgquat(m, ((NI) 1));
	T22_ = (NF32)0;
	T22_ = X5BX5D__1laBXuXKeK8f9aVhwaW9bDCAquat(T21_, ((NI) 1));
	T23_ = X5BX5D__rEXZMo9bL1J1n1McYQKstrgquat(m, ((NI) 2));
	T24_ = (NF32)0;
	T24_ = X5BX5D__1laBXuXKeK8f9aVhwaW9bDCAquat(T23_, ((NI) 2));
	fourWSquaredMinus1 = ((NF32)(((NF32)(T20_) + (NF32)(T22_))) + (NF32)(T24_));
	nimln_(85, "quat.nim");
	biggestIndex = ((NI) 0);
	nimln_(86, "quat.nim");
	fourBiggestSquaredMinus1 = fourWSquaredMinus1;
	nimln_(87, "quat.nim");
	{
		if (!(fourBiggestSquaredMinus1 < fourXSquaredMinus1)) goto LA27_;
		nimln_(88, "quat.nim");
		fourBiggestSquaredMinus1 = fourXSquaredMinus1;
		nimln_(89, "quat.nim");
		biggestIndex = ((NI) 1);
	}
	LA27_: ;
	nimln_(90, "quat.nim");
	{
		if (!(fourBiggestSquaredMinus1 < fourYSquaredMinus1)) goto LA31_;
		nimln_(91, "quat.nim");
		fourBiggestSquaredMinus1 = fourYSquaredMinus1;
		nimln_(92, "quat.nim");
		biggestIndex = ((NI) 2);
	}
	LA31_: ;
	nimln_(93, "quat.nim");
	{
		if (!(fourBiggestSquaredMinus1 < fourZSquaredMinus1)) goto LA35_;
		nimln_(94, "quat.nim");
		fourBiggestSquaredMinus1 = fourZSquaredMinus1;
		nimln_(95, "quat.nim");
		biggestIndex = ((NI) 3);
	}
	LA35_: ;
	nimln_(97, "quat.nim");
	T37_ = (NF32)0;
	T37_ = sqrtf(((NF32)(fourBiggestSquaredMinus1) + (NF32)(1.0000000000000000e+00)));
	biggestVal = ((NF32)(T37_) * (NF32)(5.0000000000000000e-01));
	nimln_(98, "quat.nim");
	mult = ((NF32)(2.5000000000000000e-01) / (NF32)(biggestVal));
	nimln_(100, "quat.nim");
	switch (biggestIndex) {
	case ((NI) 0):
	{
		tyObject_Vec_8lp09c9aJ6sSqRDc8uUVfyuA T39_;
		NF32 T40_;
		tyObject_Vec_8lp09c9aJ6sSqRDc8uUVfyuA T41_;
		NF32 T42_;
		tyObject_Vec_8lp09c9aJ6sSqRDc8uUVfyuA T43_;
		NF32 T44_;
		tyObject_Vec_8lp09c9aJ6sSqRDc8uUVfyuA T45_;
		NF32 T46_;
		tyObject_Vec_8lp09c9aJ6sSqRDc8uUVfyuA T47_;
		NF32 T48_;
		tyObject_Vec_8lp09c9aJ6sSqRDc8uUVfyuA T49_;
		NF32 T50_;
		nimln_(102, "quat.nim");
		weq__GCNEa8PrHZJD7kPbvColTQ((&result), biggestVal);
		nimln_(103, "quat.nim");
		T39_ = X5BX5D__rEXZMo9bL1J1n1McYQKstrgquat(m, ((NI) 1));
		T40_ = (NF32)0;
		T40_ = X5BX5D__1laBXuXKeK8f9aVhwaW9bDCAquat(T39_, ((NI) 2));
		T41_ = X5BX5D__rEXZMo9bL1J1n1McYQKstrgquat(m, ((NI) 2));
		T42_ = (NF32)0;
		T42_ = X5BX5D__1laBXuXKeK8f9aVhwaW9bDCAquat(T41_, ((NI) 1));
		xeq__GCNEa8PrHZJD7kPbvColTQ_2((&result), ((NF32)(((NF32)(T40_) - (NF32)(T42_))) * (NF32)(mult)));
		nimln_(104, "quat.nim");
		T43_ = X5BX5D__rEXZMo9bL1J1n1McYQKstrgquat(m, ((NI) 2));
		T44_ = (NF32)0;
		T44_ = X5BX5D__1laBXuXKeK8f9aVhwaW9bDCAquat(T43_, ((NI) 0));
		T45_ = X5BX5D__rEXZMo9bL1J1n1McYQKstrgquat(m, ((NI) 0));
		T46_ = (NF32)0;
		T46_ = X5BX5D__1laBXuXKeK8f9aVhwaW9bDCAquat(T45_, ((NI) 2));
		yeq__GCNEa8PrHZJD7kPbvColTQ_3((&result), ((NF32)(((NF32)(T44_) - (NF32)(T46_))) * (NF32)(mult)));
		nimln_(105, "quat.nim");
		T47_ = X5BX5D__rEXZMo9bL1J1n1McYQKstrgquat(m, ((NI) 0));
		T48_ = (NF32)0;
		T48_ = X5BX5D__1laBXuXKeK8f9aVhwaW9bDCAquat(T47_, ((NI) 1));
		T49_ = X5BX5D__rEXZMo9bL1J1n1McYQKstrgquat(m, ((NI) 1));
		T50_ = (NF32)0;
		T50_ = X5BX5D__1laBXuXKeK8f9aVhwaW9bDCAquat(T49_, ((NI) 0));
		zeq__GCNEa8PrHZJD7kPbvColTQ_4((&result), ((NF32)(((NF32)(T48_) - (NF32)(T50_))) * (NF32)(mult)));
	}
	break;
	case ((NI) 1):
	{
		tyObject_Vec_8lp09c9aJ6sSqRDc8uUVfyuA T52_;
		NF32 T53_;
		tyObject_Vec_8lp09c9aJ6sSqRDc8uUVfyuA T54_;
		NF32 T55_;
		tyObject_Vec_8lp09c9aJ6sSqRDc8uUVfyuA T56_;
		NF32 T57_;
		tyObject_Vec_8lp09c9aJ6sSqRDc8uUVfyuA T58_;
		NF32 T59_;
		tyObject_Vec_8lp09c9aJ6sSqRDc8uUVfyuA T60_;
		NF32 T61_;
		tyObject_Vec_8lp09c9aJ6sSqRDc8uUVfyuA T62_;
		NF32 T63_;
		nimln_(107, "quat.nim");
		T52_ = X5BX5D__rEXZMo9bL1J1n1McYQKstrgquat(m, ((NI) 1));
		T53_ = (NF32)0;
		T53_ = X5BX5D__1laBXuXKeK8f9aVhwaW9bDCAquat(T52_, ((NI) 2));
		T54_ = X5BX5D__rEXZMo9bL1J1n1McYQKstrgquat(m, ((NI) 2));
		T55_ = (NF32)0;
		T55_ = X5BX5D__1laBXuXKeK8f9aVhwaW9bDCAquat(T54_, ((NI) 1));
		weq__GCNEa8PrHZJD7kPbvColTQ((&result), ((NF32)(((NF32)(T53_) - (NF32)(T55_))) * (NF32)(mult)));
		nimln_(108, "quat.nim");
		xeq__GCNEa8PrHZJD7kPbvColTQ_2((&result), biggestVal);
		nimln_(109, "quat.nim");
		T56_ = X5BX5D__rEXZMo9bL1J1n1McYQKstrgquat(m, ((NI) 0));
		T57_ = (NF32)0;
		T57_ = X5BX5D__1laBXuXKeK8f9aVhwaW9bDCAquat(T56_, ((NI) 1));
		T58_ = X5BX5D__rEXZMo9bL1J1n1McYQKstrgquat(m, ((NI) 1));
		T59_ = (NF32)0;
		T59_ = X5BX5D__1laBXuXKeK8f9aVhwaW9bDCAquat(T58_, ((NI) 0));
		yeq__GCNEa8PrHZJD7kPbvColTQ_3((&result), ((NF32)(((NF32)(T57_) + (NF32)(T59_))) * (NF32)(mult)));
		nimln_(110, "quat.nim");
		T60_ = X5BX5D__rEXZMo9bL1J1n1McYQKstrgquat(m, ((NI) 2));
		T61_ = (NF32)0;
		T61_ = X5BX5D__1laBXuXKeK8f9aVhwaW9bDCAquat(T60_, ((NI) 0));
		T62_ = X5BX5D__rEXZMo9bL1J1n1McYQKstrgquat(m, ((NI) 0));
		T63_ = (NF32)0;
		T63_ = X5BX5D__1laBXuXKeK8f9aVhwaW9bDCAquat(T62_, ((NI) 2));
		zeq__GCNEa8PrHZJD7kPbvColTQ_4((&result), ((NF32)(((NF32)(T61_) + (NF32)(T63_))) * (NF32)(mult)));
	}
	break;
	case ((NI) 2):
	{
		tyObject_Vec_8lp09c9aJ6sSqRDc8uUVfyuA T65_;
		NF32 T66_;
		tyObject_Vec_8lp09c9aJ6sSqRDc8uUVfyuA T67_;
		NF32 T68_;
		tyObject_Vec_8lp09c9aJ6sSqRDc8uUVfyuA T69_;
		NF32 T70_;
		tyObject_Vec_8lp09c9aJ6sSqRDc8uUVfyuA T71_;
		NF32 T72_;
		tyObject_Vec_8lp09c9aJ6sSqRDc8uUVfyuA T73_;
		NF32 T74_;
		tyObject_Vec_8lp09c9aJ6sSqRDc8uUVfyuA T75_;
		NF32 T76_;
		nimln_(112, "quat.nim");
		T65_ = X5BX5D__rEXZMo9bL1J1n1McYQKstrgquat(m, ((NI) 2));
		T66_ = (NF32)0;
		T66_ = X5BX5D__1laBXuXKeK8f9aVhwaW9bDCAquat(T65_, ((NI) 0));
		T67_ = X5BX5D__rEXZMo9bL1J1n1McYQKstrgquat(m, ((NI) 0));
		T68_ = (NF32)0;
		T68_ = X5BX5D__1laBXuXKeK8f9aVhwaW9bDCAquat(T67_, ((NI) 2));
		weq__GCNEa8PrHZJD7kPbvColTQ((&result), ((NF32)(((NF32)(T66_) - (NF32)(T68_))) * (NF32)(mult)));
		nimln_(113, "quat.nim");
		T69_ = X5BX5D__rEXZMo9bL1J1n1McYQKstrgquat(m, ((NI) 0));
		T70_ = (NF32)0;
		T70_ = X5BX5D__1laBXuXKeK8f9aVhwaW9bDCAquat(T69_, ((NI) 1));
		T71_ = X5BX5D__rEXZMo9bL1J1n1McYQKstrgquat(m, ((NI) 1));
		T72_ = (NF32)0;
		T72_ = X5BX5D__1laBXuXKeK8f9aVhwaW9bDCAquat(T71_, ((NI) 0));
		xeq__GCNEa8PrHZJD7kPbvColTQ_2((&result), ((NF32)(((NF32)(T70_) + (NF32)(T72_))) * (NF32)(mult)));
		nimln_(114, "quat.nim");
		yeq__GCNEa8PrHZJD7kPbvColTQ_3((&result), biggestVal);
		nimln_(115, "quat.nim");
		T73_ = X5BX5D__rEXZMo9bL1J1n1McYQKstrgquat(m, ((NI) 1));
		T74_ = (NF32)0;
		T74_ = X5BX5D__1laBXuXKeK8f9aVhwaW9bDCAquat(T73_, ((NI) 2));
		T75_ = X5BX5D__rEXZMo9bL1J1n1McYQKstrgquat(m, ((NI) 2));
		T76_ = (NF32)0;
		T76_ = X5BX5D__1laBXuXKeK8f9aVhwaW9bDCAquat(T75_, ((NI) 1));
		zeq__GCNEa8PrHZJD7kPbvColTQ_4((&result), ((NF32)(((NF32)(T74_) + (NF32)(T76_))) * (NF32)(mult)));
	}
	break;
	case ((NI) 3):
	{
		tyObject_Vec_8lp09c9aJ6sSqRDc8uUVfyuA T78_;
		NF32 T79_;
		tyObject_Vec_8lp09c9aJ6sSqRDc8uUVfyuA T80_;
		NF32 T81_;
		tyObject_Vec_8lp09c9aJ6sSqRDc8uUVfyuA T82_;
		NF32 T83_;
		tyObject_Vec_8lp09c9aJ6sSqRDc8uUVfyuA T84_;
		NF32 T85_;
		tyObject_Vec_8lp09c9aJ6sSqRDc8uUVfyuA T86_;
		NF32 T87_;
		tyObject_Vec_8lp09c9aJ6sSqRDc8uUVfyuA T88_;
		NF32 T89_;
		nimln_(117, "quat.nim");
		T78_ = X5BX5D__rEXZMo9bL1J1n1McYQKstrgquat(m, ((NI) 0));
		T79_ = (NF32)0;
		T79_ = X5BX5D__1laBXuXKeK8f9aVhwaW9bDCAquat(T78_, ((NI) 1));
		T80_ = X5BX5D__rEXZMo9bL1J1n1McYQKstrgquat(m, ((NI) 1));
		T81_ = (NF32)0;
		T81_ = X5BX5D__1laBXuXKeK8f9aVhwaW9bDCAquat(T80_, ((NI) 0));
		weq__GCNEa8PrHZJD7kPbvColTQ((&result), ((NF32)(((NF32)(T79_) - (NF32)(T81_))) * (NF32)(mult)));
		nimln_(118, "quat.nim");
		T82_ = X5BX5D__rEXZMo9bL1J1n1McYQKstrgquat(m, ((NI) 2));
		T83_ = (NF32)0;
		T83_ = X5BX5D__1laBXuXKeK8f9aVhwaW9bDCAquat(T82_, ((NI) 0));
		T84_ = X5BX5D__rEXZMo9bL1J1n1McYQKstrgquat(m, ((NI) 0));
		T85_ = (NF32)0;
		T85_ = X5BX5D__1laBXuXKeK8f9aVhwaW9bDCAquat(T84_, ((NI) 2));
		xeq__GCNEa8PrHZJD7kPbvColTQ_2((&result), ((NF32)(((NF32)(T83_) + (NF32)(T85_))) * (NF32)(mult)));
		nimln_(119, "quat.nim");
		T86_ = X5BX5D__rEXZMo9bL1J1n1McYQKstrgquat(m, ((NI) 1));
		T87_ = (NF32)0;
		T87_ = X5BX5D__1laBXuXKeK8f9aVhwaW9bDCAquat(T86_, ((NI) 2));
		T88_ = X5BX5D__rEXZMo9bL1J1n1McYQKstrgquat(m, ((NI) 2));
		T89_ = (NF32)0;
		T89_ = X5BX5D__1laBXuXKeK8f9aVhwaW9bDCAquat(T88_, ((NI) 1));
		yeq__GCNEa8PrHZJD7kPbvColTQ_3((&result), ((NF32)(((NF32)(T87_) + (NF32)(T89_))) * (NF32)(mult)));
		nimln_(120, "quat.nim");
		zeq__GCNEa8PrHZJD7kPbvColTQ_4((&result), biggestVal);
	}
	break;
	}
	popFrame();
	return result;
}

static N_INLINE(tyObject_Vec_8lp09c9aJ6sSqRDc8uUVfyuA, xyz_SaRAHeaZESnlNsRWeM6zKQquat)(tyObject_Vec_nc2ATn3mNKEC36f9a1o6BCw v) {
	tyObject_Vec_8lp09c9aJ6sSqRDc8uUVfyuA result;
	tyObject_Vec_8lp09c9aJ6sSqRDc8uUVfyuA T1_;
	nimfr_("xyz", "vec.nim");
	memset((void*)(&result), 0, sizeof(result));
	nimln_(216, "vec.nim");
	memset((void*)(&T1_), 0, sizeof(T1_));
	T1_.arr[0] = v.arr[(((NI) 0))- 0];
	T1_.arr[1] = v.arr[(((NI) 1))- 0];
	T1_.arr[2] = v.arr[(((NI) 2))- 0];
	result = T1_;
	popFrame();
	return result;
}

static N_INLINE(tyObject_Vec_nc2ATn3mNKEC36f9a1o6BCw, X5BX5D__eheLjiNw9aBDJp8bmeHHY9awquat)(tyObject_Mat_rRXFRTYKpgDJ5Kn1m7tKHA* v, NI ix) {
	tyObject_Vec_nc2ATn3mNKEC36f9a1o6BCw result;
	nimfr_("[]", "mat.nim");
	memset((void*)(&result), 0, sizeof(result));
	nimln_(36, "mat.nim");
	if ((NU)(ix) > (NU)(3)) raiseIndexError();
	result = (*v).arr[(ix)- 0];
	popFrame();
	return result;
}

N_NIMCALL(tyObject_Quat_8OGz1DWD3GbPw26YwmEgFA, quat_fPOtxpkVq1yw860ZwYu9cdw)(tyObject_Mat_rRXFRTYKpgDJ5Kn1m7tKHA* mat) {
	tyObject_Quat_8OGz1DWD3GbPw26YwmEgFA result;
	tyObject_Vec_nc2ATn3mNKEC36f9a1o6BCw T1_;
	tyObject_Vec_8lp09c9aJ6sSqRDc8uUVfyuA T2_;
	tyObject_Vec_nc2ATn3mNKEC36f9a1o6BCw T3_;
	tyObject_Vec_8lp09c9aJ6sSqRDc8uUVfyuA T4_;
	tyObject_Vec_nc2ATn3mNKEC36f9a1o6BCw T5_;
	tyObject_Vec_8lp09c9aJ6sSqRDc8uUVfyuA T6_;
	tyObject_Mat_T4xVXfJBjoFESt9b1eXqtYg T7_;
	nimfr_("quat", "quat.nim");
	memset((void*)(&result), 0, sizeof(result));
	nimln_(123, "quat.nim");
	nimln_(124, "quat.nim");
	T1_ = X5BX5D__eheLjiNw9aBDJp8bmeHHY9awquat(mat, ((NI) 0));
	T2_ = xyz_SaRAHeaZESnlNsRWeM6zKQquat(T1_);
	T3_ = X5BX5D__eheLjiNw9aBDJp8bmeHHY9awquat(mat, ((NI) 1));
	T4_ = xyz_SaRAHeaZESnlNsRWeM6zKQquat(T3_);
	T5_ = X5BX5D__eheLjiNw9aBDJp8bmeHHY9awquat(mat, ((NI) 2));
	T6_ = xyz_SaRAHeaZESnlNsRWeM6zKQquat(T5_);
	T7_ = mat3_a0uQJfXiy9aQlYR4iveqxUw(T2_, T4_, T6_);
	result = quat_Anu8hOIKhcfXwGCygNeQgg((&T7_));
	popFrame();
	return result;
}

static N_INLINE(NF32, x_Xbi8c1XUPkUTWFDNj5l5oQvec)(tyObject_Vec_8lp09c9aJ6sSqRDc8uUVfyuA v) {
	NF32 result;
	nimfr_("x", "vec.nim");
	result = (NF32)0;
	nimln_(255, "vec.nim");
	result = v.arr[(((NI) 0))- 0];
	popFrame();
	return result;
}

static N_INLINE(NF32, y_Xbi8c1XUPkUTWFDNj5l5oQ_2vec)(tyObject_Vec_8lp09c9aJ6sSqRDc8uUVfyuA v) {
	NF32 result;
	nimfr_("y", "vec.nim");
	result = (NF32)0;
	nimln_(255, "vec.nim");
	result = v.arr[(((NI) 1))- 0];
	popFrame();
	return result;
}

static N_INLINE(NF32, z_Xbi8c1XUPkUTWFDNj5l5oQ_3vec)(tyObject_Vec_8lp09c9aJ6sSqRDc8uUVfyuA v) {
	NF32 result;
	nimfr_("z", "vec.nim");
	result = (NF32)0;
	nimln_(255, "vec.nim");
	result = v.arr[(((NI) 2))- 0];
	popFrame();
	return result;
}

N_NIMCALL(tyObject_Quat_8OGz1DWD3GbPw26YwmEgFA, quat_e4AGEGAbBg8gnjMDiPwKVQ)(tyObject_Vec_8lp09c9aJ6sSqRDc8uUVfyuA axis, NF32 angle) {
	tyObject_Quat_8OGz1DWD3GbPw26YwmEgFA result;
	NF32 s;
	NF32 T1_;
	NF32 T2_;
	NF32 T3_;
	NF32 T4_;
	nimfr_("quat", "quat.nim");
	memset((void*)(&result), 0, sizeof(result));
	nimln_(71, "quat.nim");
	s = sinf(((NF32)(angle) / (NF32)(2.0000000000000000e+00)));
	nimln_(72, "quat.nim");
	T1_ = (NF32)0;
	T1_ = x_Xbi8c1XUPkUTWFDNj5l5oQvec(axis);
	xeq__GCNEa8PrHZJD7kPbvColTQ_2((&result), ((NF32)(T1_) * (NF32)(s)));
	nimln_(73, "quat.nim");
	T2_ = (NF32)0;
	T2_ = y_Xbi8c1XUPkUTWFDNj5l5oQ_2vec(axis);
	yeq__GCNEa8PrHZJD7kPbvColTQ_3((&result), ((NF32)(T2_) * (NF32)(s)));
	nimln_(74, "quat.nim");
	T3_ = (NF32)0;
	T3_ = z_Xbi8c1XUPkUTWFDNj5l5oQ_3vec(axis);
	zeq__GCNEa8PrHZJD7kPbvColTQ_4((&result), ((NF32)(T3_) * (NF32)(s)));
	nimln_(75, "quat.nim");
	T4_ = (NF32)0;
	T4_ = cosf(((NF32)(angle) / (NF32)(2.0000000000000000e+00)));
	weq__GCNEa8PrHZJD7kPbvColTQ((&result), T4_);
	popFrame();
	return result;
}

static N_INLINE(tyObject_Quat_8OGz1DWD3GbPw26YwmEgFA, quat_B3Tk7ibspUCeUKLupWvG9cQ_2quat)(NF32 x, NF32 y, NF32 z, NF32 w) {
	tyObject_Quat_8OGz1DWD3GbPw26YwmEgFA result;
	nimfr_("quat", "quat.nim");
	memset((void*)(&result), 0, sizeof(result));
	nimln_(68, "quat.nim");
	result.arr[0] = x;
	result.arr[1] = y;
	result.arr[2] = z;
	result.arr[3] = w;
	popFrame();
	return result;
}

static N_INLINE(void, pluseq__0Q9c9ccOr82GxaUx3qtv9aCoQquat)(NF32* x, NF32 y) {
	nimfr_("+=", "system.nim");
	nimln_(3549, "system.nim");
	(*x) = ((NF32)((*x)) + (NF32)(y));
	popFrame();
}

static N_INLINE(NI, addInt)(NI a, NI b) {
	NI result;
{	result = (NI)0;
	result = (NI)((NU64)(a) + (NU64)(b));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI) 0) <= (NI)(result ^ a));
		if (T3_) goto LA4_;
		T3_ = (((NI) 0) <= (NI)(result ^ b));
		LA4_: ;
		if (!T3_) goto LA5_;
		goto BeforeRet_;
	}
	LA5_: ;
	raiseOverflow();
	}BeforeRet_: ;
	return result;
}

static N_INLINE(NF32, dot_fVg9b9b1P9aDx1N4voq9cgRWhQquat)(tyObject_Vec_8lp09c9aJ6sSqRDc8uUVfyuA u, tyObject_Vec_8lp09c9aJ6sSqRDc8uUVfyuA v) {
	NF32 result;
	nimfr_("dot", "vec.nim");
	result = (NF32)0;
	{
		NI i;
		NI i_2;
		i = (NI)0;
		nimln_(3847, "system.nim");
		i_2 = ((NI) 0);
		{
			nimln_(3848, "system.nim");
			while (1) {
				NF32 T4_;
				NF32 T5_;
				NI TM_puszxb5eHZKmsb5EP4KzKQ_2;
				if (!(i_2 < ((NI) 3))) goto LA3;
				nimln_(3849, "system.nim");
				i = i_2;
				nimln_(478, "vec.nim");
				T4_ = (NF32)0;
				T4_ = X5BX5D__1laBXuXKeK8f9aVhwaW9bDCAquat(u, i);
				T5_ = (NF32)0;
				T5_ = X5BX5D__1laBXuXKeK8f9aVhwaW9bDCAquat(v, i);
				pluseq__0Q9c9ccOr82GxaUx3qtv9aCoQquat((&result), ((NF32)(T4_) * (NF32)(T5_)));
				nimln_(3850, "system.nim");
				TM_puszxb5eHZKmsb5EP4KzKQ_2 = addInt(i_2, ((NI) 1));
				i_2 = (NI)(TM_puszxb5eHZKmsb5EP4KzKQ_2);
			} LA3: ;
		}
	}
	popFrame();
	return result;
}

N_NIMCALL(NF32, X5BX5D__O1OvuULnXFY9b2jyEcFfrLA)(tyObject_Quat_8OGz1DWD3GbPw26YwmEgFA q, NI i) {
	NF32 result;
	nimfr_("[]", "quat.nim");
	result = (NF32)0;
	nimln_(10, "quat.nim");
	if ((NU)(i) > (NU)(3)) raiseIndexError();
	result = q.arr[(i)- 0];
	popFrame();
	return result;
}

N_NIMCALL(tyObject_Quat_8OGz1DWD3GbPw26YwmEgFA, star__ACy88Lzc9cgWeEVEtOIkXEA)(tyObject_Quat_8OGz1DWD3GbPw26YwmEgFA q, NF32 s) {
	tyObject_Quat_8OGz1DWD3GbPw26YwmEgFA result;
	nimfr_("*", "quat.nim");
	memset((void*)(&result), 0, sizeof(result));
	{
		NI i;
		NI res;
		i = (NI)0;
		nimln_(1986, "system.nim");
		res = ((NI) 0);
		{
			nimln_(1987, "system.nim");
			while (1) {
				NF32 T4_;
				NI TM_puszxb5eHZKmsb5EP4KzKQ_3;
				if (!(res <= ((NI) 3))) goto LA3;
				nimln_(1988, "system.nim");
				i = res;
				nimln_(135, "quat.nim");
				T4_ = (NF32)0;
				T4_ = X5BX5D__O1OvuULnXFY9b2jyEcFfrLA(q, i);
				X5BX5Deq__nlZ7Qp0P2yr0mVKOy1aWjg((&result), i, ((NF32)(T4_) * (NF32)(s)));
				nimln_(1989, "system.nim");
				TM_puszxb5eHZKmsb5EP4KzKQ_3 = addInt(res, ((NI) 1));
				res = (NI)(TM_puszxb5eHZKmsb5EP4KzKQ_3);
			} LA3: ;
		}
	}
	popFrame();
	return result;
}

N_NIMCALL(NF32, length2_kG7Dk1nvxm5ySomPiPJnFQ_2)(tyObject_Quat_8OGz1DWD3GbPw26YwmEgFA q) {
	NF32 result;
	nimfr_("length2", "quat.nim");
	result = (NF32)0;
	{
		NI i;
		NI res;
		i = (NI)0;
		nimln_(1986, "system.nim");
		res = ((NI) 0);
		{
			nimln_(1987, "system.nim");
			while (1) {
				NF32 T4_;
				NF32 T5_;
				NI TM_puszxb5eHZKmsb5EP4KzKQ_4;
				if (!(res <= ((NI) 3))) goto LA3;
				nimln_(1988, "system.nim");
				i = res;
				nimln_(186, "quat.nim");
				T4_ = (NF32)0;
				T4_ = X5BX5D__O1OvuULnXFY9b2jyEcFfrLA(q, i);
				T5_ = (NF32)0;
				T5_ = X5BX5D__O1OvuULnXFY9b2jyEcFfrLA(q, i);
				pluseq__0Q9c9ccOr82GxaUx3qtv9aCoQquat((&result), ((NF32)(T4_) * (NF32)(T5_)));
				nimln_(1989, "system.nim");
				TM_puszxb5eHZKmsb5EP4KzKQ_4 = addInt(res, ((NI) 1));
				res = (NI)(TM_puszxb5eHZKmsb5EP4KzKQ_4);
			} LA3: ;
		}
	}
	popFrame();
	return result;
}

N_NIMCALL(NF32, length_kG7Dk1nvxm5ySomPiPJnFQ)(tyObject_Quat_8OGz1DWD3GbPw26YwmEgFA q) {
	NF32 result;
	NF32 T1_;
	nimfr_("length", "quat.nim");
	result = (NF32)0;
	nimln_(189, "quat.nim");
	T1_ = (NF32)0;
	T1_ = length2_kG7Dk1nvxm5ySomPiPJnFQ_2(q);
	result = sqrtf(T1_);
	popFrame();
	return result;
}

N_NIMCALL(tyObject_Quat_8OGz1DWD3GbPw26YwmEgFA, normalize_9aGq4tI0kJTht8uYKISPt2Q)(tyObject_Quat_8OGz1DWD3GbPw26YwmEgFA q) {
	tyObject_Quat_8OGz1DWD3GbPw26YwmEgFA result;
	NF32 T1_;
	nimfr_("normalize", "quat.nim");
	memset((void*)(&result), 0, sizeof(result));
	nimln_(192, "quat.nim");
	T1_ = (NF32)0;
	T1_ = length_kG7Dk1nvxm5ySomPiPJnFQ(q);
	result = star__ACy88Lzc9cgWeEVEtOIkXEA(q, ((NF32)(1.0000000000000000e+00f) / (NF32)(T1_)));
	popFrame();
	return result;
}

N_NIMCALL(tyObject_Quat_8OGz1DWD3GbPw26YwmEgFA, quat_uw0g7WVS8gj0wu9cw8Tz9c9aw)(tyObject_Vec_8lp09c9aJ6sSqRDc8uUVfyuA u, tyObject_Vec_8lp09c9aJ6sSqRDc8uUVfyuA v) {
	tyObject_Quat_8OGz1DWD3GbPw26YwmEgFA result;
	tyObject_Vec_8lp09c9aJ6sSqRDc8uUVfyuA LocalW;
	NF32 Dot;
	tyObject_Quat_8OGz1DWD3GbPw26YwmEgFA q;
	NF32 T1_;
	NF32 T2_;
	NF32 T3_;
	nimfr_("quat", "quat.nim");
	memset((void*)(&result), 0, sizeof(result));
	nimln_(326, "quat.nim");
	LocalW = cross_u30ZqBLCPuracR4Z1FBPOQ(u, v);
	nimln_(327, "quat.nim");
	Dot = dot_fVg9b9b1P9aDx1N4voq9cgRWhQquat(u, v);
	nimln_(328, "quat.nim");
	T1_ = (NF32)0;
	T1_ = x_Xbi8c1XUPkUTWFDNj5l5oQvec(LocalW);
	T2_ = (NF32)0;
	T2_ = y_Xbi8c1XUPkUTWFDNj5l5oQ_2vec(LocalW);
	T3_ = (NF32)0;
	T3_ = z_Xbi8c1XUPkUTWFDNj5l5oQ_3vec(LocalW);
	q = quat_B3Tk7ibspUCeUKLupWvG9cQ_2quat(T1_, T2_, T3_, ((NF32)(1.0000000000000000e+00) + (NF32)(Dot)));
	nimln_(329, "quat.nim");
	result = normalize_9aGq4tI0kJTht8uYKISPt2Q(q);
	popFrame();
	return result;
}

static N_INLINE(tyObject_Vec_8lp09c9aJ6sSqRDc8uUVfyuA, yzx_QNKRCIoL02fVO14FHlc10Qvec)(tyObject_Vec_8lp09c9aJ6sSqRDc8uUVfyuA v) {
	tyObject_Vec_8lp09c9aJ6sSqRDc8uUVfyuA result;
	tyObject_Vec_8lp09c9aJ6sSqRDc8uUVfyuA T1_;
	nimfr_("yzx", "vec.nim");
	memset((void*)(&result), 0, sizeof(result));
	nimln_(216, "vec.nim");
	memset((void*)(&T1_), 0, sizeof(T1_));
	T1_.arr[0] = v.arr[(((NI) 1))- 0];
	T1_.arr[1] = v.arr[(((NI) 2))- 0];
	T1_.arr[2] = v.arr[(((NI) 0))- 0];
	result = T1_;
	popFrame();
	return result;
}

static N_INLINE(tyObject_Vec_8lp09c9aJ6sSqRDc8uUVfyuA, zxy_QNKRCIoL02fVO14FHlc10Q_2vec)(tyObject_Vec_8lp09c9aJ6sSqRDc8uUVfyuA v) {
	tyObject_Vec_8lp09c9aJ6sSqRDc8uUVfyuA result;
	tyObject_Vec_8lp09c9aJ6sSqRDc8uUVfyuA T1_;
	nimfr_("zxy", "vec.nim");
	memset((void*)(&result), 0, sizeof(result));
	nimln_(216, "vec.nim");
	memset((void*)(&T1_), 0, sizeof(T1_));
	T1_.arr[0] = v.arr[(((NI) 2))- 0];
	T1_.arr[1] = v.arr[(((NI) 0))- 0];
	T1_.arr[2] = v.arr[(((NI) 1))- 0];
	result = T1_;
	popFrame();
	return result;
}

static N_INLINE(tyObject_Vec_8lp09c9aJ6sSqRDc8uUVfyuA, star__J7vWjOv59bjwwYcDHMIUtEg_2vec)(tyObject_Vec_8lp09c9aJ6sSqRDc8uUVfyuA v, tyObject_Vec_8lp09c9aJ6sSqRDc8uUVfyuA u) {
	tyObject_Vec_8lp09c9aJ6sSqRDc8uUVfyuA result;
	nimfr_("*", "vec.nim");
	memset((void*)(&result), 0, sizeof(result));
	{
		NI ii;
		NI i;
		ii = (NI)0;
		nimln_(3847, "system.nim");
		i = ((NI) 0);
		{
			nimln_(3848, "system.nim");
			while (1) {
				NI TM_puszxb5eHZKmsb5EP4KzKQ_5;
				if (!(i < ((NI) 3))) goto LA3;
				nimln_(3849, "system.nim");
				ii = i;
				if ((NU)(ii) > (NU)(2)) raiseIndexError();
				nimln_(109, "vec.nim");
				if ((NU)(ii) > (NU)(2)) raiseIndexError();
				if ((NU)(ii) > (NU)(2)) raiseIndexError();
				result.arr[(ii)- 0] = ((NF32)(v.arr[(ii)- 0]) * (NF32)(u.arr[(ii)- 0]));
				nimln_(3850, "system.nim");
				TM_puszxb5eHZKmsb5EP4KzKQ_5 = addInt(i, ((NI) 1));
				i = (NI)(TM_puszxb5eHZKmsb5EP4KzKQ_5);
			} LA3: ;
		}
	}
	popFrame();
	return result;
}

static N_INLINE(tyObject_Vec_8lp09c9aJ6sSqRDc8uUVfyuA, minus__J7vWjOv59bjwwYcDHMIUtEgvec)(tyObject_Vec_8lp09c9aJ6sSqRDc8uUVfyuA v, tyObject_Vec_8lp09c9aJ6sSqRDc8uUVfyuA u) {
	tyObject_Vec_8lp09c9aJ6sSqRDc8uUVfyuA result;
	nimfr_("-", "vec.nim");
	memset((void*)(&result), 0, sizeof(result));
	{
		NI ii;
		NI i;
		ii = (NI)0;
		nimln_(3847, "system.nim");
		i = ((NI) 0);
		{
			nimln_(3848, "system.nim");
			while (1) {
				NI TM_puszxb5eHZKmsb5EP4KzKQ_6;
				if (!(i < ((NI) 3))) goto LA3;
				nimln_(3849, "system.nim");
				ii = i;
				if ((NU)(ii) > (NU)(2)) raiseIndexError();
				nimln_(109, "vec.nim");
				if ((NU)(ii) > (NU)(2)) raiseIndexError();
				if ((NU)(ii) > (NU)(2)) raiseIndexError();
				result.arr[(ii)- 0] = ((NF32)(v.arr[(ii)- 0]) - (NF32)(u.arr[(ii)- 0]));
				nimln_(3850, "system.nim");
				TM_puszxb5eHZKmsb5EP4KzKQ_6 = addInt(i, ((NI) 1));
				i = (NI)(TM_puszxb5eHZKmsb5EP4KzKQ_6);
			} LA3: ;
		}
	}
	popFrame();
	return result;
}

N_NIMCALL(tyObject_Quat_8OGz1DWD3GbPw26YwmEgFA, quatf_e4AGEGAbBg8gnjMDiPwKVQ_2)(tyObject_Vec_8lp09c9aJ6sSqRDc8uUVfyuA axis, NF32 angle) {
	tyObject_Quat_8OGz1DWD3GbPw26YwmEgFA result;
	nimfr_("quatf", "quat.nim");
	memset((void*)(&result), 0, sizeof(result));
	nimln_(336, "quat.nim");
	result = quat_e4AGEGAbBg8gnjMDiPwKVQ(axis, angle);
	popFrame();
	return result;
}

N_NIMCALL(tyObject_Quat_8OGz1DWD3GbPw26YwmEgFA, quatf_uw0g7WVS8gj0wu9cw8Tz9c9aw_2)(tyObject_Vec_8lp09c9aJ6sSqRDc8uUVfyuA u, tyObject_Vec_8lp09c9aJ6sSqRDc8uUVfyuA v) {
	tyObject_Quat_8OGz1DWD3GbPw26YwmEgFA result;
	nimfr_("quatf", "quat.nim");
	memset((void*)(&result), 0, sizeof(result));
	nimln_(337, "quat.nim");
	result = quat_uw0g7WVS8gj0wu9cw8Tz9c9aw(u, v);
	popFrame();
	return result;
}

N_NIMCALL(tyObject_Quat_8OGz1DWD3GbPw26YwmEgFA, quatf_X0cGfWDayZC5Zp1XKZFtKg)(tyObject_Mat_T4xVXfJBjoFESt9b1eXqtYg* mat) {
	tyObject_Quat_8OGz1DWD3GbPw26YwmEgFA result;
	nimfr_("quatf", "quat.nim");
	memset((void*)(&result), 0, sizeof(result));
	nimln_(338, "quat.nim");
	result = quat_Anu8hOIKhcfXwGCygNeQgg(mat);
	popFrame();
	return result;
}

N_NIMCALL(tyObject_Quat_8OGz1DWD3GbPw26YwmEgFA, quatf_PGZ6hsyjJ6sePt0ul8pKjw)(void) {
	tyObject_Quat_8OGz1DWD3GbPw26YwmEgFA result;
	tyObject_Quat_8OGz1DWD3GbPw26YwmEgFA T1_;
	nimfr_("quatf", "quat.nim");
	memset((void*)(&result), 0, sizeof(result));
	nimln_(339, "quat.nim");
	memset((void*)(&T1_), 0, sizeof(T1_));
	memcpy((void*)T1_.arr, (NIM_CONST void*)TM_puszxb5eHZKmsb5EP4KzKQ_7, sizeof(tyArray_9aTCwbdg1cSQimdVd0OEKVw));
	result = T1_;
	popFrame();
	return result;
}

static N_INLINE(tyObject_Quat_yJAd1NQB8I67sGeTRIsbNw, quatd_0lqGzO7AmX7PhRWVxaVspQquat)(NF x, NF y, NF z, NF w) {
	tyObject_Quat_yJAd1NQB8I67sGeTRIsbNw result;
	tyObject_Quat_yJAd1NQB8I67sGeTRIsbNw T1_;
	nimfr_("quatd", "quat.nim");
	memset((void*)(&result), 0, sizeof(result));
	nimln_(341, "quat.nim");
	memset((void*)(&T1_), 0, sizeof(T1_));
	T1_.arr[0] = x;
	T1_.arr[1] = y;
	T1_.arr[2] = z;
	T1_.arr[3] = w;
	result = T1_;
	popFrame();
	return result;
}

static N_INLINE(NF, X5BX5D__HoOotoUjRplz2l22Kg9bGJQquat)(tyObject_Vec_S5njPDIR1N39afJ9a6EQzdbA* v, NI ix) {
	NF result;
	nimfr_("[]", "vec.nim");
	result = (NF)0;
	nimln_(149, "vec.nim");
	if ((NU)(ix) > (NU)(2)) raiseIndexError();
	result = (*v).arr[(ix)- 0];
	popFrame();
	return result;
}

static N_INLINE(tyObject_Vec_S5njPDIR1N39afJ9a6EQzdbA, X5BX5D__DFRvm3Wm5fJ7q7ShD5ku3wquat)(tyObject_Mat_HtRb1O5aOVprrfb4PBLHfQ* v, NI ix) {
	tyObject_Vec_S5njPDIR1N39afJ9a6EQzdbA result;
	nimfr_("[]", "mat.nim");
	memset((void*)(&result), 0, sizeof(result));
	nimln_(36, "mat.nim");
	if ((NU)(ix) > (NU)(2)) raiseIndexError();
	result = (*v).arr[(ix)- 0];
	popFrame();
	return result;
}

N_NIMCALL(void, X5BX5Deq__CXmgG9aNgIv0zqBZasUbPGg)(tyObject_Quat_yJAd1NQB8I67sGeTRIsbNw* q, NI i, NF val) {
	nimfr_("[]=", "quat.nim");
	if ((NU)(i) > (NU)(3)) raiseIndexError();
	nimln_(16, "quat.nim");
	(*q).arr[(i)- 0] = val;
	popFrame();
}

N_NIMCALL(void, weq__hUQCTX9aE3AffSKdLKY7vjw)(tyObject_Quat_yJAd1NQB8I67sGeTRIsbNw* q, NF v) {
	nimfr_("w=", "quat.nim");
	nimln_(61, "quat.nim");
	X5BX5Deq__CXmgG9aNgIv0zqBZasUbPGg(q, ((NI) 3), v);
	popFrame();
}

N_NIMCALL(void, xeq__hUQCTX9aE3AffSKdLKY7vjw_2)(tyObject_Quat_yJAd1NQB8I67sGeTRIsbNw* q, NF v) {
	nimfr_("x=", "quat.nim");
	nimln_(52, "quat.nim");
	X5BX5Deq__CXmgG9aNgIv0zqBZasUbPGg(q, ((NI) 0), v);
	popFrame();
}

N_NIMCALL(void, yeq__hUQCTX9aE3AffSKdLKY7vjw_3)(tyObject_Quat_yJAd1NQB8I67sGeTRIsbNw* q, NF v) {
	nimfr_("y=", "quat.nim");
	nimln_(55, "quat.nim");
	X5BX5Deq__CXmgG9aNgIv0zqBZasUbPGg(q, ((NI) 1), v);
	popFrame();
}

N_NIMCALL(void, zeq__hUQCTX9aE3AffSKdLKY7vjw_4)(tyObject_Quat_yJAd1NQB8I67sGeTRIsbNw* q, NF v) {
	nimfr_("z=", "quat.nim");
	nimln_(58, "quat.nim");
	X5BX5Deq__CXmgG9aNgIv0zqBZasUbPGg(q, ((NI) 2), v);
	popFrame();
}

N_NIMCALL(tyObject_Quat_yJAd1NQB8I67sGeTRIsbNw, quat_9bg9b9a9bGItEerqpTBegmuR1w)(tyObject_Mat_HtRb1O5aOVprrfb4PBLHfQ* m) {
	tyObject_Quat_yJAd1NQB8I67sGeTRIsbNw result;
	NF fourXSquaredMinus1;
	tyObject_Vec_S5njPDIR1N39afJ9a6EQzdbA T1_;
	NF T2_;
	tyObject_Vec_S5njPDIR1N39afJ9a6EQzdbA T3_;
	NF T4_;
	tyObject_Vec_S5njPDIR1N39afJ9a6EQzdbA T5_;
	NF T6_;
	NF fourYSquaredMinus1;
	tyObject_Vec_S5njPDIR1N39afJ9a6EQzdbA T7_;
	NF T8_;
	tyObject_Vec_S5njPDIR1N39afJ9a6EQzdbA T9_;
	NF T10_;
	tyObject_Vec_S5njPDIR1N39afJ9a6EQzdbA T11_;
	NF T12_;
	NF fourZSquaredMinus1;
	tyObject_Vec_S5njPDIR1N39afJ9a6EQzdbA T13_;
	NF T14_;
	tyObject_Vec_S5njPDIR1N39afJ9a6EQzdbA T15_;
	NF T16_;
	tyObject_Vec_S5njPDIR1N39afJ9a6EQzdbA T17_;
	NF T18_;
	NF fourWSquaredMinus1;
	tyObject_Vec_S5njPDIR1N39afJ9a6EQzdbA T19_;
	NF T20_;
	tyObject_Vec_S5njPDIR1N39afJ9a6EQzdbA T21_;
	NF T22_;
	tyObject_Vec_S5njPDIR1N39afJ9a6EQzdbA T23_;
	NF T24_;
	NI biggestIndex;
	NF fourBiggestSquaredMinus1;
	NF biggestVal;
	NF T37_;
	NF mult;
	nimfr_("quat", "quat.nim");
	memset((void*)(&result), 0, sizeof(result));
	nimln_(80, "quat.nim");
	T1_ = X5BX5D__DFRvm3Wm5fJ7q7ShD5ku3wquat(m, ((NI) 0));
	T2_ = (NF)0;
	T2_ = X5BX5D__HoOotoUjRplz2l22Kg9bGJQquat((&T1_), ((NI) 0));
	T3_ = X5BX5D__DFRvm3Wm5fJ7q7ShD5ku3wquat(m, ((NI) 1));
	T4_ = (NF)0;
	T4_ = X5BX5D__HoOotoUjRplz2l22Kg9bGJQquat((&T3_), ((NI) 1));
	T5_ = X5BX5D__DFRvm3Wm5fJ7q7ShD5ku3wquat(m, ((NI) 2));
	T6_ = (NF)0;
	T6_ = X5BX5D__HoOotoUjRplz2l22Kg9bGJQquat((&T5_), ((NI) 2));
	fourXSquaredMinus1 = ((NF)(((NF)(T2_) - (NF)(T4_))) - (NF)(T6_));
	nimln_(81, "quat.nim");
	T7_ = X5BX5D__DFRvm3Wm5fJ7q7ShD5ku3wquat(m, ((NI) 1));
	T8_ = (NF)0;
	T8_ = X5BX5D__HoOotoUjRplz2l22Kg9bGJQquat((&T7_), ((NI) 1));
	T9_ = X5BX5D__DFRvm3Wm5fJ7q7ShD5ku3wquat(m, ((NI) 0));
	T10_ = (NF)0;
	T10_ = X5BX5D__HoOotoUjRplz2l22Kg9bGJQquat((&T9_), ((NI) 0));
	T11_ = X5BX5D__DFRvm3Wm5fJ7q7ShD5ku3wquat(m, ((NI) 2));
	T12_ = (NF)0;
	T12_ = X5BX5D__HoOotoUjRplz2l22Kg9bGJQquat((&T11_), ((NI) 2));
	fourYSquaredMinus1 = ((NF)(((NF)(T8_) - (NF)(T10_))) - (NF)(T12_));
	nimln_(82, "quat.nim");
	T13_ = X5BX5D__DFRvm3Wm5fJ7q7ShD5ku3wquat(m, ((NI) 2));
	T14_ = (NF)0;
	T14_ = X5BX5D__HoOotoUjRplz2l22Kg9bGJQquat((&T13_), ((NI) 2));
	T15_ = X5BX5D__DFRvm3Wm5fJ7q7ShD5ku3wquat(m, ((NI) 0));
	T16_ = (NF)0;
	T16_ = X5BX5D__HoOotoUjRplz2l22Kg9bGJQquat((&T15_), ((NI) 0));
	T17_ = X5BX5D__DFRvm3Wm5fJ7q7ShD5ku3wquat(m, ((NI) 1));
	T18_ = (NF)0;
	T18_ = X5BX5D__HoOotoUjRplz2l22Kg9bGJQquat((&T17_), ((NI) 1));
	fourZSquaredMinus1 = ((NF)(((NF)(T14_) - (NF)(T16_))) - (NF)(T18_));
	nimln_(83, "quat.nim");
	T19_ = X5BX5D__DFRvm3Wm5fJ7q7ShD5ku3wquat(m, ((NI) 0));
	T20_ = (NF)0;
	T20_ = X5BX5D__HoOotoUjRplz2l22Kg9bGJQquat((&T19_), ((NI) 0));
	T21_ = X5BX5D__DFRvm3Wm5fJ7q7ShD5ku3wquat(m, ((NI) 1));
	T22_ = (NF)0;
	T22_ = X5BX5D__HoOotoUjRplz2l22Kg9bGJQquat((&T21_), ((NI) 1));
	T23_ = X5BX5D__DFRvm3Wm5fJ7q7ShD5ku3wquat(m, ((NI) 2));
	T24_ = (NF)0;
	T24_ = X5BX5D__HoOotoUjRplz2l22Kg9bGJQquat((&T23_), ((NI) 2));
	fourWSquaredMinus1 = ((NF)(((NF)(T20_) + (NF)(T22_))) + (NF)(T24_));
	nimln_(85, "quat.nim");
	biggestIndex = ((NI) 0);
	nimln_(86, "quat.nim");
	fourBiggestSquaredMinus1 = fourWSquaredMinus1;
	nimln_(87, "quat.nim");
	{
		if (!(fourBiggestSquaredMinus1 < fourXSquaredMinus1)) goto LA27_;
		nimln_(88, "quat.nim");
		fourBiggestSquaredMinus1 = fourXSquaredMinus1;
		nimln_(89, "quat.nim");
		biggestIndex = ((NI) 1);
	}
	LA27_: ;
	nimln_(90, "quat.nim");
	{
		if (!(fourBiggestSquaredMinus1 < fourYSquaredMinus1)) goto LA31_;
		nimln_(91, "quat.nim");
		fourBiggestSquaredMinus1 = fourYSquaredMinus1;
		nimln_(92, "quat.nim");
		biggestIndex = ((NI) 2);
	}
	LA31_: ;
	nimln_(93, "quat.nim");
	{
		if (!(fourBiggestSquaredMinus1 < fourZSquaredMinus1)) goto LA35_;
		nimln_(94, "quat.nim");
		fourBiggestSquaredMinus1 = fourZSquaredMinus1;
		nimln_(95, "quat.nim");
		biggestIndex = ((NI) 3);
	}
	LA35_: ;
	nimln_(97, "quat.nim");
	T37_ = (NF)0;
	T37_ = sqrt(((NF)(fourBiggestSquaredMinus1) + (NF)(1.0000000000000000e+00)));
	biggestVal = ((NF)(T37_) * (NF)(5.0000000000000000e-01));
	nimln_(98, "quat.nim");
	mult = ((NF)(2.5000000000000000e-01) / (NF)(biggestVal));
	nimln_(100, "quat.nim");
	switch (biggestIndex) {
	case ((NI) 0):
	{
		tyObject_Vec_S5njPDIR1N39afJ9a6EQzdbA T39_;
		NF T40_;
		tyObject_Vec_S5njPDIR1N39afJ9a6EQzdbA T41_;
		NF T42_;
		tyObject_Vec_S5njPDIR1N39afJ9a6EQzdbA T43_;
		NF T44_;
		tyObject_Vec_S5njPDIR1N39afJ9a6EQzdbA T45_;
		NF T46_;
		tyObject_Vec_S5njPDIR1N39afJ9a6EQzdbA T47_;
		NF T48_;
		tyObject_Vec_S5njPDIR1N39afJ9a6EQzdbA T49_;
		NF T50_;
		nimln_(102, "quat.nim");
		weq__hUQCTX9aE3AffSKdLKY7vjw((&result), biggestVal);
		nimln_(103, "quat.nim");
		T39_ = X5BX5D__DFRvm3Wm5fJ7q7ShD5ku3wquat(m, ((NI) 1));
		T40_ = (NF)0;
		T40_ = X5BX5D__HoOotoUjRplz2l22Kg9bGJQquat((&T39_), ((NI) 2));
		T41_ = X5BX5D__DFRvm3Wm5fJ7q7ShD5ku3wquat(m, ((NI) 2));
		T42_ = (NF)0;
		T42_ = X5BX5D__HoOotoUjRplz2l22Kg9bGJQquat((&T41_), ((NI) 1));
		xeq__hUQCTX9aE3AffSKdLKY7vjw_2((&result), ((NF)(((NF)(T40_) - (NF)(T42_))) * (NF)(mult)));
		nimln_(104, "quat.nim");
		T43_ = X5BX5D__DFRvm3Wm5fJ7q7ShD5ku3wquat(m, ((NI) 2));
		T44_ = (NF)0;
		T44_ = X5BX5D__HoOotoUjRplz2l22Kg9bGJQquat((&T43_), ((NI) 0));
		T45_ = X5BX5D__DFRvm3Wm5fJ7q7ShD5ku3wquat(m, ((NI) 0));
		T46_ = (NF)0;
		T46_ = X5BX5D__HoOotoUjRplz2l22Kg9bGJQquat((&T45_), ((NI) 2));
		yeq__hUQCTX9aE3AffSKdLKY7vjw_3((&result), ((NF)(((NF)(T44_) - (NF)(T46_))) * (NF)(mult)));
		nimln_(105, "quat.nim");
		T47_ = X5BX5D__DFRvm3Wm5fJ7q7ShD5ku3wquat(m, ((NI) 0));
		T48_ = (NF)0;
		T48_ = X5BX5D__HoOotoUjRplz2l22Kg9bGJQquat((&T47_), ((NI) 1));
		T49_ = X5BX5D__DFRvm3Wm5fJ7q7ShD5ku3wquat(m, ((NI) 1));
		T50_ = (NF)0;
		T50_ = X5BX5D__HoOotoUjRplz2l22Kg9bGJQquat((&T49_), ((NI) 0));
		zeq__hUQCTX9aE3AffSKdLKY7vjw_4((&result), ((NF)(((NF)(T48_) - (NF)(T50_))) * (NF)(mult)));
	}
	break;
	case ((NI) 1):
	{
		tyObject_Vec_S5njPDIR1N39afJ9a6EQzdbA T52_;
		NF T53_;
		tyObject_Vec_S5njPDIR1N39afJ9a6EQzdbA T54_;
		NF T55_;
		tyObject_Vec_S5njPDIR1N39afJ9a6EQzdbA T56_;
		NF T57_;
		tyObject_Vec_S5njPDIR1N39afJ9a6EQzdbA T58_;
		NF T59_;
		tyObject_Vec_S5njPDIR1N39afJ9a6EQzdbA T60_;
		NF T61_;
		tyObject_Vec_S5njPDIR1N39afJ9a6EQzdbA T62_;
		NF T63_;
		nimln_(107, "quat.nim");
		T52_ = X5BX5D__DFRvm3Wm5fJ7q7ShD5ku3wquat(m, ((NI) 1));
		T53_ = (NF)0;
		T53_ = X5BX5D__HoOotoUjRplz2l22Kg9bGJQquat((&T52_), ((NI) 2));
		T54_ = X5BX5D__DFRvm3Wm5fJ7q7ShD5ku3wquat(m, ((NI) 2));
		T55_ = (NF)0;
		T55_ = X5BX5D__HoOotoUjRplz2l22Kg9bGJQquat((&T54_), ((NI) 1));
		weq__hUQCTX9aE3AffSKdLKY7vjw((&result), ((NF)(((NF)(T53_) - (NF)(T55_))) * (NF)(mult)));
		nimln_(108, "quat.nim");
		xeq__hUQCTX9aE3AffSKdLKY7vjw_2((&result), biggestVal);
		nimln_(109, "quat.nim");
		T56_ = X5BX5D__DFRvm3Wm5fJ7q7ShD5ku3wquat(m, ((NI) 0));
		T57_ = (NF)0;
		T57_ = X5BX5D__HoOotoUjRplz2l22Kg9bGJQquat((&T56_), ((NI) 1));
		T58_ = X5BX5D__DFRvm3Wm5fJ7q7ShD5ku3wquat(m, ((NI) 1));
		T59_ = (NF)0;
		T59_ = X5BX5D__HoOotoUjRplz2l22Kg9bGJQquat((&T58_), ((NI) 0));
		yeq__hUQCTX9aE3AffSKdLKY7vjw_3((&result), ((NF)(((NF)(T57_) + (NF)(T59_))) * (NF)(mult)));
		nimln_(110, "quat.nim");
		T60_ = X5BX5D__DFRvm3Wm5fJ7q7ShD5ku3wquat(m, ((NI) 2));
		T61_ = (NF)0;
		T61_ = X5BX5D__HoOotoUjRplz2l22Kg9bGJQquat((&T60_), ((NI) 0));
		T62_ = X5BX5D__DFRvm3Wm5fJ7q7ShD5ku3wquat(m, ((NI) 0));
		T63_ = (NF)0;
		T63_ = X5BX5D__HoOotoUjRplz2l22Kg9bGJQquat((&T62_), ((NI) 2));
		zeq__hUQCTX9aE3AffSKdLKY7vjw_4((&result), ((NF)(((NF)(T61_) + (NF)(T63_))) * (NF)(mult)));
	}
	break;
	case ((NI) 2):
	{
		tyObject_Vec_S5njPDIR1N39afJ9a6EQzdbA T65_;
		NF T66_;
		tyObject_Vec_S5njPDIR1N39afJ9a6EQzdbA T67_;
		NF T68_;
		tyObject_Vec_S5njPDIR1N39afJ9a6EQzdbA T69_;
		NF T70_;
		tyObject_Vec_S5njPDIR1N39afJ9a6EQzdbA T71_;
		NF T72_;
		tyObject_Vec_S5njPDIR1N39afJ9a6EQzdbA T73_;
		NF T74_;
		tyObject_Vec_S5njPDIR1N39afJ9a6EQzdbA T75_;
		NF T76_;
		nimln_(112, "quat.nim");
		T65_ = X5BX5D__DFRvm3Wm5fJ7q7ShD5ku3wquat(m, ((NI) 2));
		T66_ = (NF)0;
		T66_ = X5BX5D__HoOotoUjRplz2l22Kg9bGJQquat((&T65_), ((NI) 0));
		T67_ = X5BX5D__DFRvm3Wm5fJ7q7ShD5ku3wquat(m, ((NI) 0));
		T68_ = (NF)0;
		T68_ = X5BX5D__HoOotoUjRplz2l22Kg9bGJQquat((&T67_), ((NI) 2));
		weq__hUQCTX9aE3AffSKdLKY7vjw((&result), ((NF)(((NF)(T66_) - (NF)(T68_))) * (NF)(mult)));
		nimln_(113, "quat.nim");
		T69_ = X5BX5D__DFRvm3Wm5fJ7q7ShD5ku3wquat(m, ((NI) 0));
		T70_ = (NF)0;
		T70_ = X5BX5D__HoOotoUjRplz2l22Kg9bGJQquat((&T69_), ((NI) 1));
		T71_ = X5BX5D__DFRvm3Wm5fJ7q7ShD5ku3wquat(m, ((NI) 1));
		T72_ = (NF)0;
		T72_ = X5BX5D__HoOotoUjRplz2l22Kg9bGJQquat((&T71_), ((NI) 0));
		xeq__hUQCTX9aE3AffSKdLKY7vjw_2((&result), ((NF)(((NF)(T70_) + (NF)(T72_))) * (NF)(mult)));
		nimln_(114, "quat.nim");
		yeq__hUQCTX9aE3AffSKdLKY7vjw_3((&result), biggestVal);
		nimln_(115, "quat.nim");
		T73_ = X5BX5D__DFRvm3Wm5fJ7q7ShD5ku3wquat(m, ((NI) 1));
		T74_ = (NF)0;
		T74_ = X5BX5D__HoOotoUjRplz2l22Kg9bGJQquat((&T73_), ((NI) 2));
		T75_ = X5BX5D__DFRvm3Wm5fJ7q7ShD5ku3wquat(m, ((NI) 2));
		T76_ = (NF)0;
		T76_ = X5BX5D__HoOotoUjRplz2l22Kg9bGJQquat((&T75_), ((NI) 1));
		zeq__hUQCTX9aE3AffSKdLKY7vjw_4((&result), ((NF)(((NF)(T74_) + (NF)(T76_))) * (NF)(mult)));
	}
	break;
	case ((NI) 3):
	{
		tyObject_Vec_S5njPDIR1N39afJ9a6EQzdbA T78_;
		NF T79_;
		tyObject_Vec_S5njPDIR1N39afJ9a6EQzdbA T80_;
		NF T81_;
		tyObject_Vec_S5njPDIR1N39afJ9a6EQzdbA T82_;
		NF T83_;
		tyObject_Vec_S5njPDIR1N39afJ9a6EQzdbA T84_;
		NF T85_;
		tyObject_Vec_S5njPDIR1N39afJ9a6EQzdbA T86_;
		NF T87_;
		tyObject_Vec_S5njPDIR1N39afJ9a6EQzdbA T88_;
		NF T89_;
		nimln_(117, "quat.nim");
		T78_ = X5BX5D__DFRvm3Wm5fJ7q7ShD5ku3wquat(m, ((NI) 0));
		T79_ = (NF)0;
		T79_ = X5BX5D__HoOotoUjRplz2l22Kg9bGJQquat((&T78_), ((NI) 1));
		T80_ = X5BX5D__DFRvm3Wm5fJ7q7ShD5ku3wquat(m, ((NI) 1));
		T81_ = (NF)0;
		T81_ = X5BX5D__HoOotoUjRplz2l22Kg9bGJQquat((&T80_), ((NI) 0));
		weq__hUQCTX9aE3AffSKdLKY7vjw((&result), ((NF)(((NF)(T79_) - (NF)(T81_))) * (NF)(mult)));
		nimln_(118, "quat.nim");
		T82_ = X5BX5D__DFRvm3Wm5fJ7q7ShD5ku3wquat(m, ((NI) 2));
		T83_ = (NF)0;
		T83_ = X5BX5D__HoOotoUjRplz2l22Kg9bGJQquat((&T82_), ((NI) 0));
		T84_ = X5BX5D__DFRvm3Wm5fJ7q7ShD5ku3wquat(m, ((NI) 0));
		T85_ = (NF)0;
		T85_ = X5BX5D__HoOotoUjRplz2l22Kg9bGJQquat((&T84_), ((NI) 2));
		xeq__hUQCTX9aE3AffSKdLKY7vjw_2((&result), ((NF)(((NF)(T83_) + (NF)(T85_))) * (NF)(mult)));
		nimln_(119, "quat.nim");
		T86_ = X5BX5D__DFRvm3Wm5fJ7q7ShD5ku3wquat(m, ((NI) 1));
		T87_ = (NF)0;
		T87_ = X5BX5D__HoOotoUjRplz2l22Kg9bGJQquat((&T86_), ((NI) 2));
		T88_ = X5BX5D__DFRvm3Wm5fJ7q7ShD5ku3wquat(m, ((NI) 2));
		T89_ = (NF)0;
		T89_ = X5BX5D__HoOotoUjRplz2l22Kg9bGJQquat((&T88_), ((NI) 1));
		yeq__hUQCTX9aE3AffSKdLKY7vjw_3((&result), ((NF)(((NF)(T87_) + (NF)(T89_))) * (NF)(mult)));
		nimln_(120, "quat.nim");
		zeq__hUQCTX9aE3AffSKdLKY7vjw_4((&result), biggestVal);
	}
	break;
	}
	popFrame();
	return result;
}

static N_INLINE(tyObject_Vec_S5njPDIR1N39afJ9a6EQzdbA, xyz_PjuPWi0lAXGKqBB2kytmngquat)(tyObject_Vec_ajluWiFZ8tTU9b0kwuUOFAQ* v) {
	tyObject_Vec_S5njPDIR1N39afJ9a6EQzdbA result;
	tyObject_Vec_S5njPDIR1N39afJ9a6EQzdbA T1_;
	nimfr_("xyz", "vec.nim");
	memset((void*)(&result), 0, sizeof(result));
	nimln_(216, "vec.nim");
	memset((void*)(&T1_), 0, sizeof(T1_));
	T1_.arr[0] = (*v).arr[(((NI) 0))- 0];
	T1_.arr[1] = (*v).arr[(((NI) 1))- 0];
	T1_.arr[2] = (*v).arr[(((NI) 2))- 0];
	result = T1_;
	popFrame();
	return result;
}

static N_INLINE(tyObject_Vec_ajluWiFZ8tTU9b0kwuUOFAQ, X5BX5D__bDnwjaYhlA4Lch0wvQp59bAquat)(tyObject_Mat_heEQpaDfEb6loQ9cBE724ag* v, NI ix) {
	tyObject_Vec_ajluWiFZ8tTU9b0kwuUOFAQ result;
	nimfr_("[]", "mat.nim");
	memset((void*)(&result), 0, sizeof(result));
	nimln_(36, "mat.nim");
	if ((NU)(ix) > (NU)(3)) raiseIndexError();
	result = (*v).arr[(ix)- 0];
	popFrame();
	return result;
}

N_NIMCALL(tyObject_Quat_yJAd1NQB8I67sGeTRIsbNw, quat_YgjR5GQ2DyEtw5vNWaVUjw)(tyObject_Mat_heEQpaDfEb6loQ9cBE724ag* mat) {
	tyObject_Quat_yJAd1NQB8I67sGeTRIsbNw result;
	tyObject_Vec_ajluWiFZ8tTU9b0kwuUOFAQ T1_;
	tyObject_Vec_S5njPDIR1N39afJ9a6EQzdbA T2_;
	tyObject_Vec_ajluWiFZ8tTU9b0kwuUOFAQ T3_;
	tyObject_Vec_S5njPDIR1N39afJ9a6EQzdbA T4_;
	tyObject_Vec_ajluWiFZ8tTU9b0kwuUOFAQ T5_;
	tyObject_Vec_S5njPDIR1N39afJ9a6EQzdbA T6_;
	tyObject_Mat_HtRb1O5aOVprrfb4PBLHfQ T7_;
	nimfr_("quat", "quat.nim");
	memset((void*)(&result), 0, sizeof(result));
	nimln_(123, "quat.nim");
	nimln_(124, "quat.nim");
	T1_ = X5BX5D__bDnwjaYhlA4Lch0wvQp59bAquat(mat, ((NI) 0));
	T2_ = xyz_PjuPWi0lAXGKqBB2kytmngquat((&T1_));
	T3_ = X5BX5D__bDnwjaYhlA4Lch0wvQp59bAquat(mat, ((NI) 1));
	T4_ = xyz_PjuPWi0lAXGKqBB2kytmngquat((&T3_));
	T5_ = X5BX5D__bDnwjaYhlA4Lch0wvQp59bAquat(mat, ((NI) 2));
	T6_ = xyz_PjuPWi0lAXGKqBB2kytmngquat((&T5_));
	T7_ = mat3_GnV39c9bfQfKHmgIWBodVH8A((&T2_), (&T4_), (&T6_));
	result = quat_9bg9b9a9bGItEerqpTBegmuR1w((&T7_));
	popFrame();
	return result;
}

static N_INLINE(NF, x_NpfOyWKi6CLtEhMWqkmyuQvec)(tyObject_Vec_S5njPDIR1N39afJ9a6EQzdbA* v) {
	NF result;
	nimfr_("x", "vec.nim");
	result = (NF)0;
	nimln_(255, "vec.nim");
	result = (*v).arr[(((NI) 0))- 0];
	popFrame();
	return result;
}

static N_INLINE(NF, y_NpfOyWKi6CLtEhMWqkmyuQ_2vec)(tyObject_Vec_S5njPDIR1N39afJ9a6EQzdbA* v) {
	NF result;
	nimfr_("y", "vec.nim");
	result = (NF)0;
	nimln_(255, "vec.nim");
	result = (*v).arr[(((NI) 1))- 0];
	popFrame();
	return result;
}

static N_INLINE(NF, z_NpfOyWKi6CLtEhMWqkmyuQ_3vec)(tyObject_Vec_S5njPDIR1N39afJ9a6EQzdbA* v) {
	NF result;
	nimfr_("z", "vec.nim");
	result = (NF)0;
	nimln_(255, "vec.nim");
	result = (*v).arr[(((NI) 2))- 0];
	popFrame();
	return result;
}

N_NIMCALL(tyObject_Quat_yJAd1NQB8I67sGeTRIsbNw, quat_0gnPEPPD5U13KUM09ao5wFA)(tyObject_Vec_S5njPDIR1N39afJ9a6EQzdbA* axis, NF angle) {
	tyObject_Quat_yJAd1NQB8I67sGeTRIsbNw result;
	NF s;
	NF T1_;
	NF T2_;
	NF T3_;
	NF T4_;
	nimfr_("quat", "quat.nim");
	memset((void*)(&result), 0, sizeof(result));
	nimln_(71, "quat.nim");
	s = sin(((NF)(angle) / (NF)(2.0000000000000000e+00)));
	nimln_(72, "quat.nim");
	T1_ = (NF)0;
	T1_ = x_NpfOyWKi6CLtEhMWqkmyuQvec(axis);
	xeq__hUQCTX9aE3AffSKdLKY7vjw_2((&result), ((NF)(T1_) * (NF)(s)));
	nimln_(73, "quat.nim");
	T2_ = (NF)0;
	T2_ = y_NpfOyWKi6CLtEhMWqkmyuQ_2vec(axis);
	yeq__hUQCTX9aE3AffSKdLKY7vjw_3((&result), ((NF)(T2_) * (NF)(s)));
	nimln_(74, "quat.nim");
	T3_ = (NF)0;
	T3_ = z_NpfOyWKi6CLtEhMWqkmyuQ_3vec(axis);
	zeq__hUQCTX9aE3AffSKdLKY7vjw_4((&result), ((NF)(T3_) * (NF)(s)));
	nimln_(75, "quat.nim");
	T4_ = (NF)0;
	T4_ = cos(((NF)(angle) / (NF)(2.0000000000000000e+00)));
	weq__hUQCTX9aE3AffSKdLKY7vjw((&result), T4_);
	popFrame();
	return result;
}

static N_INLINE(tyObject_Quat_yJAd1NQB8I67sGeTRIsbNw, quat_0lqGzO7AmX7PhRWVxaVspQ_2quat)(NF x, NF y, NF z, NF w) {
	tyObject_Quat_yJAd1NQB8I67sGeTRIsbNw result;
	nimfr_("quat", "quat.nim");
	memset((void*)(&result), 0, sizeof(result));
	nimln_(68, "quat.nim");
	result.arr[0] = x;
	result.arr[1] = y;
	result.arr[2] = z;
	result.arr[3] = w;
	popFrame();
	return result;
}

static N_INLINE(void, pluseq__7kHiltrvRlcg6wSYR3CxAw_2strutils)(NF* x, NF y) {
	nimfr_("+=", "system.nim");
	nimln_(3549, "system.nim");
	(*x) = ((NF)((*x)) + (NF)(y));
	popFrame();
}

static N_INLINE(NF, dot_IcSwLAapwm3k9a3IG4M9bUSQquat)(tyObject_Vec_S5njPDIR1N39afJ9a6EQzdbA* u, tyObject_Vec_S5njPDIR1N39afJ9a6EQzdbA* v) {
	NF result;
	nimfr_("dot", "vec.nim");
	result = (NF)0;
	{
		NI i;
		NI i_2;
		i = (NI)0;
		nimln_(3847, "system.nim");
		i_2 = ((NI) 0);
		{
			nimln_(3848, "system.nim");
			while (1) {
				NF T4_;
				NF T5_;
				NI TM_puszxb5eHZKmsb5EP4KzKQ_8;
				if (!(i_2 < ((NI) 3))) goto LA3;
				nimln_(3849, "system.nim");
				i = i_2;
				nimln_(478, "vec.nim");
				T4_ = (NF)0;
				T4_ = X5BX5D__HoOotoUjRplz2l22Kg9bGJQquat(u, i);
				T5_ = (NF)0;
				T5_ = X5BX5D__HoOotoUjRplz2l22Kg9bGJQquat(v, i);
				pluseq__7kHiltrvRlcg6wSYR3CxAw_2strutils((&result), ((NF)(T4_) * (NF)(T5_)));
				nimln_(3850, "system.nim");
				TM_puszxb5eHZKmsb5EP4KzKQ_8 = addInt(i_2, ((NI) 1));
				i_2 = (NI)(TM_puszxb5eHZKmsb5EP4KzKQ_8);
			} LA3: ;
		}
	}
	popFrame();
	return result;
}

N_NIMCALL(NF, X5BX5D__W9bJigMDx5Mue3nTmF9bxFPw)(tyObject_Quat_yJAd1NQB8I67sGeTRIsbNw* q, NI i) {
	NF result;
	nimfr_("[]", "quat.nim");
	result = (NF)0;
	nimln_(10, "quat.nim");
	if ((NU)(i) > (NU)(3)) raiseIndexError();
	result = (*q).arr[(i)- 0];
	popFrame();
	return result;
}

N_NIMCALL(tyObject_Quat_yJAd1NQB8I67sGeTRIsbNw, star__XWgUovB1XZVq9curgVFw4Qg)(tyObject_Quat_yJAd1NQB8I67sGeTRIsbNw* q, NF s) {
	tyObject_Quat_yJAd1NQB8I67sGeTRIsbNw result;
	nimfr_("*", "quat.nim");
	memset((void*)(&result), 0, sizeof(result));
	{
		NI i;
		NI res;
		i = (NI)0;
		nimln_(1986, "system.nim");
		res = ((NI) 0);
		{
			nimln_(1987, "system.nim");
			while (1) {
				NF T4_;
				NI TM_puszxb5eHZKmsb5EP4KzKQ_9;
				if (!(res <= ((NI) 3))) goto LA3;
				nimln_(1988, "system.nim");
				i = res;
				nimln_(135, "quat.nim");
				T4_ = (NF)0;
				T4_ = X5BX5D__W9bJigMDx5Mue3nTmF9bxFPw(q, i);
				X5BX5Deq__CXmgG9aNgIv0zqBZasUbPGg((&result), i, ((NF)(T4_) * (NF)(s)));
				nimln_(1989, "system.nim");
				TM_puszxb5eHZKmsb5EP4KzKQ_9 = addInt(res, ((NI) 1));
				res = (NI)(TM_puszxb5eHZKmsb5EP4KzKQ_9);
			} LA3: ;
		}
	}
	popFrame();
	return result;
}

N_NIMCALL(NF, length2_e0H9aq8ETGjS9by7Evwdd3dA_2)(tyObject_Quat_yJAd1NQB8I67sGeTRIsbNw* q) {
	NF result;
	nimfr_("length2", "quat.nim");
	result = (NF)0;
	{
		NI i;
		NI res;
		i = (NI)0;
		nimln_(1986, "system.nim");
		res = ((NI) 0);
		{
			nimln_(1987, "system.nim");
			while (1) {
				NF T4_;
				NF T5_;
				NI TM_puszxb5eHZKmsb5EP4KzKQ_10;
				if (!(res <= ((NI) 3))) goto LA3;
				nimln_(1988, "system.nim");
				i = res;
				nimln_(186, "quat.nim");
				T4_ = (NF)0;
				T4_ = X5BX5D__W9bJigMDx5Mue3nTmF9bxFPw(q, i);
				T5_ = (NF)0;
				T5_ = X5BX5D__W9bJigMDx5Mue3nTmF9bxFPw(q, i);
				pluseq__7kHiltrvRlcg6wSYR3CxAw_2strutils((&result), ((NF)(T4_) * (NF)(T5_)));
				nimln_(1989, "system.nim");
				TM_puszxb5eHZKmsb5EP4KzKQ_10 = addInt(res, ((NI) 1));
				res = (NI)(TM_puszxb5eHZKmsb5EP4KzKQ_10);
			} LA3: ;
		}
	}
	popFrame();
	return result;
}

N_NIMCALL(NF, length_e0H9aq8ETGjS9by7Evwdd3dA)(tyObject_Quat_yJAd1NQB8I67sGeTRIsbNw* q) {
	NF result;
	NF T1_;
	nimfr_("length", "quat.nim");
	result = (NF)0;
	nimln_(189, "quat.nim");
	T1_ = (NF)0;
	T1_ = length2_e0H9aq8ETGjS9by7Evwdd3dA_2(q);
	result = sqrt(T1_);
	popFrame();
	return result;
}

N_NIMCALL(tyObject_Quat_yJAd1NQB8I67sGeTRIsbNw, normalize_e2ZcyGv6dIwdw8RgF6Ck2g)(tyObject_Quat_yJAd1NQB8I67sGeTRIsbNw* q) {
	tyObject_Quat_yJAd1NQB8I67sGeTRIsbNw result;
	NF T1_;
	nimfr_("normalize", "quat.nim");
	memset((void*)(&result), 0, sizeof(result));
	nimln_(192, "quat.nim");
	T1_ = (NF)0;
	T1_ = length_e0H9aq8ETGjS9by7Evwdd3dA(q);
	result = star__XWgUovB1XZVq9curgVFw4Qg(q, ((NF)(1.0000000000000000e+00f) / (NF)(T1_)));
	popFrame();
	return result;
}

N_NIMCALL(tyObject_Quat_yJAd1NQB8I67sGeTRIsbNw, quat_jmZHZx59bLLTLSoCQp31v9bw)(tyObject_Vec_S5njPDIR1N39afJ9a6EQzdbA* u, tyObject_Vec_S5njPDIR1N39afJ9a6EQzdbA* v) {
	tyObject_Quat_yJAd1NQB8I67sGeTRIsbNw result;
	tyObject_Vec_S5njPDIR1N39afJ9a6EQzdbA LocalW;
	NF Dot;
	tyObject_Quat_yJAd1NQB8I67sGeTRIsbNw q;
	NF T1_;
	NF T2_;
	NF T3_;
	nimfr_("quat", "quat.nim");
	memset((void*)(&result), 0, sizeof(result));
	nimln_(326, "quat.nim");
	LocalW = cross_xqD7SU75nzFLAQWqOYjycQ(u, v);
	nimln_(327, "quat.nim");
	Dot = dot_IcSwLAapwm3k9a3IG4M9bUSQquat(u, v);
	nimln_(328, "quat.nim");
	T1_ = (NF)0;
	T1_ = x_NpfOyWKi6CLtEhMWqkmyuQvec((&LocalW));
	T2_ = (NF)0;
	T2_ = y_NpfOyWKi6CLtEhMWqkmyuQ_2vec((&LocalW));
	T3_ = (NF)0;
	T3_ = z_NpfOyWKi6CLtEhMWqkmyuQ_3vec((&LocalW));
	q = quat_0lqGzO7AmX7PhRWVxaVspQ_2quat(T1_, T2_, T3_, ((NF)(1.0000000000000000e+00) + (NF)(Dot)));
	nimln_(329, "quat.nim");
	result = normalize_e2ZcyGv6dIwdw8RgF6Ck2g((&q));
	popFrame();
	return result;
}

static N_INLINE(tyObject_Vec_S5njPDIR1N39afJ9a6EQzdbA, yzx_MSvCTTpbc9cWSB9cTnDV2tBAvec)(tyObject_Vec_S5njPDIR1N39afJ9a6EQzdbA* v) {
	tyObject_Vec_S5njPDIR1N39afJ9a6EQzdbA result;
	tyObject_Vec_S5njPDIR1N39afJ9a6EQzdbA T1_;
	nimfr_("yzx", "vec.nim");
	memset((void*)(&result), 0, sizeof(result));
	nimln_(216, "vec.nim");
	memset((void*)(&T1_), 0, sizeof(T1_));
	T1_.arr[0] = (*v).arr[(((NI) 1))- 0];
	T1_.arr[1] = (*v).arr[(((NI) 2))- 0];
	T1_.arr[2] = (*v).arr[(((NI) 0))- 0];
	result = T1_;
	popFrame();
	return result;
}

static N_INLINE(tyObject_Vec_S5njPDIR1N39afJ9a6EQzdbA, zxy_MSvCTTpbc9cWSB9cTnDV2tBA_2vec)(tyObject_Vec_S5njPDIR1N39afJ9a6EQzdbA* v) {
	tyObject_Vec_S5njPDIR1N39afJ9a6EQzdbA result;
	tyObject_Vec_S5njPDIR1N39afJ9a6EQzdbA T1_;
	nimfr_("zxy", "vec.nim");
	memset((void*)(&result), 0, sizeof(result));
	nimln_(216, "vec.nim");
	memset((void*)(&T1_), 0, sizeof(T1_));
	T1_.arr[0] = (*v).arr[(((NI) 2))- 0];
	T1_.arr[1] = (*v).arr[(((NI) 0))- 0];
	T1_.arr[2] = (*v).arr[(((NI) 1))- 0];
	result = T1_;
	popFrame();
	return result;
}

static N_INLINE(tyObject_Vec_S5njPDIR1N39afJ9a6EQzdbA, star__btEXTJnnMEuPmjWOn1TWIA_2vec)(tyObject_Vec_S5njPDIR1N39afJ9a6EQzdbA* v, tyObject_Vec_S5njPDIR1N39afJ9a6EQzdbA* u) {
	tyObject_Vec_S5njPDIR1N39afJ9a6EQzdbA result;
	nimfr_("*", "vec.nim");
	memset((void*)(&result), 0, sizeof(result));
	{
		NI ii;
		NI i;
		ii = (NI)0;
		nimln_(3847, "system.nim");
		i = ((NI) 0);
		{
			nimln_(3848, "system.nim");
			while (1) {
				NI TM_puszxb5eHZKmsb5EP4KzKQ_11;
				if (!(i < ((NI) 3))) goto LA3;
				nimln_(3849, "system.nim");
				ii = i;
				if ((NU)(ii) > (NU)(2)) raiseIndexError();
				nimln_(109, "vec.nim");
				if ((NU)(ii) > (NU)(2)) raiseIndexError();
				if ((NU)(ii) > (NU)(2)) raiseIndexError();
				result.arr[(ii)- 0] = ((NF)((*v).arr[(ii)- 0]) * (NF)((*u).arr[(ii)- 0]));
				nimln_(3850, "system.nim");
				TM_puszxb5eHZKmsb5EP4KzKQ_11 = addInt(i, ((NI) 1));
				i = (NI)(TM_puszxb5eHZKmsb5EP4KzKQ_11);
			} LA3: ;
		}
	}
	popFrame();
	return result;
}

static N_INLINE(tyObject_Vec_S5njPDIR1N39afJ9a6EQzdbA, minus__btEXTJnnMEuPmjWOn1TWIAvec)(tyObject_Vec_S5njPDIR1N39afJ9a6EQzdbA* v, tyObject_Vec_S5njPDIR1N39afJ9a6EQzdbA* u) {
	tyObject_Vec_S5njPDIR1N39afJ9a6EQzdbA result;
	nimfr_("-", "vec.nim");
	memset((void*)(&result), 0, sizeof(result));
	{
		NI ii;
		NI i;
		ii = (NI)0;
		nimln_(3847, "system.nim");
		i = ((NI) 0);
		{
			nimln_(3848, "system.nim");
			while (1) {
				NI TM_puszxb5eHZKmsb5EP4KzKQ_12;
				if (!(i < ((NI) 3))) goto LA3;
				nimln_(3849, "system.nim");
				ii = i;
				if ((NU)(ii) > (NU)(2)) raiseIndexError();
				nimln_(109, "vec.nim");
				if ((NU)(ii) > (NU)(2)) raiseIndexError();
				if ((NU)(ii) > (NU)(2)) raiseIndexError();
				result.arr[(ii)- 0] = ((NF)((*v).arr[(ii)- 0]) - (NF)((*u).arr[(ii)- 0]));
				nimln_(3850, "system.nim");
				TM_puszxb5eHZKmsb5EP4KzKQ_12 = addInt(i, ((NI) 1));
				i = (NI)(TM_puszxb5eHZKmsb5EP4KzKQ_12);
			} LA3: ;
		}
	}
	popFrame();
	return result;
}

N_NIMCALL(tyObject_Quat_yJAd1NQB8I67sGeTRIsbNw, quatd_0gnPEPPD5U13KUM09ao5wFA_2)(tyObject_Vec_S5njPDIR1N39afJ9a6EQzdbA* axis, NF angle) {
	tyObject_Quat_yJAd1NQB8I67sGeTRIsbNw result;
	nimfr_("quatd", "quat.nim");
	memset((void*)(&result), 0, sizeof(result));
	nimln_(342, "quat.nim");
	result = quat_0gnPEPPD5U13KUM09ao5wFA(axis, angle);
	popFrame();
	return result;
}

N_NIMCALL(tyObject_Quat_yJAd1NQB8I67sGeTRIsbNw, quatd_jmZHZx59bLLTLSoCQp31v9bw_2)(tyObject_Vec_S5njPDIR1N39afJ9a6EQzdbA* u, tyObject_Vec_S5njPDIR1N39afJ9a6EQzdbA* v) {
	tyObject_Quat_yJAd1NQB8I67sGeTRIsbNw result;
	nimfr_("quatd", "quat.nim");
	memset((void*)(&result), 0, sizeof(result));
	nimln_(343, "quat.nim");
	result = quat_jmZHZx59bLLTLSoCQp31v9bw(u, v);
	popFrame();
	return result;
}

N_NIMCALL(tyObject_Quat_yJAd1NQB8I67sGeTRIsbNw, quatd_sweJ0yMi9azrhhhxjXHoEUw)(tyObject_Mat_HtRb1O5aOVprrfb4PBLHfQ* mat) {
	tyObject_Quat_yJAd1NQB8I67sGeTRIsbNw result;
	nimfr_("quatd", "quat.nim");
	memset((void*)(&result), 0, sizeof(result));
	nimln_(344, "quat.nim");
	result = quat_9bg9b9a9bGItEerqpTBegmuR1w(mat);
	popFrame();
	return result;
}

N_NIMCALL(tyObject_Quat_yJAd1NQB8I67sGeTRIsbNw, quatd_xt2xY9c8l9akDPgVM2pv5aLw)(void) {
	tyObject_Quat_yJAd1NQB8I67sGeTRIsbNw result;
	tyObject_Quat_yJAd1NQB8I67sGeTRIsbNw T1_;
	nimfr_("quatd", "quat.nim");
	memset((void*)(&result), 0, sizeof(result));
	nimln_(345, "quat.nim");
	memset((void*)(&T1_), 0, sizeof(T1_));
	memcpy((void*)T1_.arr, (NIM_CONST void*)TM_puszxb5eHZKmsb5EP4KzKQ_13, sizeof(tyArray_jOGfJgrdxgfAJsLC7WNNEw));
	result = T1_;
	popFrame();
	return result;
}
NIM_EXTERNC N_NOINLINE(void, glm_quatInit000)(void) {
	nimfr_("quat", "quat.nim");
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, glm_quatDatInit000)(void) {
}

