/* Generated by Nim Compiler v0.17.2 */
/*   (c) 2017 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w  -I/home/vlad/Nim/lib -o /home/vlad/Sandbox/learnopengl/lighting/nimcache/x11_xutil.o /home/vlad/Sandbox/learnopengl/lighting/nimcache/x11_xutil.c */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 64

#include "nimbase.h"
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef powerpc
#undef unix
typedef struct TGenericSeq TGenericSeq;
typedef struct NimStringDesc NimStringDesc;
typedef struct tyObject_TXClassHint_NcAxSWMg1alKX2gGd3BoAA tyObject_TXClassHint_NcAxSWMg1alKX2gGd3BoAA;
typedef struct tyObject_TXIconSize_F3Me9c0P8GYk9cUOuLc9amqJQ tyObject_TXIconSize_F3Me9c0P8GYk9cUOuLc9amqJQ;
typedef struct tyObject_TXSizeHints_ZCZZOwbq6eefPoUNI8vGTQ tyObject_TXSizeHints_ZCZZOwbq6eefPoUNI8vGTQ;
typedef struct tyObject_TXStandardColormap_zAfXviCBWQ9cAeAzQ7THvUg tyObject_TXStandardColormap_zAfXviCBWQ9cAeAzQ7THvUg;
typedef struct tyObject_TXWMHints_lUa4DZQSJz1v9a01zIbsbJQ tyObject_TXWMHints_lUa4DZQSJz1v9a01zIbsbJQ;
typedef struct tyObject_TXRegion_RT9a0bSeCV49bxhFbk39ahF7A tyObject_TXRegion_RT9a0bSeCV49bxhFbk39ahF7A;
typedef struct tyObject_TXRectangle_S8vGECuhPC3amcQqvwAN9cw tyObject_TXRectangle_S8vGECuhPC3amcQqvwAN9cw;
typedef struct tyObject_TXDisplay_gMxDwwqjHjGHbrH7kUchGA tyObject_TXDisplay_gMxDwwqjHjGHbrH7kUchGA;
typedef struct tyObject_TXTextProperty_da1IvVEsacOzwgSbxX43oA tyObject_TXTextProperty_da1IvVEsacOzwgSbxX43oA;
typedef struct tyObject_TXVisualInfo_1VtEjmAVZ8Q9aLR0s41Pjnw tyObject_TXVisualInfo_1VtEjmAVZ8Q9aLR0s41Pjnw;
typedef struct tyObject_TXKeyEvent_YmaqpZgRYdl9cHeEfN7EtEw tyObject_TXKeyEvent_YmaqpZgRYdl9cHeEfN7EtEw;
typedef struct tyObject_TXComposeStatus_0fUfVKbE82y7yOb3PIxyXw tyObject_TXComposeStatus_0fUfVKbE82y7yOb3PIxyXw;
typedef struct tyObject_TXPoint_0BYJ9aU4Lm9biJ9ah9capUKHQA tyObject_TXPoint_0BYJ9aU4Lm9biJ9ah9capUKHQA;
typedef struct tyObject_TXGC_ETFLsgVh1BdkG6EX5H5zfA tyObject_TXGC_ETFLsgVh1BdkG6EX5H5zfA;
typedef struct tyObject_TXImage_e0S5K9cN9cczbNOLyWrYKsCQ tyObject_TXImage_e0S5K9cN9cczbNOLyWrYKsCQ;
typedef struct tyObject_TF_UE19anzg85i4kcN5z8YAH3w tyObject_TF_UE19anzg85i4kcN5z8YAH3w;
typedef struct tyObject_TVisual_sqcKqLNOQefL6fxiLETvYw tyObject_TVisual_sqcKqLNOQefL6fxiLETvYw;
typedef struct tyObject_TCPoint_KgVBUJcg9bt8nMEjZBpELgw tyObject_TCPoint_KgVBUJcg9bt8nMEjZBpELgw;
typedef struct tyObject_TXExtData_bmVh0W8jZ9c3HbsLjsgs28g tyObject_TXExtData_bmVh0W8jZ9c3HbsLjsgs28g;
struct TGenericSeq {
NI len;
NI reserved;
};
struct NimStringDesc {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef N_CDECL_PTR(tyObject_TXClassHint_NcAxSWMg1alKX2gGd3BoAA*, tyProc_zPzS57h6C05CT3LPxvk8VQ) (void);
typedef N_CDECL_PTR(tyObject_TXIconSize_F3Me9c0P8GYk9cUOuLc9amqJQ*, tyProc_pJCpoi4xciXO6FUOEleglA) (void);
typedef N_CDECL_PTR(tyObject_TXSizeHints_ZCZZOwbq6eefPoUNI8vGTQ*, tyProc_7zYEZ6TVffoUgPh9cS1FVvQ) (void);
typedef N_CDECL_PTR(tyObject_TXStandardColormap_zAfXviCBWQ9cAeAzQ7THvUg*, tyProc_RWaKkowz8mBzKnCrdrwjUg) (void);
typedef N_CDECL_PTR(tyObject_TXWMHints_lUa4DZQSJz1v9a01zIbsbJQ*, tyProc_L1zdNDE1z1SfZRa1ZUswQQ) (void);
typedef N_CDECL_PTR(int, tyProc_kxUovtzjOWnOB9bjPGH8jPw) (tyObject_TXRegion_RT9a0bSeCV49bxhFbk39ahF7A* para1, tyObject_TXRectangle_S8vGECuhPC3amcQqvwAN9cw* para2);
typedef N_CDECL_PTR(tyObject_TXRegion_RT9a0bSeCV49bxhFbk39ahF7A*, tyProc_18cSxVS2RbnYA9aP5LAiXTA) (void);
typedef N_CDECL_PTR(NCSTRING, tyProc_09bvyvHFtWbkzL5AHgf0bKw) (void);
typedef N_CDECL_PTR(int, tyProc_uF7GbVXhvDog9c9bqqyS81Ig) (tyObject_TXDisplay_gMxDwwqjHjGHbrH7kUchGA* para1, unsigned long para2, int para3);
typedef N_CDECL_PTR(int, tyProc_kD3MN9b4eKAFWThEkkqC1qQ) (tyObject_TXRegion_RT9a0bSeCV49bxhFbk39ahF7A* para1);
typedef N_CDECL_PTR(int, tyProc_iIDrWqptIMblKaHgMXxmFA) (tyObject_TXRegion_RT9a0bSeCV49bxhFbk39ahF7A* para1, tyObject_TXRegion_RT9a0bSeCV49bxhFbk39ahF7A* para2);
typedef N_CDECL_PTR(int, tyProc_MvXaxx9af9aes7JMcvxfXcwQ) (tyObject_TXDisplay_gMxDwwqjHjGHbrH7kUchGA* para1, unsigned long para2, int para3, NIM_CHAR** para4);
typedef N_CDECL_PTR(int, tyProc_xfGEjrfsPPQqFjsbgDCjrg) (tyObject_TXDisplay_gMxDwwqjHjGHbrH7kUchGA* para1, unsigned long para2, tyObject_TXClassHint_NcAxSWMg1alKX2gGd3BoAA* para3);
typedef N_CDECL_PTR(int, tyProc_hXHLHBkPLRusiPSv9cRq5tQ) (tyObject_TXDisplay_gMxDwwqjHjGHbrH7kUchGA* para1, unsigned long para2, tyObject_TXIconSize_F3Me9c0P8GYk9cUOuLc9amqJQ** para3, int* para4);
typedef N_CDECL_PTR(int, tyProc_9aWivT6Edf8PyRV3NvT2h7A) (tyObject_TXDisplay_gMxDwwqjHjGHbrH7kUchGA* para1, unsigned long para2, tyObject_TXSizeHints_ZCZZOwbq6eefPoUNI8vGTQ* para3);
typedef N_CDECL_PTR(int, tyProc_aE1CTOki9aJy3wlSnUOsIAw) (tyObject_TXDisplay_gMxDwwqjHjGHbrH7kUchGA* para1, unsigned long para2, tyObject_TXStandardColormap_zAfXviCBWQ9cAeAzQ7THvUg** para3, int* para4, unsigned long para5);
typedef N_CDECL_PTR(int, tyProc_IR12rrjzxXqgWXmxKVeikQ) (tyObject_TXDisplay_gMxDwwqjHjGHbrH7kUchGA* para1, unsigned long para2, tyObject_TXSizeHints_ZCZZOwbq6eefPoUNI8vGTQ* para3, unsigned long para4);
typedef N_CDECL_PTR(int, tyProc_WWiO8ZQc2dKjnHaEHe1S3g) (tyObject_TXDisplay_gMxDwwqjHjGHbrH7kUchGA* para1, unsigned long para2, tyObject_TXStandardColormap_zAfXviCBWQ9cAeAzQ7THvUg* para3, unsigned long para4);
typedef N_CDECL_PTR(int, tyProc_uy1vOa8ZTciMPQucUf1dRw) (tyObject_TXDisplay_gMxDwwqjHjGHbrH7kUchGA* para1, unsigned long para2, tyObject_TXTextProperty_da1IvVEsacOzwgSbxX43oA* para3, unsigned long para4);
typedef N_CDECL_PTR(tyObject_TXVisualInfo_1VtEjmAVZ8Q9aLR0s41Pjnw*, tyProc_1EP29cbWh0jd4WO3c9cYpPlg) (tyObject_TXDisplay_gMxDwwqjHjGHbrH7kUchGA* para1, long para2, tyObject_TXVisualInfo_1VtEjmAVZ8Q9aLR0s41Pjnw* para3, int* para4);
typedef N_CDECL_PTR(int, tyProc_t0ariGsj6KPo59bWvCmGpPA) (tyObject_TXDisplay_gMxDwwqjHjGHbrH7kUchGA* para1, unsigned long para2, tyObject_TXTextProperty_da1IvVEsacOzwgSbxX43oA* para3);
typedef N_CDECL_PTR(tyObject_TXWMHints_lUa4DZQSJz1v9a01zIbsbJQ*, tyProc_JJYIMEzhjdI79cJbNQfZydg) (tyObject_TXDisplay_gMxDwwqjHjGHbrH7kUchGA* para1, unsigned long para2);
typedef N_CDECL_PTR(int, tyProc_gjSQ7qB9b8sOx14Hf3QZUdg) (tyObject_TXDisplay_gMxDwwqjHjGHbrH7kUchGA* para1, unsigned long para2, tyObject_TXSizeHints_ZCZZOwbq6eefPoUNI8vGTQ* para3, NI* para4);
typedef N_CDECL_PTR(int, tyProc_OA9c9b5DYNlsm03Et2i9c2PiQ) (tyObject_TXDisplay_gMxDwwqjHjGHbrH7kUchGA* para1, unsigned long para2, tyObject_TXSizeHints_ZCZZOwbq6eefPoUNI8vGTQ* para3, NI* para4, unsigned long para5);
typedef N_CDECL_PTR(int, tyProc_De4LPoObmzbYuD1tbqZK3g) (tyObject_TXRegion_RT9a0bSeCV49bxhFbk39ahF7A* para1, tyObject_TXRegion_RT9a0bSeCV49bxhFbk39ahF7A* para2, tyObject_TXRegion_RT9a0bSeCV49bxhFbk39ahF7A* para3);
typedef N_CDECL_PTR(void, tyProc_CuIjqy8B9cY8wP5e6RwMulQ) (unsigned long para1, unsigned long* para2, unsigned long* para3);
typedef N_CDECL_PTR(int, tyProc_RAYLa1dnoEEzrJRfMgh5Kg) (tyObject_TXKeyEvent_YmaqpZgRYdl9cHeEfN7EtEw* para1, NCSTRING para2, int para3, unsigned long* para4, tyObject_TXComposeStatus_0fUfVKbE82y7yOb3PIxyXw* para5);
typedef N_CDECL_PTR(int, tyProc_rdWhMebssS7tE3LFN1FJJw) (tyObject_TXDisplay_gMxDwwqjHjGHbrH7kUchGA* para1, int para2, int para3, int para4, tyObject_TXVisualInfo_1VtEjmAVZ8Q9aLR0s41Pjnw* para5);
typedef N_CDECL_PTR(int, tyProc_CPOUL7sfsUggPfYMUN6l9aA) (tyObject_TXRegion_RT9a0bSeCV49bxhFbk39ahF7A* para1, int para2, int para3);
typedef N_CDECL_PTR(NI, tyProc_FodgJ0LEUemXg9bKFCuYBEA) (tyObject_TXRegion_RT9a0bSeCV49bxhFbk39ahF7A* para1, int para2, int para3);
typedef N_CDECL_PTR(tyObject_TXRegion_RT9a0bSeCV49bxhFbk39ahF7A*, tyProc_brF9cwu3OgcV0hrOykgubgg) (tyObject_TXPoint_0BYJ9aU4Lm9biJ9ah9capUKHQA* para1, int para2, int para3);
typedef N_CDECL_PTR(int, tyProc_cZEY9cicFK2coDAS8XZOtKw) (tyObject_TXRegion_RT9a0bSeCV49bxhFbk39ahF7A* para1, int para2, int para3, unsigned int para4, unsigned int para5);
typedef N_CDECL_PTR(int, tyProc_0ysgWDKm2NQM0u9bCv9bxQXQ) (tyObject_TXDisplay_gMxDwwqjHjGHbrH7kUchGA* para1, unsigned long para2, int para3, NCSTRING para4);
typedef N_CDECL_PTR(int, tyProc_TkM0ne8UilJKwRLed52cMA) (tyObject_TXDisplay_gMxDwwqjHjGHbrH7kUchGA* para1, unsigned long para2, tyObject_TXClassHint_NcAxSWMg1alKX2gGd3BoAA* para3);
typedef N_CDECL_PTR(int, tyProc_1JuAutjX49a3f4OAhFCWQ9cg) (tyObject_TXDisplay_gMxDwwqjHjGHbrH7kUchGA* para1, unsigned long para2, tyObject_TXIconSize_F3Me9c0P8GYk9cUOuLc9amqJQ* para3, int para4);
typedef N_CDECL_PTR(int, tyProc_tQBdXnFpE3bhq80ssEfI9bA) (tyObject_TXDisplay_gMxDwwqjHjGHbrH7kUchGA* para1, unsigned long para2, tyObject_TXSizeHints_ZCZZOwbq6eefPoUNI8vGTQ* para3);
typedef N_CDECL_PTR(void, tyProc_r6lA9c8FtuWj3a9bl6Jd2QBA) (tyObject_TXDisplay_gMxDwwqjHjGHbrH7kUchGA* para1, unsigned long para2, tyObject_TXStandardColormap_zAfXviCBWQ9cAeAzQ7THvUg* para3, int para4, unsigned long para5);
typedef N_CDECL_PTR(int, tyProc_ZfrFP9amdyPLHtIcgrvP2uQ) (tyObject_TXDisplay_gMxDwwqjHjGHbrH7kUchGA* para1, unsigned long para2, tyObject_TXSizeHints_ZCZZOwbq6eefPoUNI8vGTQ* para3, unsigned long para4);
typedef N_CDECL_PTR(int, tyProc_xNsRqAHBsNean7PbtB9aSNA) (tyObject_TXDisplay_gMxDwwqjHjGHbrH7kUchGA* para1, unsigned long para2, NCSTRING para3, NCSTRING para4, unsigned long para5, NCSTRING* para6, int para7, tyObject_TXSizeHints_ZCZZOwbq6eefPoUNI8vGTQ* para8);
typedef N_CDECL_PTR(void, tyProc_VK0lxcwnR9amQgo06oJw0kA) (tyObject_TXDisplay_gMxDwwqjHjGHbrH7kUchGA* para1, unsigned long para2, tyObject_TXTextProperty_da1IvVEsacOzwgSbxX43oA* para3, unsigned long para4);
typedef N_CDECL_PTR(void, tyProc_Zf9cgsdUeEnzsbxSvwv1gQA) (tyObject_TXDisplay_gMxDwwqjHjGHbrH7kUchGA* para1, unsigned long para2, tyObject_TXTextProperty_da1IvVEsacOzwgSbxX43oA* para3);
typedef N_CDECL_PTR(int, tyProc_gvy64YosY7QevxBqsy7RCQ) (tyObject_TXDisplay_gMxDwwqjHjGHbrH7kUchGA* para1, unsigned long para2, tyObject_TXWMHints_lUa4DZQSJz1v9a01zIbsbJQ* para3);
typedef N_CDECL_PTR(void, tyProc_8dH9ahTZgn89awr7UTJG9aYhQ) (tyObject_TXDisplay_gMxDwwqjHjGHbrH7kUchGA* para1, unsigned long para2, tyObject_TXSizeHints_ZCZZOwbq6eefPoUNI8vGTQ* para3);
typedef N_CDECL_PTR(void, tyProc_JslQe9cADo8jGQWrC6S19bag) (tyObject_TXDisplay_gMxDwwqjHjGHbrH7kUchGA* para1, unsigned long para2, tyObject_TXTextProperty_da1IvVEsacOzwgSbxX43oA* para3, tyObject_TXTextProperty_da1IvVEsacOzwgSbxX43oA* para4, NCSTRING* para5, int para6, tyObject_TXSizeHints_ZCZZOwbq6eefPoUNI8vGTQ* para7, tyObject_TXWMHints_lUa4DZQSJz1v9a01zIbsbJQ* para8, tyObject_TXClassHint_NcAxSWMg1alKX2gGd3BoAA* para9);
typedef N_CDECL_PTR(void, tyProc_tWlQKgtpZdVozp3cnGqYCw) (tyObject_TXDisplay_gMxDwwqjHjGHbrH7kUchGA* para1, unsigned long para2, NCSTRING para3, NCSTRING para4, NCSTRING* para5, int para6, tyObject_TXSizeHints_ZCZZOwbq6eefPoUNI8vGTQ* para7, tyObject_TXWMHints_lUa4DZQSJz1v9a01zIbsbJQ* para8, tyObject_TXClassHint_NcAxSWMg1alKX2gGd3BoAA* para9);
typedef N_CDECL_PTR(void, tyProc_M09bQyDal8ZRgJ874GtLhLg) (tyObject_TXDisplay_gMxDwwqjHjGHbrH7kUchGA* para1, unsigned long para2, tyObject_TXSizeHints_ZCZZOwbq6eefPoUNI8vGTQ* para3, unsigned long para4);
typedef N_CDECL_PTR(int, tyProc_E5XSzdTsseY9bfH771Rthxg) (tyObject_TXDisplay_gMxDwwqjHjGHbrH7kUchGA* para1, tyObject_TXGC_ETFLsgVh1BdkG6EX5H5zfA* para2, tyObject_TXRegion_RT9a0bSeCV49bxhFbk39ahF7A* para3);
typedef N_CDECL_PTR(void, tyProc_mueeJxz6EWk04dsLmuQ6Ew) (tyObject_TXDisplay_gMxDwwqjHjGHbrH7kUchGA* para1, unsigned long para2, tyObject_TXStandardColormap_zAfXviCBWQ9cAeAzQ7THvUg* para3, unsigned long para4);
typedef N_CDECL_PTR(int, tyProc_QtKMkiuvFVJA9aoJrOG2A9bA) (NCSTRING* para1, int para2, tyObject_TXTextProperty_da1IvVEsacOzwgSbxX43oA* para3);
typedef NU8 tyEnum_TXICCEncodingStyle_6BS76AsFGarSe9aoBphsi2w;
typedef N_CDECL_PTR(int, tyProc_8lLJp9aaRyUq19a1RKOM5GbQ) (tyObject_TXDisplay_gMxDwwqjHjGHbrH7kUchGA* para1, NCSTRING* para2, int para3, tyEnum_TXICCEncodingStyle_6BS76AsFGarSe9aoBphsi2w para4, tyObject_TXTextProperty_da1IvVEsacOzwgSbxX43oA* para5);
typedef N_CDECL_PTR(int, tyProc_lW3r9c2gB6QRGf5BIA8ntdg) (tyObject_TXDisplay_gMxDwwqjHjGHbrH7kUchGA* para1, NI16** para2, int para3, tyEnum_TXICCEncodingStyle_6BS76AsFGarSe9aoBphsi2w para4, tyObject_TXTextProperty_da1IvVEsacOzwgSbxX43oA* para5);
typedef N_CDECL_PTR(void, tyProc_Y8u4eB4zmFgeOnSJfKgaUQ) (NI16** para1);
typedef N_CDECL_PTR(int, tyProc_ydSLfh3PyA4Pb0859bTyDLw) (tyObject_TXTextProperty_da1IvVEsacOzwgSbxX43oA* para1, NCSTRING** para2, int* para3);
typedef N_CDECL_PTR(int, tyProc_o6Ya9cfTymcwdTOpf5QrQ8A) (tyObject_TXDisplay_gMxDwwqjHjGHbrH7kUchGA* para1, tyObject_TXTextProperty_da1IvVEsacOzwgSbxX43oA* para2, NCSTRING** para3, int* para4);
typedef N_CDECL_PTR(int, tyProc_0PYOSmE79bK9b9c0jmrHKXR9bQ) (tyObject_TXDisplay_gMxDwwqjHjGHbrH7kUchGA* para1, tyObject_TXTextProperty_da1IvVEsacOzwgSbxX43oA* para2, NI16*** para3, int* para4);
typedef N_CDECL_PTR(int, tyProc_ilxbT6WFqGS7tU2VAZ9cEZg) (tyObject_TXRectangle_S8vGECuhPC3amcQqvwAN9cw* para1, tyObject_TXRegion_RT9a0bSeCV49bxhFbk39ahF7A* para2, tyObject_TXRegion_RT9a0bSeCV49bxhFbk39ahF7A* para3);
typedef N_CDECL_PTR(int, tyProc_iR6R09all3Jek9bL9c6frTEkA) (tyObject_TXDisplay_gMxDwwqjHjGHbrH7kUchGA* para1, int para2, NCSTRING para3, NCSTRING para4, unsigned int para5, tyObject_TXSizeHints_ZCZZOwbq6eefPoUNI8vGTQ* para6, int* para7, int* para8, int* para9, int* para10, int* para11);
typedef N_CDECL_PTR(tyObject_TXImage_e0S5K9cN9cczbNOLyWrYKsCQ*, tyProc_aUq6i6REPBuUaZLVB75EEA) (tyObject_TXDisplay_gMxDwwqjHjGHbrH7kUchGA* para1, tyObject_TVisual_sqcKqLNOQefL6fxiLETvYw* para2, unsigned int para3, int para4, int para5, NCSTRING para6, unsigned int para7, unsigned int para8, int para9, int para10);
typedef N_CDECL_PTR(int, tyProc_5e3MrwvuEVXmu69cIETQoWA) (tyObject_TXImage_e0S5K9cN9cczbNOLyWrYKsCQ* para1);
typedef N_CDECL_PTR(unsigned long, tyProc_UaF5PEQuIRE9aiUPKYBTmuw) (tyObject_TXImage_e0S5K9cN9cczbNOLyWrYKsCQ* para1, int para2, int para3);
typedef N_CDECL_PTR(int, tyProc_pn5eY0sp29bf8ombZ7R9c45g) (tyObject_TXImage_e0S5K9cN9cczbNOLyWrYKsCQ* para1, int para2, int para3, unsigned long para4);
typedef N_CDECL_PTR(tyObject_TXImage_e0S5K9cN9cczbNOLyWrYKsCQ*, tyProc_fhzx9b9cH9a259aAHjIP0M0EEA) (tyObject_TXImage_e0S5K9cN9cczbNOLyWrYKsCQ* para1, int para2, int para3, unsigned int para4, unsigned int para5);
typedef N_CDECL_PTR(int, tyProc_18MISVuJYuuTT3IhkNQdQg) (tyObject_TXImage_e0S5K9cN9cczbNOLyWrYKsCQ* para1, long para2);
struct tyObject_TF_UE19anzg85i4kcN5z8YAH3w {
tyProc_aUq6i6REPBuUaZLVB75EEA create_image;
tyProc_5e3MrwvuEVXmu69cIETQoWA destroy_image;
tyProc_UaF5PEQuIRE9aiUPKYBTmuw get_pixel;
tyProc_pn5eY0sp29bf8ombZ7R9c45g put_pixel;
tyProc_fhzx9b9cH9a259aAHjIP0M0EEA sub_image;
tyProc_18MISVuJYuuTT3IhkNQdQg add_pixel;
};
struct tyObject_TXImage_e0S5K9cN9cczbNOLyWrYKsCQ {
int width;
int height;
int xoffset;
int format;
NCSTRING data;
int byte_order;
int bitmap_unit;
int bitmap_bit_order;
int bitmap_pad;
int depth;
int bytes_per_line;
int bits_per_pixel;
unsigned long red_mask;
unsigned long green_mask;
unsigned long blue_mask;
NIM_CHAR* obdata;
tyObject_TF_UE19anzg85i4kcN5z8YAH3w f;
};
struct tyObject_TXClassHint_NcAxSWMg1alKX2gGd3BoAA {
NCSTRING res_name;
NCSTRING res_class;
};
struct tyObject_TXIconSize_F3Me9c0P8GYk9cUOuLc9amqJQ {
int min_width;
int min_height;
int max_width;
int max_height;
int width_inc;
int height_inc;
};
struct tyObject_TCPoint_KgVBUJcg9bt8nMEjZBpELgw {
int x;
int y;
};
struct tyObject_TXSizeHints_ZCZZOwbq6eefPoUNI8vGTQ {
long flags;
int x;
int y;
int width;
int height;
int min_width;
int min_height;
int max_width;
int max_height;
int width_inc;
int height_inc;
tyObject_TCPoint_KgVBUJcg9bt8nMEjZBpELgw min_aspect;
tyObject_TCPoint_KgVBUJcg9bt8nMEjZBpELgw max_aspect;
int base_width;
int base_height;
int win_gravity;
};
struct tyObject_TXStandardColormap_zAfXviCBWQ9cAeAzQ7THvUg {
unsigned long colormap;
unsigned long red_max;
unsigned long red_mult;
unsigned long green_max;
unsigned long green_mult;
unsigned long blue_max;
unsigned long blue_mult;
unsigned long base_pixel;
unsigned long visualid;
unsigned long killid;
};
struct tyObject_TXWMHints_lUa4DZQSJz1v9a01zIbsbJQ {
long flags;
NI input;
int initial_state;
unsigned long icon_pixmap;
unsigned long icon_window;
int icon_x;
int icon_y;
unsigned long icon_mask;
unsigned long window_group;
};
struct tyObject_TXRegion_RT9a0bSeCV49bxhFbk39ahF7A {
char dummy;
};
struct tyObject_TXRectangle_S8vGECuhPC3amcQqvwAN9cw {
short x;
short y;
unsigned short width;
unsigned short height;
};
struct tyObject_TXDisplay_gMxDwwqjHjGHbrH7kUchGA {
char dummy;
};
struct tyObject_TXTextProperty_da1IvVEsacOzwgSbxX43oA {
NCSTRING value;
unsigned long encoding;
int format;
unsigned long nitems;
};
struct tyObject_TXVisualInfo_1VtEjmAVZ8Q9aLR0s41Pjnw {
tyObject_TVisual_sqcKqLNOQefL6fxiLETvYw* visual;
unsigned long visualid;
int screen;
int depth;
int class_0;
unsigned long red_mask;
unsigned long green_mask;
unsigned long blue_mask;
int colormap_size;
int bits_per_rgb;
};
struct tyObject_TXKeyEvent_YmaqpZgRYdl9cHeEfN7EtEw {
int theType;
unsigned long serial;
NI send_event;
tyObject_TXDisplay_gMxDwwqjHjGHbrH7kUchGA* display;
unsigned long window;
unsigned long root;
unsigned long subwindow;
unsigned long time;
int x;
int y;
int x_root;
int y_root;
unsigned int state;
unsigned int keycode;
NI same_screen;
};
struct tyObject_TXComposeStatus_0fUfVKbE82y7yOb3PIxyXw {
NIM_CHAR* compose_ptr;
int chars_matched;
};
struct tyObject_TXPoint_0BYJ9aU4Lm9biJ9ah9capUKHQA {
short x;
short y;
};
struct tyObject_TXGC_ETFLsgVh1BdkG6EX5H5zfA {
char dummy;
};
struct tyObject_TVisual_sqcKqLNOQefL6fxiLETvYw {
tyObject_TXExtData_bmVh0W8jZ9c3HbsLjsgs28g* ext_data;
unsigned long visualid;
int c_class;
unsigned long red_mask;
unsigned long green_mask;
unsigned long blue_mask;
int bits_per_rgb;
int map_entries;
};
typedef N_CDECL_PTR(int, tyProc_PmEMm3nFNXrCrvxl43MgjQ) (tyObject_TXExtData_bmVh0W8jZ9c3HbsLjsgs28g* extension);
struct tyObject_TXExtData_bmVh0W8jZ9c3HbsLjsgs28g {
int number;
tyObject_TXExtData_bmVh0W8jZ9c3HbsLjsgs28g* next;
tyProc_PmEMm3nFNXrCrvxl43MgjQ free_private;
NIM_CHAR* private_data;
};
N_NIMCALL(void*, nimLoadLibrary)(NimStringDesc* path);
N_NOINLINE(void, nimLoadLibraryError)(NimStringDesc* path);
N_NIMCALL(void*, nimGetProcAddr)(void* lib, NCSTRING name);
N_NIMCALL(int, XDestroyImage_NM50hfux1tieXN5o9a840Sg)(tyObject_TXImage_e0S5K9cN9cczbNOLyWrYKsCQ* ximage);
static N_INLINE(void, nimFrame)(TFrame* s);
N_NOINLINE(void, stackOverflow_II46IjNZztN9bmbxUD8dt8g)(void);
static N_INLINE(void, popFrame)(void);
N_NIMCALL(unsigned long, XGetPixel_9b9cXTZxBLzuPURl2Tl3w3CQ)(tyObject_TXImage_e0S5K9cN9cczbNOLyWrYKsCQ* ximage, int x, int y);
N_NIMCALL(int, XPutPixel_5VE1n1GgDfCH7t8YgN59a6A)(tyObject_TXImage_e0S5K9cN9cczbNOLyWrYKsCQ* ximage, int x, int y, unsigned long pixel);
N_NIMCALL(tyObject_TXImage_e0S5K9cN9cczbNOLyWrYKsCQ*, XSubImage_tmmybLAOs0Xn19cM4S9azznA)(tyObject_TXImage_e0S5K9cN9cczbNOLyWrYKsCQ* ximage, int x, int y, unsigned int width, unsigned int height);
N_NIMCALL(int, XAddPixel_xZcCg9cb9ax8Ue42WPcejruw)(tyObject_TXImage_e0S5K9cN9cczbNOLyWrYKsCQ* ximage, long value);
N_NIMCALL(NIM_BOOL, IsKeypadKey_MvA8ZnvyMLj9a4BZHcY9bBhg)(unsigned long keysym);
N_NIMCALL(NIM_BOOL, IsPrivateKeypadKey_MvA8ZnvyMLj9a4BZHcY9bBhg_2)(unsigned long keysym);
N_NIMCALL(NIM_BOOL, IsCursorKey_MvA8ZnvyMLj9a4BZHcY9bBhg_3)(unsigned long keysym);
N_NIMCALL(NIM_BOOL, IsPFKey_MvA8ZnvyMLj9a4BZHcY9bBhg_4)(unsigned long keysym);
N_NIMCALL(NIM_BOOL, IsFunctionKey_MvA8ZnvyMLj9a4BZHcY9bBhg_5)(unsigned long keysym);
N_NIMCALL(NIM_BOOL, IsMiscFunctionKey_MvA8ZnvyMLj9a4BZHcY9bBhg_6)(unsigned long keysym);
N_NIMCALL(NIM_BOOL, IsModifierKey_MvA8ZnvyMLj9a4BZHcY9bBhg_7)(unsigned long keysym);
N_NIMCALL(NIM_BOOL, eqeq__fGnaGOqLnoCI1mmdaRD0qw)(unsigned long a, unsigned long b);
static void* TM_QOPO9bL7lOHTZ2zQmB9csB9cw_2;
tyProc_zPzS57h6C05CT3LPxvk8VQ Dl_253349_;
tyProc_pJCpoi4xciXO6FUOEleglA Dl_253351_;
tyProc_7zYEZ6TVffoUgPh9cS1FVvQ Dl_253353_;
tyProc_RWaKkowz8mBzKnCrdrwjUg Dl_253355_;
tyProc_L1zdNDE1z1SfZRa1ZUswQQ Dl_253357_;
tyProc_kxUovtzjOWnOB9bjPGH8jPw Dl_253359_;
tyProc_18cSxVS2RbnYA9aP5LAiXTA Dl_253363_;
tyProc_09bvyvHFtWbkzL5AHgf0bKw Dl_253365_;
tyProc_uF7GbVXhvDog9c9bqqyS81Ig Dl_253367_;
tyProc_kD3MN9b4eKAFWThEkkqC1qQ Dl_253372_;
tyProc_kD3MN9b4eKAFWThEkkqC1qQ Dl_253375_;
tyProc_iIDrWqptIMblKaHgMXxmFA Dl_253378_;
tyProc_MvXaxx9af9aes7JMcvxfXcwQ Dl_253382_;
tyProc_xfGEjrfsPPQqFjsbgDCjrg Dl_253388_;
tyProc_hXHLHBkPLRusiPSv9cRq5tQ Dl_253393_;
tyProc_9aWivT6Edf8PyRV3NvT2h7A Dl_253399_;
tyProc_aE1CTOki9aJy3wlSnUOsIAw Dl_253404_;
tyProc_IR12rrjzxXqgWXmxKVeikQ Dl_253411_;
tyProc_WWiO8ZQc2dKjnHaEHe1S3g Dl_253417_;
tyProc_uy1vOa8ZTciMPQucUf1dRw Dl_253423_;
tyProc_1EP29cbWh0jd4WO3c9cYpPlg Dl_253429_;
tyProc_t0ariGsj6KPo59bWvCmGpPA Dl_253435_;
tyProc_JJYIMEzhjdI79cJbNQfZydg Dl_253440_;
tyProc_t0ariGsj6KPo59bWvCmGpPA Dl_253444_;
tyProc_t0ariGsj6KPo59bWvCmGpPA Dl_253449_;
tyProc_gjSQ7qB9b8sOx14Hf3QZUdg Dl_253454_;
tyProc_OA9c9b5DYNlsm03Et2i9c2PiQ Dl_253461_;
tyProc_9aWivT6Edf8PyRV3NvT2h7A Dl_253469_;
tyProc_De4LPoObmzbYuD1tbqZK3g Dl_253474_;
tyProc_CuIjqy8B9cY8wP5e6RwMulQ Dl_253479_;
tyProc_RAYLa1dnoEEzrJRfMgh5Kg Dl_253484_;
tyProc_rdWhMebssS7tE3LFN1FJJw Dl_253491_;
tyProc_CPOUL7sfsUggPfYMUN6l9aA Dl_253498_;
tyProc_FodgJ0LEUemXg9bKFCuYBEA Dl_253503_;
tyProc_brF9cwu3OgcV0hrOykgubgg Dl_253508_;
tyProc_cZEY9cicFK2coDAS8XZOtKw Dl_253513_;
tyProc_0ysgWDKm2NQM0u9bCv9bxQXQ Dl_253520_;
tyProc_TkM0ne8UilJKwRLed52cMA Dl_253526_;
tyProc_1JuAutjX49a3f4OAhFCWQ9cg Dl_253531_;
tyProc_tQBdXnFpE3bhq80ssEfI9bA Dl_253537_;
tyProc_r6lA9c8FtuWj3a9bl6Jd2QBA Dl_253542_;
tyProc_ZfrFP9amdyPLHtIcgrvP2uQ Dl_253549_;
tyProc_xNsRqAHBsNean7PbtB9aSNA Dl_253555_;
tyProc_VK0lxcwnR9amQgo06oJw0kA Dl_253565_;
tyProc_Zf9cgsdUeEnzsbxSvwv1gQA Dl_253571_;
tyProc_gvy64YosY7QevxBqsy7RCQ Dl_253576_;
tyProc_Zf9cgsdUeEnzsbxSvwv1gQA Dl_253581_;
tyProc_Zf9cgsdUeEnzsbxSvwv1gQA Dl_253586_;
tyProc_8dH9ahTZgn89awr7UTJG9aYhQ Dl_253591_;
tyProc_JslQe9cADo8jGQWrC6S19bag Dl_253596_;
tyProc_tWlQKgtpZdVozp3cnGqYCw Dl_253607_;
tyProc_tWlQKgtpZdVozp3cnGqYCw Dl_253618_;
tyProc_M09bQyDal8ZRgJ874GtLhLg Dl_253629_;
tyProc_E5XSzdTsseY9bfH771Rthxg Dl_253635_;
tyProc_mueeJxz6EWk04dsLmuQ6Ew Dl_253640_;
tyProc_tQBdXnFpE3bhq80ssEfI9bA Dl_253646_;
tyProc_CPOUL7sfsUggPfYMUN6l9aA Dl_253651_;
tyProc_QtKMkiuvFVJA9aoJrOG2A9bA Dl_253656_;
tyProc_De4LPoObmzbYuD1tbqZK3g Dl_253661_;
tyProc_8lLJp9aaRyUq19a1RKOM5GbQ Dl_253666_;
tyProc_lW3r9c2gB6QRGf5BIA8ntdg Dl_253673_;
tyProc_8lLJp9aaRyUq19a1RKOM5GbQ Dl_253682_;
tyProc_Y8u4eB4zmFgeOnSJfKgaUQ Dl_253689_;
tyProc_ydSLfh3PyA4Pb0859bTyDLw Dl_253694_;
tyProc_o6Ya9cfTymcwdTOpf5QrQ8A Dl_253699_;
tyProc_0PYOSmE79bK9b9c0jmrHKXR9bQ Dl_253705_;
tyProc_o6Ya9cfTymcwdTOpf5QrQ8A Dl_253714_;
tyProc_ilxbT6WFqGS7tU2VAZ9cEZg Dl_253720_;
tyProc_De4LPoObmzbYuD1tbqZK3g Dl_253725_;
tyProc_iR6R09all3Jek9bL9c6frTEkA Dl_253730_;
tyProc_De4LPoObmzbYuD1tbqZK3g Dl_253743_;
extern TFrame* framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
STRING_LITERAL(TM_QOPO9bL7lOHTZ2zQmB9csB9cw_4, "libX11.so", 9);
STRING_LITERAL(TM_QOPO9bL7lOHTZ2zQmB9csB9cw_6, "libX11.so.6", 11);
STRING_LITERAL(TM_QOPO9bL7lOHTZ2zQmB9csB9cw_7, "libX11.so(|.6)", 14);

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI T1_;
	T1_ = (NI)0;
	{
		if (!(framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw == NIM_NIL)) goto LA4_;
		T1_ = ((NI) 0);
	}
	goto LA2_;
	LA4_: ;
	{
		T1_ = ((NI) ((NI16)((*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).calldepth + ((NI16) 1))));
	}
	LA2_: ;
	(*s).calldepth = ((NI16) (T1_));
	(*s).prev = framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9_;
		stackOverflow_II46IjNZztN9bmbxUD8dt8g();
	}
	LA9_: ;
}

static N_INLINE(void, popFrame)(void) {
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = (*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).prev;
}

N_NIMCALL(int, XDestroyImage_NM50hfux1tieXN5o9a840Sg)(tyObject_TXImage_e0S5K9cN9cczbNOLyWrYKsCQ* ximage) {
	int result;
	nimfr_("XDestroyImage", "xutil.nim");
	result = (int)0;
	nimln_(378, "xutil.nim");
	result = (*ximage).f.destroy_image(ximage);
	popFrame();
	return result;
}

N_NIMCALL(unsigned long, XGetPixel_9b9cXTZxBLzuPURl2Tl3w3CQ)(tyObject_TXImage_e0S5K9cN9cczbNOLyWrYKsCQ* ximage, int x, int y) {
	unsigned long result;
	nimfr_("XGetPixel", "xutil.nim");
	result = (unsigned long)0;
	nimln_(381, "xutil.nim");
	result = (*ximage).f.get_pixel(ximage, x, y);
	popFrame();
	return result;
}

N_NIMCALL(int, XPutPixel_5VE1n1GgDfCH7t8YgN59a6A)(tyObject_TXImage_e0S5K9cN9cczbNOLyWrYKsCQ* ximage, int x, int y, unsigned long pixel) {
	int result;
	nimfr_("XPutPixel", "xutil.nim");
	result = (int)0;
	nimln_(384, "xutil.nim");
	result = (*ximage).f.put_pixel(ximage, x, y, pixel);
	popFrame();
	return result;
}

N_NIMCALL(tyObject_TXImage_e0S5K9cN9cczbNOLyWrYKsCQ*, XSubImage_tmmybLAOs0Xn19cM4S9azznA)(tyObject_TXImage_e0S5K9cN9cczbNOLyWrYKsCQ* ximage, int x, int y, unsigned int width, unsigned int height) {
	tyObject_TXImage_e0S5K9cN9cczbNOLyWrYKsCQ* result;
	nimfr_("XSubImage", "xutil.nim");
	result = (tyObject_TXImage_e0S5K9cN9cczbNOLyWrYKsCQ*)0;
	nimln_(387, "xutil.nim");
	result = (*ximage).f.sub_image(ximage, x, y, width, height);
	popFrame();
	return result;
}

N_NIMCALL(int, XAddPixel_xZcCg9cb9ax8Ue42WPcejruw)(tyObject_TXImage_e0S5K9cN9cczbNOLyWrYKsCQ* ximage, long value) {
	int result;
	nimfr_("XAddPixel", "xutil.nim");
	result = (int)0;
	nimln_(390, "xutil.nim");
	result = (*ximage).f.add_pixel(ximage, value);
	popFrame();
	return result;
}

N_NIMCALL(NIM_BOOL, IsKeypadKey_MvA8ZnvyMLj9a4BZHcY9bBhg)(unsigned long keysym) {
	NIM_BOOL result;
	NIM_BOOL T1_;
	nimfr_("IsKeypadKey", "xutil.nim");
	result = (NIM_BOOL)0;
	nimln_(393, "xutil.nim");
	T1_ = (NIM_BOOL)0;
	T1_ = ((NU64)(((unsigned long) 65408)) <= (NU64)(keysym));
	if (!(T1_)) goto LA2_;
	T1_ = ((NU64)(keysym) <= (NU64)(((unsigned long) 65469)));
	LA2_: ;
	result = T1_;
	popFrame();
	return result;
}

N_NIMCALL(NIM_BOOL, IsPrivateKeypadKey_MvA8ZnvyMLj9a4BZHcY9bBhg_2)(unsigned long keysym) {
	NIM_BOOL result;
	NIM_BOOL T1_;
	nimfr_("IsPrivateKeypadKey", "xutil.nim");
	result = (NIM_BOOL)0;
	nimln_(396, "xutil.nim");
	T1_ = (NIM_BOOL)0;
	T1_ = ((NU64)(((unsigned long) 285212672)) <= (NU64)(keysym));
	if (!(T1_)) goto LA2_;
	T1_ = ((NU64)(keysym) <= (NU64)(((unsigned long) 285278207)));
	LA2_: ;
	result = T1_;
	popFrame();
	return result;
}

N_NIMCALL(NIM_BOOL, IsCursorKey_MvA8ZnvyMLj9a4BZHcY9bBhg_3)(unsigned long keysym) {
	NIM_BOOL result;
	NIM_BOOL T1_;
	nimfr_("IsCursorKey", "xutil.nim");
	result = (NIM_BOOL)0;
	nimln_(399, "xutil.nim");
	T1_ = (NIM_BOOL)0;
	T1_ = ((NU64)(((unsigned long) 65360)) <= (NU64)(keysym));
	if (!(T1_)) goto LA2_;
	T1_ = ((NU64)(keysym) < (NU64)(((unsigned long) 65376)));
	LA2_: ;
	result = T1_;
	popFrame();
	return result;
}

N_NIMCALL(NIM_BOOL, IsPFKey_MvA8ZnvyMLj9a4BZHcY9bBhg_4)(unsigned long keysym) {
	NIM_BOOL result;
	NIM_BOOL T1_;
	nimfr_("IsPFKey", "xutil.nim");
	result = (NIM_BOOL)0;
	nimln_(402, "xutil.nim");
	T1_ = (NIM_BOOL)0;
	T1_ = ((NU64)(((unsigned long) 65425)) <= (NU64)(keysym));
	if (!(T1_)) goto LA2_;
	T1_ = ((NU64)(keysym) <= (NU64)(((unsigned long) 65428)));
	LA2_: ;
	result = T1_;
	popFrame();
	return result;
}

N_NIMCALL(NIM_BOOL, IsFunctionKey_MvA8ZnvyMLj9a4BZHcY9bBhg_5)(unsigned long keysym) {
	NIM_BOOL result;
	NIM_BOOL T1_;
	nimfr_("IsFunctionKey", "xutil.nim");
	result = (NIM_BOOL)0;
	nimln_(405, "xutil.nim");
	T1_ = (NIM_BOOL)0;
	T1_ = ((NU64)(((unsigned long) 65470)) <= (NU64)(keysym));
	if (!(T1_)) goto LA2_;
	T1_ = ((NU64)(keysym) <= (NU64)(((unsigned long) 65504)));
	LA2_: ;
	result = T1_;
	popFrame();
	return result;
}

N_NIMCALL(NIM_BOOL, IsMiscFunctionKey_MvA8ZnvyMLj9a4BZHcY9bBhg_6)(unsigned long keysym) {
	NIM_BOOL result;
	NIM_BOOL T1_;
	nimfr_("IsMiscFunctionKey", "xutil.nim");
	result = (NIM_BOOL)0;
	nimln_(408, "xutil.nim");
	T1_ = (NIM_BOOL)0;
	T1_ = ((NU64)(((unsigned long) 65376)) <= (NU64)(keysym));
	if (!(T1_)) goto LA2_;
	T1_ = ((NU64)(keysym) <= (NU64)(((unsigned long) 65387)));
	LA2_: ;
	result = T1_;
	popFrame();
	return result;
}

N_NIMCALL(NIM_BOOL, IsModifierKey_MvA8ZnvyMLj9a4BZHcY9bBhg_7)(unsigned long keysym) {
	NIM_BOOL result;
	NIM_BOOL T1_;
	NIM_BOOL T2_;
	NIM_BOOL T3_;
	nimfr_("IsModifierKey", "xutil.nim");
	result = (NIM_BOOL)0;
	nimln_(411, "xutil.nim");
	T1_ = (NIM_BOOL)0;
	T2_ = (NIM_BOOL)0;
	T3_ = (NIM_BOOL)0;
	T3_ = ((NU64)(((unsigned long) 65505)) <= (NU64)(keysym));
	if (!(T3_)) goto LA4_;
	T3_ = ((NU64)(keysym) <= (NU64)(((unsigned long) 65518)));
	LA4_: ;
	T2_ = T3_;
	if (T2_) goto LA5_;
	nimln_(412, "xutil.nim");
	T2_ = eqeq__fGnaGOqLnoCI1mmdaRD0qw(keysym, ((unsigned long) 65406));
	LA5_: ;
	T1_ = T2_;
	if (T1_) goto LA6_;
	T1_ = eqeq__fGnaGOqLnoCI1mmdaRD0qw(keysym, ((unsigned long) 65407));
	LA6_: ;
	result = T1_;
	popFrame();
	return result;
}
NIM_EXTERNC N_NOINLINE(void, x11_xutilInit000)(void) {
	nimfr_("xutil", "xutil.nim");
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, x11_xutilDatInit000)(void) {
if (!((TM_QOPO9bL7lOHTZ2zQmB9csB9cw_2 = nimLoadLibrary((NimStringDesc*) &TM_QOPO9bL7lOHTZ2zQmB9csB9cw_4))
||(TM_QOPO9bL7lOHTZ2zQmB9csB9cw_2 = nimLoadLibrary((NimStringDesc*) &TM_QOPO9bL7lOHTZ2zQmB9csB9cw_6))
)) nimLoadLibraryError((NimStringDesc*) &TM_QOPO9bL7lOHTZ2zQmB9csB9cw_7);
	Dl_253349_ = (tyProc_zPzS57h6C05CT3LPxvk8VQ) nimGetProcAddr(TM_QOPO9bL7lOHTZ2zQmB9csB9cw_2, "XAllocClassHint");
	Dl_253351_ = (tyProc_pJCpoi4xciXO6FUOEleglA) nimGetProcAddr(TM_QOPO9bL7lOHTZ2zQmB9csB9cw_2, "XAllocIconSize");
	Dl_253353_ = (tyProc_7zYEZ6TVffoUgPh9cS1FVvQ) nimGetProcAddr(TM_QOPO9bL7lOHTZ2zQmB9csB9cw_2, "XAllocSizeHints");
	Dl_253355_ = (tyProc_RWaKkowz8mBzKnCrdrwjUg) nimGetProcAddr(TM_QOPO9bL7lOHTZ2zQmB9csB9cw_2, "XAllocStandardColormap");
	Dl_253357_ = (tyProc_L1zdNDE1z1SfZRa1ZUswQQ) nimGetProcAddr(TM_QOPO9bL7lOHTZ2zQmB9csB9cw_2, "XAllocWMHints");
	Dl_253359_ = (tyProc_kxUovtzjOWnOB9bjPGH8jPw) nimGetProcAddr(TM_QOPO9bL7lOHTZ2zQmB9csB9cw_2, "XClipBox");
	Dl_253363_ = (tyProc_18cSxVS2RbnYA9aP5LAiXTA) nimGetProcAddr(TM_QOPO9bL7lOHTZ2zQmB9csB9cw_2, "XCreateRegion");
	Dl_253365_ = (tyProc_09bvyvHFtWbkzL5AHgf0bKw) nimGetProcAddr(TM_QOPO9bL7lOHTZ2zQmB9csB9cw_2, "XDefaultString");
	Dl_253367_ = (tyProc_uF7GbVXhvDog9c9bqqyS81Ig) nimGetProcAddr(TM_QOPO9bL7lOHTZ2zQmB9csB9cw_2, "XDeleteContext");
	Dl_253372_ = (tyProc_kD3MN9b4eKAFWThEkkqC1qQ) nimGetProcAddr(TM_QOPO9bL7lOHTZ2zQmB9csB9cw_2, "XDestroyRegion");
	Dl_253375_ = (tyProc_kD3MN9b4eKAFWThEkkqC1qQ) nimGetProcAddr(TM_QOPO9bL7lOHTZ2zQmB9csB9cw_2, "XEmptyRegion");
	Dl_253378_ = (tyProc_iIDrWqptIMblKaHgMXxmFA) nimGetProcAddr(TM_QOPO9bL7lOHTZ2zQmB9csB9cw_2, "XEqualRegion");
	Dl_253382_ = (tyProc_MvXaxx9af9aes7JMcvxfXcwQ) nimGetProcAddr(TM_QOPO9bL7lOHTZ2zQmB9csB9cw_2, "XFindContext");
	Dl_253388_ = (tyProc_xfGEjrfsPPQqFjsbgDCjrg) nimGetProcAddr(TM_QOPO9bL7lOHTZ2zQmB9csB9cw_2, "XGetClassHint");
	Dl_253393_ = (tyProc_hXHLHBkPLRusiPSv9cRq5tQ) nimGetProcAddr(TM_QOPO9bL7lOHTZ2zQmB9csB9cw_2, "XGetIconSizes");
	Dl_253399_ = (tyProc_9aWivT6Edf8PyRV3NvT2h7A) nimGetProcAddr(TM_QOPO9bL7lOHTZ2zQmB9csB9cw_2, "XGetNormalHints");
	Dl_253404_ = (tyProc_aE1CTOki9aJy3wlSnUOsIAw) nimGetProcAddr(TM_QOPO9bL7lOHTZ2zQmB9csB9cw_2, "XGetRGBColormaps");
	Dl_253411_ = (tyProc_IR12rrjzxXqgWXmxKVeikQ) nimGetProcAddr(TM_QOPO9bL7lOHTZ2zQmB9csB9cw_2, "XGetSizeHints");
	Dl_253417_ = (tyProc_WWiO8ZQc2dKjnHaEHe1S3g) nimGetProcAddr(TM_QOPO9bL7lOHTZ2zQmB9csB9cw_2, "XGetStandardColormap");
	Dl_253423_ = (tyProc_uy1vOa8ZTciMPQucUf1dRw) nimGetProcAddr(TM_QOPO9bL7lOHTZ2zQmB9csB9cw_2, "XGetTextProperty");
	Dl_253429_ = (tyProc_1EP29cbWh0jd4WO3c9cYpPlg) nimGetProcAddr(TM_QOPO9bL7lOHTZ2zQmB9csB9cw_2, "XGetVisualInfo");
	Dl_253435_ = (tyProc_t0ariGsj6KPo59bWvCmGpPA) nimGetProcAddr(TM_QOPO9bL7lOHTZ2zQmB9csB9cw_2, "XGetWMClientMachine");
	Dl_253440_ = (tyProc_JJYIMEzhjdI79cJbNQfZydg) nimGetProcAddr(TM_QOPO9bL7lOHTZ2zQmB9csB9cw_2, "XGetWMHints");
	Dl_253444_ = (tyProc_t0ariGsj6KPo59bWvCmGpPA) nimGetProcAddr(TM_QOPO9bL7lOHTZ2zQmB9csB9cw_2, "XGetWMIconName");
	Dl_253449_ = (tyProc_t0ariGsj6KPo59bWvCmGpPA) nimGetProcAddr(TM_QOPO9bL7lOHTZ2zQmB9csB9cw_2, "XGetWMName");
	Dl_253454_ = (tyProc_gjSQ7qB9b8sOx14Hf3QZUdg) nimGetProcAddr(TM_QOPO9bL7lOHTZ2zQmB9csB9cw_2, "XGetWMNormalHints");
	Dl_253461_ = (tyProc_OA9c9b5DYNlsm03Et2i9c2PiQ) nimGetProcAddr(TM_QOPO9bL7lOHTZ2zQmB9csB9cw_2, "XGetWMSizeHints");
	Dl_253469_ = (tyProc_9aWivT6Edf8PyRV3NvT2h7A) nimGetProcAddr(TM_QOPO9bL7lOHTZ2zQmB9csB9cw_2, "XGetZoomHints");
	Dl_253474_ = (tyProc_De4LPoObmzbYuD1tbqZK3g) nimGetProcAddr(TM_QOPO9bL7lOHTZ2zQmB9csB9cw_2, "XIntersectRegion");
	Dl_253479_ = (tyProc_CuIjqy8B9cY8wP5e6RwMulQ) nimGetProcAddr(TM_QOPO9bL7lOHTZ2zQmB9csB9cw_2, "XConvertCase");
	Dl_253484_ = (tyProc_RAYLa1dnoEEzrJRfMgh5Kg) nimGetProcAddr(TM_QOPO9bL7lOHTZ2zQmB9csB9cw_2, "XLookupString");
	Dl_253491_ = (tyProc_rdWhMebssS7tE3LFN1FJJw) nimGetProcAddr(TM_QOPO9bL7lOHTZ2zQmB9csB9cw_2, "XMatchVisualInfo");
	Dl_253498_ = (tyProc_CPOUL7sfsUggPfYMUN6l9aA) nimGetProcAddr(TM_QOPO9bL7lOHTZ2zQmB9csB9cw_2, "XOffsetRegion");
	Dl_253503_ = (tyProc_FodgJ0LEUemXg9bKFCuYBEA) nimGetProcAddr(TM_QOPO9bL7lOHTZ2zQmB9csB9cw_2, "XPointInRegion");
	Dl_253508_ = (tyProc_brF9cwu3OgcV0hrOykgubgg) nimGetProcAddr(TM_QOPO9bL7lOHTZ2zQmB9csB9cw_2, "XPolygonRegion");
	Dl_253513_ = (tyProc_cZEY9cicFK2coDAS8XZOtKw) nimGetProcAddr(TM_QOPO9bL7lOHTZ2zQmB9csB9cw_2, "XRectInRegion");
	Dl_253520_ = (tyProc_0ysgWDKm2NQM0u9bCv9bxQXQ) nimGetProcAddr(TM_QOPO9bL7lOHTZ2zQmB9csB9cw_2, "XSaveContext");
	Dl_253526_ = (tyProc_TkM0ne8UilJKwRLed52cMA) nimGetProcAddr(TM_QOPO9bL7lOHTZ2zQmB9csB9cw_2, "XSetClassHint");
	Dl_253531_ = (tyProc_1JuAutjX49a3f4OAhFCWQ9cg) nimGetProcAddr(TM_QOPO9bL7lOHTZ2zQmB9csB9cw_2, "XSetIconSizes");
	Dl_253537_ = (tyProc_tQBdXnFpE3bhq80ssEfI9bA) nimGetProcAddr(TM_QOPO9bL7lOHTZ2zQmB9csB9cw_2, "XSetNormalHints");
	Dl_253542_ = (tyProc_r6lA9c8FtuWj3a9bl6Jd2QBA) nimGetProcAddr(TM_QOPO9bL7lOHTZ2zQmB9csB9cw_2, "XSetRGBColormaps");
	Dl_253549_ = (tyProc_ZfrFP9amdyPLHtIcgrvP2uQ) nimGetProcAddr(TM_QOPO9bL7lOHTZ2zQmB9csB9cw_2, "XSetSizeHints");
	Dl_253555_ = (tyProc_xNsRqAHBsNean7PbtB9aSNA) nimGetProcAddr(TM_QOPO9bL7lOHTZ2zQmB9csB9cw_2, "XSetStandardProperties");
	Dl_253565_ = (tyProc_VK0lxcwnR9amQgo06oJw0kA) nimGetProcAddr(TM_QOPO9bL7lOHTZ2zQmB9csB9cw_2, "XSetTextProperty");
	Dl_253571_ = (tyProc_Zf9cgsdUeEnzsbxSvwv1gQA) nimGetProcAddr(TM_QOPO9bL7lOHTZ2zQmB9csB9cw_2, "XSetWMClientMachine");
	Dl_253576_ = (tyProc_gvy64YosY7QevxBqsy7RCQ) nimGetProcAddr(TM_QOPO9bL7lOHTZ2zQmB9csB9cw_2, "XSetWMHints");
	Dl_253581_ = (tyProc_Zf9cgsdUeEnzsbxSvwv1gQA) nimGetProcAddr(TM_QOPO9bL7lOHTZ2zQmB9csB9cw_2, "XSetWMIconName");
	Dl_253586_ = (tyProc_Zf9cgsdUeEnzsbxSvwv1gQA) nimGetProcAddr(TM_QOPO9bL7lOHTZ2zQmB9csB9cw_2, "XSetWMName");
	Dl_253591_ = (tyProc_8dH9ahTZgn89awr7UTJG9aYhQ) nimGetProcAddr(TM_QOPO9bL7lOHTZ2zQmB9csB9cw_2, "XSetWMNormalHints");
	Dl_253596_ = (tyProc_JslQe9cADo8jGQWrC6S19bag) nimGetProcAddr(TM_QOPO9bL7lOHTZ2zQmB9csB9cw_2, "XSetWMProperties");
	Dl_253607_ = (tyProc_tWlQKgtpZdVozp3cnGqYCw) nimGetProcAddr(TM_QOPO9bL7lOHTZ2zQmB9csB9cw_2, "XmbSetWMProperties");
	Dl_253618_ = (tyProc_tWlQKgtpZdVozp3cnGqYCw) nimGetProcAddr(TM_QOPO9bL7lOHTZ2zQmB9csB9cw_2, "Xutf8SetWMProperties");
	Dl_253629_ = (tyProc_M09bQyDal8ZRgJ874GtLhLg) nimGetProcAddr(TM_QOPO9bL7lOHTZ2zQmB9csB9cw_2, "XSetWMSizeHints");
	Dl_253635_ = (tyProc_E5XSzdTsseY9bfH771Rthxg) nimGetProcAddr(TM_QOPO9bL7lOHTZ2zQmB9csB9cw_2, "XSetRegion");
	Dl_253640_ = (tyProc_mueeJxz6EWk04dsLmuQ6Ew) nimGetProcAddr(TM_QOPO9bL7lOHTZ2zQmB9csB9cw_2, "XSetStandardColormap");
	Dl_253646_ = (tyProc_tQBdXnFpE3bhq80ssEfI9bA) nimGetProcAddr(TM_QOPO9bL7lOHTZ2zQmB9csB9cw_2, "XSetZoomHints");
	Dl_253651_ = (tyProc_CPOUL7sfsUggPfYMUN6l9aA) nimGetProcAddr(TM_QOPO9bL7lOHTZ2zQmB9csB9cw_2, "XShrinkRegion");
	Dl_253656_ = (tyProc_QtKMkiuvFVJA9aoJrOG2A9bA) nimGetProcAddr(TM_QOPO9bL7lOHTZ2zQmB9csB9cw_2, "XStringListToTextProperty");
	Dl_253661_ = (tyProc_De4LPoObmzbYuD1tbqZK3g) nimGetProcAddr(TM_QOPO9bL7lOHTZ2zQmB9csB9cw_2, "XSubtractRegion");
	Dl_253666_ = (tyProc_8lLJp9aaRyUq19a1RKOM5GbQ) nimGetProcAddr(TM_QOPO9bL7lOHTZ2zQmB9csB9cw_2, "XmbTextListToTextProperty");
	Dl_253673_ = (tyProc_lW3r9c2gB6QRGf5BIA8ntdg) nimGetProcAddr(TM_QOPO9bL7lOHTZ2zQmB9csB9cw_2, "XwcTextListToTextProperty");
	Dl_253682_ = (tyProc_8lLJp9aaRyUq19a1RKOM5GbQ) nimGetProcAddr(TM_QOPO9bL7lOHTZ2zQmB9csB9cw_2, "Xutf8TextListToTextProperty");
	Dl_253689_ = (tyProc_Y8u4eB4zmFgeOnSJfKgaUQ) nimGetProcAddr(TM_QOPO9bL7lOHTZ2zQmB9csB9cw_2, "XwcFreeStringList");
	Dl_253694_ = (tyProc_ydSLfh3PyA4Pb0859bTyDLw) nimGetProcAddr(TM_QOPO9bL7lOHTZ2zQmB9csB9cw_2, "XTextPropertyToStringList");
	Dl_253699_ = (tyProc_o6Ya9cfTymcwdTOpf5QrQ8A) nimGetProcAddr(TM_QOPO9bL7lOHTZ2zQmB9csB9cw_2, "XmbTextPropertyToTextList");
	Dl_253705_ = (tyProc_0PYOSmE79bK9b9c0jmrHKXR9bQ) nimGetProcAddr(TM_QOPO9bL7lOHTZ2zQmB9csB9cw_2, "XwcTextPropertyToTextList");
	Dl_253714_ = (tyProc_o6Ya9cfTymcwdTOpf5QrQ8A) nimGetProcAddr(TM_QOPO9bL7lOHTZ2zQmB9csB9cw_2, "Xutf8TextPropertyToTextList");
	Dl_253720_ = (tyProc_ilxbT6WFqGS7tU2VAZ9cEZg) nimGetProcAddr(TM_QOPO9bL7lOHTZ2zQmB9csB9cw_2, "XUnionRectWithRegion");
	Dl_253725_ = (tyProc_De4LPoObmzbYuD1tbqZK3g) nimGetProcAddr(TM_QOPO9bL7lOHTZ2zQmB9csB9cw_2, "XUnionRegion");
	Dl_253730_ = (tyProc_iR6R09all3Jek9bL9c6frTEkA) nimGetProcAddr(TM_QOPO9bL7lOHTZ2zQmB9csB9cw_2, "XWMGeometry");
	Dl_253743_ = (tyProc_De4LPoObmzbYuD1tbqZK3g) nimGetProcAddr(TM_QOPO9bL7lOHTZ2zQmB9csB9cw_2, "XXorRegion");
}

