/* Generated by Nim Compiler v0.17.2 */
/*   (c) 2017 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w  -I/home/vlad/Nim/lib -o /home/vlad/Sandbox/learnopengl/getting_started/nimcache/glm_mat_transform.o /home/vlad/Sandbox/learnopengl/getting_started/nimcache/glm_mat_transform.c */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#include <math.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef powerpc
#undef unix
typedef struct tyObject_Mat_rRXFRTYKpgDJ5Kn1m7tKHA tyObject_Mat_rRXFRTYKpgDJ5Kn1m7tKHA;
typedef struct tyObject_Vec_nc2ATn3mNKEC36f9a1o6BCw tyObject_Vec_nc2ATn3mNKEC36f9a1o6BCw;
typedef struct tyObject_Vec_8lp09c9aJ6sSqRDc8uUVfyuA tyObject_Vec_8lp09c9aJ6sSqRDc8uUVfyuA;
typedef NF32 tyArray_9aTCwbdg1cSQimdVd0OEKVw[4];
struct tyObject_Vec_nc2ATn3mNKEC36f9a1o6BCw {
tyArray_9aTCwbdg1cSQimdVd0OEKVw arr;
};
typedef tyObject_Vec_nc2ATn3mNKEC36f9a1o6BCw tyArray_Vwko69bN4O2Unwiy9crf9a1iQ[4];
struct tyObject_Mat_rRXFRTYKpgDJ5Kn1m7tKHA {
tyArray_Vwko69bN4O2Unwiy9crf9a1iQ arr;
};
typedef NF32 tyArray_mXNbtvWKAiZn9bWV4uCjiKg[3];
struct tyObject_Vec_8lp09c9aJ6sSqRDc8uUVfyuA {
tyArray_mXNbtvWKAiZn9bWV4uCjiKg arr;
};
N_NIMCALL(tyObject_Mat_rRXFRTYKpgDJ5Kn1m7tKHA, lookAtRH_iN7yJSIyVMaEk9c9azyZAbBQ_2)(tyObject_Vec_8lp09c9aJ6sSqRDc8uUVfyuA eye, tyObject_Vec_8lp09c9aJ6sSqRDc8uUVfyuA center, tyObject_Vec_8lp09c9aJ6sSqRDc8uUVfyuA up);
N_NIMCALL(tyObject_Vec_8lp09c9aJ6sSqRDc8uUVfyuA, normalize_teBxubc60zLsP82FZ7wr1A)(tyObject_Vec_8lp09c9aJ6sSqRDc8uUVfyuA v);
static N_INLINE(tyObject_Vec_8lp09c9aJ6sSqRDc8uUVfyuA, minus__J7vWjOv59bjwwYcDHMIUtEgvec)(tyObject_Vec_8lp09c9aJ6sSqRDc8uUVfyuA v, tyObject_Vec_8lp09c9aJ6sSqRDc8uUVfyuA u);
N_NOINLINE(void, raiseIndexError)(void);
static N_INLINE(NI, addInt)(NI a, NI b);
N_NOINLINE(void, raiseOverflow)(void);
static N_INLINE(void, nimFrame)(TFrame* s);
N_NOINLINE(void, stackOverflow_II46IjNZztN9bmbxUD8dt8g)(void);
static N_INLINE(void, popFrame)(void);
N_NIMCALL(tyObject_Vec_8lp09c9aJ6sSqRDc8uUVfyuA, cross_u30ZqBLCPuracR4Z1FBPOQ)(tyObject_Vec_8lp09c9aJ6sSqRDc8uUVfyuA v1, tyObject_Vec_8lp09c9aJ6sSqRDc8uUVfyuA v2);
N_NIMCALL(tyObject_Mat_rRXFRTYKpgDJ5Kn1m7tKHA, mat4_dnl08WbvO2CTNBskwbejJA)(NF32 s);
N_NIMCALL(void, row0eq__qL9cF9cOCu0hEf9crQaEJdlMg)(tyObject_Mat_rRXFRTYKpgDJ5Kn1m7tKHA* m, tyObject_Vec_nc2ATn3mNKEC36f9a1o6BCw value);
static N_INLINE(tyObject_Vec_nc2ATn3mNKEC36f9a1o6BCw, vec4_ITdPzFAfjQ2t9c6sbu9bSPiQmat_transform)(tyObject_Vec_8lp09c9aJ6sSqRDc8uUVfyuA v, NF32 w);
static N_INLINE(NF32, x_Xbi8c1XUPkUTWFDNj5l5oQvec)(tyObject_Vec_8lp09c9aJ6sSqRDc8uUVfyuA v);
static N_INLINE(NF32, y_Xbi8c1XUPkUTWFDNj5l5oQ_2vec)(tyObject_Vec_8lp09c9aJ6sSqRDc8uUVfyuA v);
static N_INLINE(NF32, z_Xbi8c1XUPkUTWFDNj5l5oQ_3vec)(tyObject_Vec_8lp09c9aJ6sSqRDc8uUVfyuA v);
N_NIMCALL(void, row1eq__qL9cF9cOCu0hEf9crQaEJdlMg_2)(tyObject_Mat_rRXFRTYKpgDJ5Kn1m7tKHA* m, tyObject_Vec_nc2ATn3mNKEC36f9a1o6BCw value);
N_NIMCALL(void, row2eq__qL9cF9cOCu0hEf9crQaEJdlMg_3)(tyObject_Mat_rRXFRTYKpgDJ5Kn1m7tKHA* m, tyObject_Vec_nc2ATn3mNKEC36f9a1o6BCw value);
N_NIMCALL(tyObject_Vec_8lp09c9aJ6sSqRDc8uUVfyuA, minus__teBxubc60zLsP82FZ7wr1A_2)(tyObject_Vec_8lp09c9aJ6sSqRDc8uUVfyuA v);
static N_INLINE(tyObject_Vec_nc2ATn3mNKEC36f9a1o6BCw, vec4_AaOb1efTPrDJJ9aKeFHEEGwmat_transform)(NF32 x, NF32 y, NF32 z, NF32 w);
static N_INLINE(NF32, dot_fVg9b9b1P9aDx1N4voq9cgRWhQquat)(tyObject_Vec_8lp09c9aJ6sSqRDc8uUVfyuA u, tyObject_Vec_8lp09c9aJ6sSqRDc8uUVfyuA v);
static N_INLINE(void, pluseq__0Q9c9ccOr82GxaUx3qtv9aCoQquat)(NF32* x, NF32 y);
static N_INLINE(NF32, X5BX5D__1laBXuXKeK8f9aVhwaW9bDCAquat)(tyObject_Vec_8lp09c9aJ6sSqRDc8uUVfyuA v, NI ix);
static N_INLINE(void, X5BX5Deq__nmP8mqMhlxbqODgoT9cwyaQmat_transform)(tyObject_Mat_rRXFRTYKpgDJ5Kn1m7tKHA* v, NI ix, NI iy, NF32 value);
N_NIMCALL(tyObject_Mat_rRXFRTYKpgDJ5Kn1m7tKHA, perspectiveRH_HDtXEbqPG0MYpwNwpSvogw_2)(NF32 fovy, NF32 aspect, NF32 zNear, NF32 zFar);
static N_INLINE(void, X5BX5Deq__u2pJD47Sl0vMQJcmqqWTgQmat_transform)(tyObject_Mat_rRXFRTYKpgDJ5Kn1m7tKHA* v, NI ix, tyObject_Vec_nc2ATn3mNKEC36f9a1o6BCw c);
static N_INLINE(tyObject_Vec_nc2ATn3mNKEC36f9a1o6BCw, plus__XtiXXDU2o8buzgLSxx9aD0wmat_transform)(tyObject_Vec_nc2ATn3mNKEC36f9a1o6BCw v, tyObject_Vec_nc2ATn3mNKEC36f9a1o6BCw u);
static N_INLINE(tyObject_Vec_nc2ATn3mNKEC36f9a1o6BCw, star__UkZJjcWPs0frWwxTW2fkWwmat_transform)(tyObject_Vec_nc2ATn3mNKEC36f9a1o6BCw v, NF32 val);
static N_INLINE(tyObject_Vec_nc2ATn3mNKEC36f9a1o6BCw, X5BX5D__eheLjiNw9aBDJp8bmeHHY9awquat)(tyObject_Mat_rRXFRTYKpgDJ5Kn1m7tKHA* v, NI ix);
static N_INLINE(tyObject_Vec_8lp09c9aJ6sSqRDc8uUVfyuA, star__F5mbSxuiB9b1sFSsWVW2fPwmain)(NF32 val, tyObject_Vec_8lp09c9aJ6sSqRDc8uUVfyuA v);
static N_INLINE(NF32*, X5BX5D__KG7x1R5fw1Adi9c9bKzkEkeAmat_transform)(tyObject_Vec_8lp09c9aJ6sSqRDc8uUVfyuA* v, NI ix);
static N_INLINE(NF32*, X5BX5D__vrkiyjLlnepZ8jblNrp6Cgmat_transform)(tyObject_Mat_rRXFRTYKpgDJ5Kn1m7tKHA* v, NI ix, NI iy);
extern TFrame* framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;

static N_INLINE(NI, addInt)(NI a, NI b) {
	NI result;
{	result = (NI)0;
	result = (NI)((NU64)(a) + (NU64)(b));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI) 0) <= (NI)(result ^ a));
		if (T3_) goto LA4_;
		T3_ = (((NI) 0) <= (NI)(result ^ b));
		LA4_: ;
		if (!T3_) goto LA5_;
		goto BeforeRet_;
	}
	LA5_: ;
	raiseOverflow();
	}BeforeRet_: ;
	return result;
}

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI T1_;
	T1_ = (NI)0;
	{
		if (!(framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw == NIM_NIL)) goto LA4_;
		T1_ = ((NI) 0);
	}
	goto LA2_;
	LA4_: ;
	{
		T1_ = ((NI) ((NI16)((*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).calldepth + ((NI16) 1))));
	}
	LA2_: ;
	(*s).calldepth = ((NI16) (T1_));
	(*s).prev = framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9_;
		stackOverflow_II46IjNZztN9bmbxUD8dt8g();
	}
	LA9_: ;
}

static N_INLINE(void, popFrame)(void) {
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = (*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).prev;
}

static N_INLINE(tyObject_Vec_8lp09c9aJ6sSqRDc8uUVfyuA, minus__J7vWjOv59bjwwYcDHMIUtEgvec)(tyObject_Vec_8lp09c9aJ6sSqRDc8uUVfyuA v, tyObject_Vec_8lp09c9aJ6sSqRDc8uUVfyuA u) {
	tyObject_Vec_8lp09c9aJ6sSqRDc8uUVfyuA result;
	nimfr_("-", "vec.nim");
	memset((void*)(&result), 0, sizeof(result));
	{
		NI ii;
		NI i;
		ii = (NI)0;
		nimln_(3847, "system.nim");
		i = ((NI) 0);
		{
			nimln_(3848, "system.nim");
			while (1) {
				NI TM_s59aFOVpWWMmZYpGM3kpqFQ_2;
				if (!(i < ((NI) 3))) goto LA3;
				nimln_(3849, "system.nim");
				ii = i;
				if ((NU)(ii) > (NU)(2)) raiseIndexError();
				nimln_(109, "vec.nim");
				if ((NU)(ii) > (NU)(2)) raiseIndexError();
				if ((NU)(ii) > (NU)(2)) raiseIndexError();
				result.arr[(ii)- 0] = ((NF32)(v.arr[(ii)- 0]) - (NF32)(u.arr[(ii)- 0]));
				nimln_(3850, "system.nim");
				TM_s59aFOVpWWMmZYpGM3kpqFQ_2 = addInt(i, ((NI) 1));
				i = (NI)(TM_s59aFOVpWWMmZYpGM3kpqFQ_2);
			} LA3: ;
		}
	}
	popFrame();
	return result;
}

static N_INLINE(NF32, x_Xbi8c1XUPkUTWFDNj5l5oQvec)(tyObject_Vec_8lp09c9aJ6sSqRDc8uUVfyuA v) {
	NF32 result;
	nimfr_("x", "vec.nim");
	result = (NF32)0;
	nimln_(255, "vec.nim");
	result = v.arr[(((NI) 0))- 0];
	popFrame();
	return result;
}

static N_INLINE(NF32, y_Xbi8c1XUPkUTWFDNj5l5oQ_2vec)(tyObject_Vec_8lp09c9aJ6sSqRDc8uUVfyuA v) {
	NF32 result;
	nimfr_("y", "vec.nim");
	result = (NF32)0;
	nimln_(255, "vec.nim");
	result = v.arr[(((NI) 1))- 0];
	popFrame();
	return result;
}

static N_INLINE(NF32, z_Xbi8c1XUPkUTWFDNj5l5oQ_3vec)(tyObject_Vec_8lp09c9aJ6sSqRDc8uUVfyuA v) {
	NF32 result;
	nimfr_("z", "vec.nim");
	result = (NF32)0;
	nimln_(255, "vec.nim");
	result = v.arr[(((NI) 2))- 0];
	popFrame();
	return result;
}

static N_INLINE(tyObject_Vec_nc2ATn3mNKEC36f9a1o6BCw, vec4_ITdPzFAfjQ2t9c6sbu9bSPiQmat_transform)(tyObject_Vec_8lp09c9aJ6sSqRDc8uUVfyuA v, NF32 w) {
	tyObject_Vec_nc2ATn3mNKEC36f9a1o6BCw result;
	tyObject_Vec_nc2ATn3mNKEC36f9a1o6BCw T1_;
	nimfr_("vec4", "vec.nim");
	memset((void*)(&result), 0, sizeof(result));
	nimln_(158, "vec.nim");
	memset((void*)(&T1_), 0, sizeof(T1_));
	T1_.arr[0] = x_Xbi8c1XUPkUTWFDNj5l5oQvec(v);
	T1_.arr[1] = y_Xbi8c1XUPkUTWFDNj5l5oQ_2vec(v);
	T1_.arr[2] = z_Xbi8c1XUPkUTWFDNj5l5oQ_3vec(v);
	T1_.arr[3] = w;
	result = T1_;
	popFrame();
	return result;
}

static N_INLINE(tyObject_Vec_nc2ATn3mNKEC36f9a1o6BCw, vec4_AaOb1efTPrDJJ9aKeFHEEGwmat_transform)(NF32 x, NF32 y, NF32 z, NF32 w) {
	tyObject_Vec_nc2ATn3mNKEC36f9a1o6BCw result;
	tyObject_Vec_nc2ATn3mNKEC36f9a1o6BCw T1_;
	nimfr_("vec4", "vec.nim");
	memset((void*)(&result), 0, sizeof(result));
	nimln_(157, "vec.nim");
	memset((void*)(&T1_), 0, sizeof(T1_));
	T1_.arr[0] = x;
	T1_.arr[1] = y;
	T1_.arr[2] = z;
	T1_.arr[3] = w;
	result = T1_;
	popFrame();
	return result;
}

static N_INLINE(void, pluseq__0Q9c9ccOr82GxaUx3qtv9aCoQquat)(NF32* x, NF32 y) {
	nimfr_("+=", "system.nim");
	nimln_(3549, "system.nim");
	(*x) = ((NF32)((*x)) + (NF32)(y));
	popFrame();
}

static N_INLINE(NF32, X5BX5D__1laBXuXKeK8f9aVhwaW9bDCAquat)(tyObject_Vec_8lp09c9aJ6sSqRDc8uUVfyuA v, NI ix) {
	NF32 result;
	nimfr_("[]", "vec.nim");
	result = (NF32)0;
	nimln_(149, "vec.nim");
	if ((NU)(ix) > (NU)(2)) raiseIndexError();
	result = v.arr[(ix)- 0];
	popFrame();
	return result;
}

static N_INLINE(NF32, dot_fVg9b9b1P9aDx1N4voq9cgRWhQquat)(tyObject_Vec_8lp09c9aJ6sSqRDc8uUVfyuA u, tyObject_Vec_8lp09c9aJ6sSqRDc8uUVfyuA v) {
	NF32 result;
	nimfr_("dot", "vec.nim");
	result = (NF32)0;
	{
		NI i;
		NI i_2;
		i = (NI)0;
		nimln_(3847, "system.nim");
		i_2 = ((NI) 0);
		{
			nimln_(3848, "system.nim");
			while (1) {
				NF32 T4_;
				NF32 T5_;
				NI TM_s59aFOVpWWMmZYpGM3kpqFQ_3;
				if (!(i_2 < ((NI) 3))) goto LA3;
				nimln_(3849, "system.nim");
				i = i_2;
				nimln_(478, "vec.nim");
				T4_ = (NF32)0;
				T4_ = X5BX5D__1laBXuXKeK8f9aVhwaW9bDCAquat(u, i);
				T5_ = (NF32)0;
				T5_ = X5BX5D__1laBXuXKeK8f9aVhwaW9bDCAquat(v, i);
				pluseq__0Q9c9ccOr82GxaUx3qtv9aCoQquat((&result), ((NF32)(T4_) * (NF32)(T5_)));
				nimln_(3850, "system.nim");
				TM_s59aFOVpWWMmZYpGM3kpqFQ_3 = addInt(i_2, ((NI) 1));
				i_2 = (NI)(TM_s59aFOVpWWMmZYpGM3kpqFQ_3);
			} LA3: ;
		}
	}
	popFrame();
	return result;
}

static N_INLINE(void, X5BX5Deq__nmP8mqMhlxbqODgoT9cwyaQmat_transform)(tyObject_Mat_rRXFRTYKpgDJ5Kn1m7tKHA* v, NI ix, NI iy, NF32 value) {
	nimfr_("[]=", "mat.nim");
	if ((NU)(ix) > (NU)(3)) raiseIndexError();
	if ((NU)(iy) > (NU)(3)) raiseIndexError();
	nimln_(41, "mat.nim");
	(*v).arr[(ix)- 0].arr[(iy)- 0] = value;
	popFrame();
}

N_NIMCALL(tyObject_Mat_rRXFRTYKpgDJ5Kn1m7tKHA, lookAtRH_iN7yJSIyVMaEk9c9azyZAbBQ_2)(tyObject_Vec_8lp09c9aJ6sSqRDc8uUVfyuA eye, tyObject_Vec_8lp09c9aJ6sSqRDc8uUVfyuA center, tyObject_Vec_8lp09c9aJ6sSqRDc8uUVfyuA up) {
	tyObject_Mat_rRXFRTYKpgDJ5Kn1m7tKHA result;
	tyObject_Vec_8lp09c9aJ6sSqRDc8uUVfyuA f;
	tyObject_Vec_8lp09c9aJ6sSqRDc8uUVfyuA T1_;
	tyObject_Vec_8lp09c9aJ6sSqRDc8uUVfyuA s;
	tyObject_Vec_8lp09c9aJ6sSqRDc8uUVfyuA T2_;
	tyObject_Vec_8lp09c9aJ6sSqRDc8uUVfyuA u;
	tyObject_Vec_nc2ATn3mNKEC36f9a1o6BCw T3_;
	tyObject_Vec_nc2ATn3mNKEC36f9a1o6BCw T4_;
	tyObject_Vec_8lp09c9aJ6sSqRDc8uUVfyuA T5_;
	tyObject_Vec_nc2ATn3mNKEC36f9a1o6BCw T6_;
	NF32 T7_;
	NF32 T8_;
	NF32 T9_;
	NF32 T10_;
	NF32 T11_;
	NF32 T12_;
	nimfr_("lookAtRH", "mat_transform.nim");
	memset((void*)(&result), 0, sizeof(result));
	nimln_(91, "mat_transform.nim");
	T1_ = minus__J7vWjOv59bjwwYcDHMIUtEgvec(center, eye);
	f = normalize_teBxubc60zLsP82FZ7wr1A(T1_);
	nimln_(92, "mat_transform.nim");
	T2_ = cross_u30ZqBLCPuracR4Z1FBPOQ(f, up);
	s = normalize_teBxubc60zLsP82FZ7wr1A(T2_);
	nimln_(93, "mat_transform.nim");
	u = cross_u30ZqBLCPuracR4Z1FBPOQ(s, f);
	nimln_(94, "mat_transform.nim");
	result = mat4_dnl08WbvO2CTNBskwbejJA(1.0000000000000000e+00);
	nimln_(95, "mat_transform.nim");
	T3_ = vec4_ITdPzFAfjQ2t9c6sbu9bSPiQmat_transform(s, 0.0);
	row0eq__qL9cF9cOCu0hEf9crQaEJdlMg((&result), T3_);
	nimln_(96, "mat_transform.nim");
	T4_ = vec4_ITdPzFAfjQ2t9c6sbu9bSPiQmat_transform(u, 0.0);
	row1eq__qL9cF9cOCu0hEf9crQaEJdlMg_2((&result), T4_);
	nimln_(97, "mat_transform.nim");
	T5_ = minus__teBxubc60zLsP82FZ7wr1A_2(f);
	T6_ = vec4_ITdPzFAfjQ2t9c6sbu9bSPiQmat_transform(T5_, 0.0);
	row2eq__qL9cF9cOCu0hEf9crQaEJdlMg_3((&result), T6_);
	nimln_(98, "mat_transform.nim");
	T7_ = (NF32)0;
	T7_ = dot_fVg9b9b1P9aDx1N4voq9cgRWhQquat(s, eye);
	T8_ = (NF32)0;
	T8_ = dot_fVg9b9b1P9aDx1N4voq9cgRWhQquat(u, eye);
	T9_ = (NF32)0;
	T9_ = dot_fVg9b9b1P9aDx1N4voq9cgRWhQquat(f, eye);
	result.arr[(((NI) 3))- 0] = vec4_AaOb1efTPrDJJ9aKeFHEEGwmat_transform(-(T7_), -(T8_), T9_, 1.0000000000000000e+00);
	nimln_(99, "mat_transform.nim");
	T10_ = (NF32)0;
	T10_ = dot_fVg9b9b1P9aDx1N4voq9cgRWhQquat(s, eye);
	X5BX5Deq__nmP8mqMhlxbqODgoT9cwyaQmat_transform((&result), ((NI) 3), ((NI) 0), -(T10_));
	nimln_(100, "mat_transform.nim");
	T11_ = (NF32)0;
	T11_ = dot_fVg9b9b1P9aDx1N4voq9cgRWhQquat(u, eye);
	X5BX5Deq__nmP8mqMhlxbqODgoT9cwyaQmat_transform((&result), ((NI) 3), ((NI) 1), -(T11_));
	nimln_(101, "mat_transform.nim");
	T12_ = (NF32)0;
	T12_ = dot_fVg9b9b1P9aDx1N4voq9cgRWhQquat(f, eye);
	X5BX5Deq__nmP8mqMhlxbqODgoT9cwyaQmat_transform((&result), ((NI) 3), ((NI) 2), T12_);
	popFrame();
	return result;
}

N_NIMCALL(tyObject_Mat_rRXFRTYKpgDJ5Kn1m7tKHA, lookAt_iN7yJSIyVMaEk9c9azyZAbBQ)(tyObject_Vec_8lp09c9aJ6sSqRDc8uUVfyuA eye, tyObject_Vec_8lp09c9aJ6sSqRDc8uUVfyuA center, tyObject_Vec_8lp09c9aJ6sSqRDc8uUVfyuA up) {
	tyObject_Mat_rRXFRTYKpgDJ5Kn1m7tKHA result;
	nimfr_("lookAt", "mat_transform.nim");
	memset((void*)(&result), 0, sizeof(result));
	nimln_(134, "mat_transform.nim");
	result = lookAtRH_iN7yJSIyVMaEk9c9azyZAbBQ_2(eye, center, up);
	popFrame();
	return result;
}

N_NIMCALL(tyObject_Mat_rRXFRTYKpgDJ5Kn1m7tKHA, perspectiveRH_HDtXEbqPG0MYpwNwpSvogw_2)(NF32 fovy, NF32 aspect, NF32 zNear, NF32 zFar) {
	tyObject_Mat_rRXFRTYKpgDJ5Kn1m7tKHA result;
	NF32 tanHalfFovy;
	nimfr_("perspectiveRH", "mat_transform.nim");
	memset((void*)(&result), 0, sizeof(result));
	nimln_(80, "mat_transform.nim");
	tanHalfFovy = tanf(((NF32)(fovy) / (NF32)(2.0000000000000000e+00)));
	nimln_(81, "mat_transform.nim");
	result = mat4_dnl08WbvO2CTNBskwbejJA(0.0);
	nimln_(82, "mat_transform.nim");
	X5BX5Deq__nmP8mqMhlxbqODgoT9cwyaQmat_transform((&result), ((NI) 0), ((NI) 0), ((NF32)(1.0000000000000000e+00) / (NF32)(((NF32)(aspect) * (NF32)(tanHalfFovy)))));
	nimln_(83, "mat_transform.nim");
	X5BX5Deq__nmP8mqMhlxbqODgoT9cwyaQmat_transform((&result), ((NI) 1), ((NI) 1), ((NF32)(1.0000000000000000e+00) / (NF32)(tanHalfFovy)));
	nimln_(84, "mat_transform.nim");
	X5BX5Deq__nmP8mqMhlxbqODgoT9cwyaQmat_transform((&result), ((NI) 2), ((NI) 3), -1.0000000000000000e+00);
	nimln_(86, "mat_transform.nim");
	X5BX5Deq__nmP8mqMhlxbqODgoT9cwyaQmat_transform((&result), ((NI) 2), ((NI) 2), ((NF32)(-(((NF32)(zFar) + (NF32)(zNear)))) / (NF32)(((NF32)(zFar) - (NF32)(zNear)))));
	nimln_(87, "mat_transform.nim");
	X5BX5Deq__nmP8mqMhlxbqODgoT9cwyaQmat_transform((&result), ((NI) 3), ((NI) 2), ((NF32)(-(((NF32)(((NF32)(2.0000000000000000e+00) * (NF32)(zFar))) * (NF32)(zNear)))) / (NF32)(((NF32)(zFar) - (NF32)(zNear)))));
	popFrame();
	return result;
}

N_NIMCALL(tyObject_Mat_rRXFRTYKpgDJ5Kn1m7tKHA, perspective_HDtXEbqPG0MYpwNwpSvogw)(NF32 fovy, NF32 aspect, NF32 zNear, NF32 zFar) {
	tyObject_Mat_rRXFRTYKpgDJ5Kn1m7tKHA result;
	nimfr_("perspective", "mat_transform.nim");
	memset((void*)(&result), 0, sizeof(result));
	nimln_(132, "mat_transform.nim");
	result = perspectiveRH_HDtXEbqPG0MYpwNwpSvogw_2(fovy, aspect, zNear, zFar);
	popFrame();
	return result;
}

static N_INLINE(void, X5BX5Deq__u2pJD47Sl0vMQJcmqqWTgQmat_transform)(tyObject_Mat_rRXFRTYKpgDJ5Kn1m7tKHA* v, NI ix, tyObject_Vec_nc2ATn3mNKEC36f9a1o6BCw c) {
	nimfr_("[]=", "mat.nim");
	if ((NU)(ix) > (NU)(3)) raiseIndexError();
	nimln_(34, "mat.nim");
	(*v).arr[(ix)- 0] = c;
	popFrame();
}

static N_INLINE(tyObject_Vec_nc2ATn3mNKEC36f9a1o6BCw, plus__XtiXXDU2o8buzgLSxx9aD0wmat_transform)(tyObject_Vec_nc2ATn3mNKEC36f9a1o6BCw v, tyObject_Vec_nc2ATn3mNKEC36f9a1o6BCw u) {
	tyObject_Vec_nc2ATn3mNKEC36f9a1o6BCw result;
	nimfr_("+", "vec.nim");
	memset((void*)(&result), 0, sizeof(result));
	{
		NI ii;
		NI i;
		ii = (NI)0;
		nimln_(3847, "system.nim");
		i = ((NI) 0);
		{
			nimln_(3848, "system.nim");
			while (1) {
				NI TM_s59aFOVpWWMmZYpGM3kpqFQ_4;
				if (!(i < ((NI) 4))) goto LA3;
				nimln_(3849, "system.nim");
				ii = i;
				if ((NU)(ii) > (NU)(3)) raiseIndexError();
				nimln_(109, "vec.nim");
				if ((NU)(ii) > (NU)(3)) raiseIndexError();
				if ((NU)(ii) > (NU)(3)) raiseIndexError();
				result.arr[(ii)- 0] = ((NF32)(v.arr[(ii)- 0]) + (NF32)(u.arr[(ii)- 0]));
				nimln_(3850, "system.nim");
				TM_s59aFOVpWWMmZYpGM3kpqFQ_4 = addInt(i, ((NI) 1));
				i = (NI)(TM_s59aFOVpWWMmZYpGM3kpqFQ_4);
			} LA3: ;
		}
	}
	popFrame();
	return result;
}

static N_INLINE(tyObject_Vec_nc2ATn3mNKEC36f9a1o6BCw, star__UkZJjcWPs0frWwxTW2fkWwmat_transform)(tyObject_Vec_nc2ATn3mNKEC36f9a1o6BCw v, NF32 val) {
	tyObject_Vec_nc2ATn3mNKEC36f9a1o6BCw result;
	nimfr_("*", "vec.nim");
	memset((void*)(&result), 0, sizeof(result));
	{
		NI ii;
		NI i;
		ii = (NI)0;
		nimln_(3847, "system.nim");
		i = ((NI) 0);
		{
			nimln_(3848, "system.nim");
			while (1) {
				NI TM_s59aFOVpWWMmZYpGM3kpqFQ_5;
				if (!(i < ((NI) 4))) goto LA3;
				nimln_(3849, "system.nim");
				ii = i;
				if ((NU)(ii) > (NU)(3)) raiseIndexError();
				nimln_(113, "vec.nim");
				if ((NU)(ii) > (NU)(3)) raiseIndexError();
				result.arr[(ii)- 0] = ((NF32)(v.arr[(ii)- 0]) * (NF32)(val));
				nimln_(3850, "system.nim");
				TM_s59aFOVpWWMmZYpGM3kpqFQ_5 = addInt(i, ((NI) 1));
				i = (NI)(TM_s59aFOVpWWMmZYpGM3kpqFQ_5);
			} LA3: ;
		}
	}
	popFrame();
	return result;
}

static N_INLINE(tyObject_Vec_nc2ATn3mNKEC36f9a1o6BCw, X5BX5D__eheLjiNw9aBDJp8bmeHHY9awquat)(tyObject_Mat_rRXFRTYKpgDJ5Kn1m7tKHA* v, NI ix) {
	tyObject_Vec_nc2ATn3mNKEC36f9a1o6BCw result;
	nimfr_("[]", "mat.nim");
	memset((void*)(&result), 0, sizeof(result));
	nimln_(36, "mat.nim");
	if ((NU)(ix) > (NU)(3)) raiseIndexError();
	result = (*v).arr[(ix)- 0];
	popFrame();
	return result;
}

N_NIMCALL(tyObject_Mat_rRXFRTYKpgDJ5Kn1m7tKHA, translate_e7jN59cKY7Uoow5L49bvCGdw)(tyObject_Mat_rRXFRTYKpgDJ5Kn1m7tKHA* m, tyObject_Vec_8lp09c9aJ6sSqRDc8uUVfyuA v) {
	tyObject_Mat_rRXFRTYKpgDJ5Kn1m7tKHA result;
	tyObject_Vec_nc2ATn3mNKEC36f9a1o6BCw T1_;
	NF32 T2_;
	tyObject_Vec_nc2ATn3mNKEC36f9a1o6BCw T3_;
	tyObject_Vec_nc2ATn3mNKEC36f9a1o6BCw T4_;
	NF32 T5_;
	tyObject_Vec_nc2ATn3mNKEC36f9a1o6BCw T6_;
	tyObject_Vec_nc2ATn3mNKEC36f9a1o6BCw T7_;
	tyObject_Vec_nc2ATn3mNKEC36f9a1o6BCw T8_;
	NF32 T9_;
	tyObject_Vec_nc2ATn3mNKEC36f9a1o6BCw T10_;
	tyObject_Vec_nc2ATn3mNKEC36f9a1o6BCw T11_;
	tyObject_Vec_nc2ATn3mNKEC36f9a1o6BCw T12_;
	tyObject_Vec_nc2ATn3mNKEC36f9a1o6BCw T13_;
	nimfr_("translate", "mat_transform.nim");
	memset((void*)(&result), 0, sizeof(result));
	nimln_(6, "mat_transform.nim");
	result = (*m);
	nimln_(7, "mat_transform.nim");
	T1_ = X5BX5D__eheLjiNw9aBDJp8bmeHHY9awquat(m, ((NI) 0));
	T2_ = (NF32)0;
	T2_ = X5BX5D__1laBXuXKeK8f9aVhwaW9bDCAquat(v, ((NI) 0));
	T3_ = star__UkZJjcWPs0frWwxTW2fkWwmat_transform(T1_, T2_);
	T4_ = X5BX5D__eheLjiNw9aBDJp8bmeHHY9awquat(m, ((NI) 1));
	T5_ = (NF32)0;
	T5_ = X5BX5D__1laBXuXKeK8f9aVhwaW9bDCAquat(v, ((NI) 1));
	T6_ = star__UkZJjcWPs0frWwxTW2fkWwmat_transform(T4_, T5_);
	T7_ = plus__XtiXXDU2o8buzgLSxx9aD0wmat_transform(T3_, T6_);
	T8_ = X5BX5D__eheLjiNw9aBDJp8bmeHHY9awquat(m, ((NI) 2));
	T9_ = (NF32)0;
	T9_ = X5BX5D__1laBXuXKeK8f9aVhwaW9bDCAquat(v, ((NI) 2));
	T10_ = star__UkZJjcWPs0frWwxTW2fkWwmat_transform(T8_, T9_);
	T11_ = plus__XtiXXDU2o8buzgLSxx9aD0wmat_transform(T7_, T10_);
	T12_ = X5BX5D__eheLjiNw9aBDJp8bmeHHY9awquat(m, ((NI) 3));
	T13_ = plus__XtiXXDU2o8buzgLSxx9aD0wmat_transform(T11_, T12_);
	X5BX5Deq__u2pJD47Sl0vMQJcmqqWTgQmat_transform((&result), ((NI) 3), T13_);
	popFrame();
	return result;
}

static N_INLINE(tyObject_Vec_8lp09c9aJ6sSqRDc8uUVfyuA, star__F5mbSxuiB9b1sFSsWVW2fPwmain)(NF32 val, tyObject_Vec_8lp09c9aJ6sSqRDc8uUVfyuA v) {
	tyObject_Vec_8lp09c9aJ6sSqRDc8uUVfyuA result;
	nimfr_("*", "vec.nim");
	memset((void*)(&result), 0, sizeof(result));
	{
		NI ii;
		NI i;
		ii = (NI)0;
		nimln_(3847, "system.nim");
		i = ((NI) 0);
		{
			nimln_(3848, "system.nim");
			while (1) {
				NI TM_s59aFOVpWWMmZYpGM3kpqFQ_6;
				if (!(i < ((NI) 3))) goto LA3;
				nimln_(3849, "system.nim");
				ii = i;
				if ((NU)(ii) > (NU)(2)) raiseIndexError();
				nimln_(117, "vec.nim");
				if ((NU)(ii) > (NU)(2)) raiseIndexError();
				result.arr[(ii)- 0] = ((NF32)(val) * (NF32)(v.arr[(ii)- 0]));
				nimln_(3850, "system.nim");
				TM_s59aFOVpWWMmZYpGM3kpqFQ_6 = addInt(i, ((NI) 1));
				i = (NI)(TM_s59aFOVpWWMmZYpGM3kpqFQ_6);
			} LA3: ;
		}
	}
	popFrame();
	return result;
}

static N_INLINE(NF32*, X5BX5D__KG7x1R5fw1Adi9c9bKzkEkeAmat_transform)(tyObject_Vec_8lp09c9aJ6sSqRDc8uUVfyuA* v, NI ix) {
	NF32* result;
	nimfr_("[]", "vec.nim");
	result = (NF32*)0;
	nimln_(151, "vec.nim");
	if ((NU)(ix) > (NU)(2)) raiseIndexError();
	result = (&(*v).arr[(ix)- 0]);
	popFrame();
	return result;
}

static N_INLINE(NF32*, X5BX5D__vrkiyjLlnepZ8jblNrp6Cgmat_transform)(tyObject_Mat_rRXFRTYKpgDJ5Kn1m7tKHA* v, NI ix, NI iy) {
	NF32* result;
	nimfr_("[]", "mat.nim");
	result = (NF32*)0;
	nimln_(45, "mat.nim");
	if ((NU)(ix) > (NU)(3)) raiseIndexError();
	if ((NU)(iy) > (NU)(3)) raiseIndexError();
	result = (&(*v).arr[(ix)- 0].arr[(iy)- 0]);
	popFrame();
	return result;
}

N_NIMCALL(tyObject_Mat_rRXFRTYKpgDJ5Kn1m7tKHA, rotate_wNoaEUlwghMGh9a3HFECfQA)(tyObject_Mat_rRXFRTYKpgDJ5Kn1m7tKHA* m, tyObject_Vec_8lp09c9aJ6sSqRDc8uUVfyuA axis, NF32 angle) {
	tyObject_Mat_rRXFRTYKpgDJ5Kn1m7tKHA result;
	NF32 a;
	NF32 c;
	NF32 s;
	tyObject_Vec_8lp09c9aJ6sSqRDc8uUVfyuA naxis;
	tyObject_Vec_8lp09c9aJ6sSqRDc8uUVfyuA temp;
	tyObject_Mat_rRXFRTYKpgDJ5Kn1m7tKHA Rotate;
	NF32* T1_;
	NF32 T2_;
	NF32* T3_;
	NF32 T4_;
	NF32 T5_;
	NF32* T6_;
	NF32 T7_;
	NF32 T8_;
	NF32* T9_;
	NF32 T10_;
	NF32 T11_;
	NF32* T12_;
	NF32 T13_;
	NF32* T14_;
	NF32 T15_;
	NF32 T16_;
	NF32* T17_;
	NF32 T18_;
	NF32 T19_;
	NF32* T20_;
	NF32 T21_;
	NF32 T22_;
	NF32* T23_;
	NF32 T24_;
	tyObject_Vec_nc2ATn3mNKEC36f9a1o6BCw T25_;
	NF32* T26_;
	tyObject_Vec_nc2ATn3mNKEC36f9a1o6BCw T27_;
	tyObject_Vec_nc2ATn3mNKEC36f9a1o6BCw T28_;
	NF32* T29_;
	tyObject_Vec_nc2ATn3mNKEC36f9a1o6BCw T30_;
	tyObject_Vec_nc2ATn3mNKEC36f9a1o6BCw T31_;
	tyObject_Vec_nc2ATn3mNKEC36f9a1o6BCw T32_;
	NF32* T33_;
	tyObject_Vec_nc2ATn3mNKEC36f9a1o6BCw T34_;
	tyObject_Vec_nc2ATn3mNKEC36f9a1o6BCw T35_;
	tyObject_Vec_nc2ATn3mNKEC36f9a1o6BCw T36_;
	NF32* T37_;
	tyObject_Vec_nc2ATn3mNKEC36f9a1o6BCw T38_;
	tyObject_Vec_nc2ATn3mNKEC36f9a1o6BCw T39_;
	NF32* T40_;
	tyObject_Vec_nc2ATn3mNKEC36f9a1o6BCw T41_;
	tyObject_Vec_nc2ATn3mNKEC36f9a1o6BCw T42_;
	tyObject_Vec_nc2ATn3mNKEC36f9a1o6BCw T43_;
	NF32* T44_;
	tyObject_Vec_nc2ATn3mNKEC36f9a1o6BCw T45_;
	tyObject_Vec_nc2ATn3mNKEC36f9a1o6BCw T46_;
	tyObject_Vec_nc2ATn3mNKEC36f9a1o6BCw T47_;
	NF32* T48_;
	tyObject_Vec_nc2ATn3mNKEC36f9a1o6BCw T49_;
	tyObject_Vec_nc2ATn3mNKEC36f9a1o6BCw T50_;
	NF32* T51_;
	tyObject_Vec_nc2ATn3mNKEC36f9a1o6BCw T52_;
	tyObject_Vec_nc2ATn3mNKEC36f9a1o6BCw T53_;
	tyObject_Vec_nc2ATn3mNKEC36f9a1o6BCw T54_;
	NF32* T55_;
	tyObject_Vec_nc2ATn3mNKEC36f9a1o6BCw T56_;
	tyObject_Vec_nc2ATn3mNKEC36f9a1o6BCw T57_;
	tyObject_Vec_nc2ATn3mNKEC36f9a1o6BCw T58_;
	nimfr_("rotate", "mat_transform.nim");
	memset((void*)(&result), 0, sizeof(result));
	nimln_(11, "mat_transform.nim");
	a = angle;
	nimln_(12, "mat_transform.nim");
	c = cosf(a);
	nimln_(13, "mat_transform.nim");
	s = sinf(a);
	nimln_(15, "mat_transform.nim");
	naxis = normalize_teBxubc60zLsP82FZ7wr1A(axis);
	nimln_(16, "mat_transform.nim");
	temp = star__F5mbSxuiB9b1sFSsWVW2fPwmain(((NF32)(1.0000000000000000e+00) - (NF32)(c)), naxis);
	nimln_(17, "mat_transform.nim");
	Rotate = mat4_dnl08WbvO2CTNBskwbejJA(0.0);
	nimln_(19, "mat_transform.nim");
	T1_ = (NF32*)0;
	T1_ = X5BX5D__KG7x1R5fw1Adi9c9bKzkEkeAmat_transform((&temp), ((NI) 0));
	T2_ = (NF32)0;
	T2_ = X5BX5D__1laBXuXKeK8f9aVhwaW9bDCAquat(axis, ((NI) 0));
	X5BX5Deq__nmP8mqMhlxbqODgoT9cwyaQmat_transform((&Rotate), ((NI) 0), ((NI) 0), ((NF32)(c) + (NF32)(((NF32)((*T1_)) * (NF32)(T2_)))));
	nimln_(20, "mat_transform.nim");
	T3_ = (NF32*)0;
	T3_ = X5BX5D__KG7x1R5fw1Adi9c9bKzkEkeAmat_transform((&temp), ((NI) 0));
	T4_ = (NF32)0;
	T4_ = X5BX5D__1laBXuXKeK8f9aVhwaW9bDCAquat(axis, ((NI) 1));
	T5_ = (NF32)0;
	T5_ = X5BX5D__1laBXuXKeK8f9aVhwaW9bDCAquat(axis, ((NI) 2));
	X5BX5Deq__nmP8mqMhlxbqODgoT9cwyaQmat_transform((&Rotate), ((NI) 0), ((NI) 1), ((NF32)(((NF32)(0.0) + (NF32)(((NF32)((*T3_)) * (NF32)(T4_))))) + (NF32)(((NF32)(s) * (NF32)(T5_)))));
	nimln_(21, "mat_transform.nim");
	T6_ = (NF32*)0;
	T6_ = X5BX5D__KG7x1R5fw1Adi9c9bKzkEkeAmat_transform((&temp), ((NI) 0));
	T7_ = (NF32)0;
	T7_ = X5BX5D__1laBXuXKeK8f9aVhwaW9bDCAquat(axis, ((NI) 2));
	T8_ = (NF32)0;
	T8_ = X5BX5D__1laBXuXKeK8f9aVhwaW9bDCAquat(axis, ((NI) 1));
	X5BX5Deq__nmP8mqMhlxbqODgoT9cwyaQmat_transform((&Rotate), ((NI) 0), ((NI) 2), ((NF32)(((NF32)(0.0) + (NF32)(((NF32)((*T6_)) * (NF32)(T7_))))) - (NF32)(((NF32)(s) * (NF32)(T8_)))));
	nimln_(23, "mat_transform.nim");
	T9_ = (NF32*)0;
	T9_ = X5BX5D__KG7x1R5fw1Adi9c9bKzkEkeAmat_transform((&temp), ((NI) 1));
	T10_ = (NF32)0;
	T10_ = X5BX5D__1laBXuXKeK8f9aVhwaW9bDCAquat(axis, ((NI) 0));
	T11_ = (NF32)0;
	T11_ = X5BX5D__1laBXuXKeK8f9aVhwaW9bDCAquat(axis, ((NI) 2));
	X5BX5Deq__nmP8mqMhlxbqODgoT9cwyaQmat_transform((&Rotate), ((NI) 1), ((NI) 0), ((NF32)(((NF32)(0.0) + (NF32)(((NF32)((*T9_)) * (NF32)(T10_))))) - (NF32)(((NF32)(s) * (NF32)(T11_)))));
	nimln_(24, "mat_transform.nim");
	T12_ = (NF32*)0;
	T12_ = X5BX5D__KG7x1R5fw1Adi9c9bKzkEkeAmat_transform((&temp), ((NI) 1));
	T13_ = (NF32)0;
	T13_ = X5BX5D__1laBXuXKeK8f9aVhwaW9bDCAquat(axis, ((NI) 1));
	X5BX5Deq__nmP8mqMhlxbqODgoT9cwyaQmat_transform((&Rotate), ((NI) 1), ((NI) 1), ((NF32)(c) + (NF32)(((NF32)((*T12_)) * (NF32)(T13_)))));
	nimln_(25, "mat_transform.nim");
	T14_ = (NF32*)0;
	T14_ = X5BX5D__KG7x1R5fw1Adi9c9bKzkEkeAmat_transform((&temp), ((NI) 1));
	T15_ = (NF32)0;
	T15_ = X5BX5D__1laBXuXKeK8f9aVhwaW9bDCAquat(axis, ((NI) 2));
	T16_ = (NF32)0;
	T16_ = X5BX5D__1laBXuXKeK8f9aVhwaW9bDCAquat(axis, ((NI) 0));
	X5BX5Deq__nmP8mqMhlxbqODgoT9cwyaQmat_transform((&Rotate), ((NI) 1), ((NI) 2), ((NF32)(((NF32)(0.0) + (NF32)(((NF32)((*T14_)) * (NF32)(T15_))))) + (NF32)(((NF32)(s) * (NF32)(T16_)))));
	nimln_(27, "mat_transform.nim");
	T17_ = (NF32*)0;
	T17_ = X5BX5D__KG7x1R5fw1Adi9c9bKzkEkeAmat_transform((&temp), ((NI) 2));
	T18_ = (NF32)0;
	T18_ = X5BX5D__1laBXuXKeK8f9aVhwaW9bDCAquat(axis, ((NI) 0));
	T19_ = (NF32)0;
	T19_ = X5BX5D__1laBXuXKeK8f9aVhwaW9bDCAquat(axis, ((NI) 1));
	X5BX5Deq__nmP8mqMhlxbqODgoT9cwyaQmat_transform((&Rotate), ((NI) 2), ((NI) 0), ((NF32)(((NF32)(0.0) + (NF32)(((NF32)((*T17_)) * (NF32)(T18_))))) + (NF32)(((NF32)(s) * (NF32)(T19_)))));
	nimln_(28, "mat_transform.nim");
	T20_ = (NF32*)0;
	T20_ = X5BX5D__KG7x1R5fw1Adi9c9bKzkEkeAmat_transform((&temp), ((NI) 2));
	T21_ = (NF32)0;
	T21_ = X5BX5D__1laBXuXKeK8f9aVhwaW9bDCAquat(axis, ((NI) 1));
	T22_ = (NF32)0;
	T22_ = X5BX5D__1laBXuXKeK8f9aVhwaW9bDCAquat(axis, ((NI) 0));
	X5BX5Deq__nmP8mqMhlxbqODgoT9cwyaQmat_transform((&Rotate), ((NI) 2), ((NI) 1), ((NF32)(((NF32)(0.0) + (NF32)(((NF32)((*T20_)) * (NF32)(T21_))))) - (NF32)(((NF32)(s) * (NF32)(T22_)))));
	nimln_(29, "mat_transform.nim");
	T23_ = (NF32*)0;
	T23_ = X5BX5D__KG7x1R5fw1Adi9c9bKzkEkeAmat_transform((&temp), ((NI) 2));
	T24_ = (NF32)0;
	T24_ = X5BX5D__1laBXuXKeK8f9aVhwaW9bDCAquat(axis, ((NI) 2));
	X5BX5Deq__nmP8mqMhlxbqODgoT9cwyaQmat_transform((&Rotate), ((NI) 2), ((NI) 2), ((NF32)(c) + (NF32)(((NF32)((*T23_)) * (NF32)(T24_)))));
	nimln_(31, "mat_transform.nim");
	result = mat4_dnl08WbvO2CTNBskwbejJA(0.0);
	nimln_(32, "mat_transform.nim");
	T25_ = X5BX5D__eheLjiNw9aBDJp8bmeHHY9awquat(m, ((NI) 0));
	T26_ = (NF32*)0;
	T26_ = X5BX5D__vrkiyjLlnepZ8jblNrp6Cgmat_transform((&Rotate), ((NI) 0), ((NI) 0));
	T27_ = star__UkZJjcWPs0frWwxTW2fkWwmat_transform(T25_, (*T26_));
	T28_ = X5BX5D__eheLjiNw9aBDJp8bmeHHY9awquat(m, ((NI) 1));
	T29_ = (NF32*)0;
	T29_ = X5BX5D__vrkiyjLlnepZ8jblNrp6Cgmat_transform((&Rotate), ((NI) 0), ((NI) 1));
	T30_ = star__UkZJjcWPs0frWwxTW2fkWwmat_transform(T28_, (*T29_));
	T31_ = plus__XtiXXDU2o8buzgLSxx9aD0wmat_transform(T27_, T30_);
	T32_ = X5BX5D__eheLjiNw9aBDJp8bmeHHY9awquat(m, ((NI) 2));
	T33_ = (NF32*)0;
	T33_ = X5BX5D__vrkiyjLlnepZ8jblNrp6Cgmat_transform((&Rotate), ((NI) 0), ((NI) 2));
	T34_ = star__UkZJjcWPs0frWwxTW2fkWwmat_transform(T32_, (*T33_));
	T35_ = plus__XtiXXDU2o8buzgLSxx9aD0wmat_transform(T31_, T34_);
	X5BX5Deq__u2pJD47Sl0vMQJcmqqWTgQmat_transform((&result), ((NI) 0), T35_);
	nimln_(33, "mat_transform.nim");
	T36_ = X5BX5D__eheLjiNw9aBDJp8bmeHHY9awquat(m, ((NI) 0));
	T37_ = (NF32*)0;
	T37_ = X5BX5D__vrkiyjLlnepZ8jblNrp6Cgmat_transform((&Rotate), ((NI) 1), ((NI) 0));
	T38_ = star__UkZJjcWPs0frWwxTW2fkWwmat_transform(T36_, (*T37_));
	T39_ = X5BX5D__eheLjiNw9aBDJp8bmeHHY9awquat(m, ((NI) 1));
	T40_ = (NF32*)0;
	T40_ = X5BX5D__vrkiyjLlnepZ8jblNrp6Cgmat_transform((&Rotate), ((NI) 1), ((NI) 1));
	T41_ = star__UkZJjcWPs0frWwxTW2fkWwmat_transform(T39_, (*T40_));
	T42_ = plus__XtiXXDU2o8buzgLSxx9aD0wmat_transform(T38_, T41_);
	T43_ = X5BX5D__eheLjiNw9aBDJp8bmeHHY9awquat(m, ((NI) 2));
	T44_ = (NF32*)0;
	T44_ = X5BX5D__vrkiyjLlnepZ8jblNrp6Cgmat_transform((&Rotate), ((NI) 1), ((NI) 2));
	T45_ = star__UkZJjcWPs0frWwxTW2fkWwmat_transform(T43_, (*T44_));
	T46_ = plus__XtiXXDU2o8buzgLSxx9aD0wmat_transform(T42_, T45_);
	X5BX5Deq__u2pJD47Sl0vMQJcmqqWTgQmat_transform((&result), ((NI) 1), T46_);
	nimln_(34, "mat_transform.nim");
	T47_ = X5BX5D__eheLjiNw9aBDJp8bmeHHY9awquat(m, ((NI) 0));
	T48_ = (NF32*)0;
	T48_ = X5BX5D__vrkiyjLlnepZ8jblNrp6Cgmat_transform((&Rotate), ((NI) 2), ((NI) 0));
	T49_ = star__UkZJjcWPs0frWwxTW2fkWwmat_transform(T47_, (*T48_));
	T50_ = X5BX5D__eheLjiNw9aBDJp8bmeHHY9awquat(m, ((NI) 1));
	T51_ = (NF32*)0;
	T51_ = X5BX5D__vrkiyjLlnepZ8jblNrp6Cgmat_transform((&Rotate), ((NI) 2), ((NI) 1));
	T52_ = star__UkZJjcWPs0frWwxTW2fkWwmat_transform(T50_, (*T51_));
	T53_ = plus__XtiXXDU2o8buzgLSxx9aD0wmat_transform(T49_, T52_);
	T54_ = X5BX5D__eheLjiNw9aBDJp8bmeHHY9awquat(m, ((NI) 2));
	T55_ = (NF32*)0;
	T55_ = X5BX5D__vrkiyjLlnepZ8jblNrp6Cgmat_transform((&Rotate), ((NI) 2), ((NI) 2));
	T56_ = star__UkZJjcWPs0frWwxTW2fkWwmat_transform(T54_, (*T55_));
	T57_ = plus__XtiXXDU2o8buzgLSxx9aD0wmat_transform(T53_, T56_);
	X5BX5Deq__u2pJD47Sl0vMQJcmqqWTgQmat_transform((&result), ((NI) 2), T57_);
	nimln_(35, "mat_transform.nim");
	T58_ = X5BX5D__eheLjiNw9aBDJp8bmeHHY9awquat(m, ((NI) 3));
	X5BX5Deq__u2pJD47Sl0vMQJcmqqWTgQmat_transform((&result), ((NI) 3), T58_);
	popFrame();
	return result;
}
NIM_EXTERNC N_NOINLINE(void, glm_mat_transformInit000)(void) {
	nimfr_("mat_transform", "mat_transform.nim");
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, glm_mat_transformDatInit000)(void) {
}

