/* Generated by Nim Compiler v0.17.2 */
/*   (c) 2017 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w  -I/home/vlad/Nim/lib -o /home/vlad/Sandbox/learnopengl/getting_started/nimcache/main.o /home/vlad/Sandbox/learnopengl/getting_started/nimcache/main.c */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#include <math.h>
#include <setjmp.h>
#include <stdio.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef powerpc
#undef unix
typedef struct tyObject_Vec_8lp09c9aJ6sSqRDc8uUVfyuA tyObject_Vec_8lp09c9aJ6sSqRDc8uUVfyuA;
typedef struct tySequence_4Xyxy0Om14N6K1l5e9bUPSQ tySequence_4Xyxy0Om14N6K1l5e9bUPSQ;
typedef struct TGenericSeq TGenericSeq;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct tySequence_sqJcVPBTp6ctoewzQQWnQw tySequence_sqJcVPBTp6ctoewzQQWnQw;
typedef struct tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g;
typedef struct tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w;
typedef struct tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ;
typedef struct tyObject_GcStack_7fytPA5bBsob6See21YMRA tyObject_GcStack_7fytPA5bBsob6See21YMRA;
typedef struct tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg;
typedef struct tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ;
typedef struct tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw;
typedef struct tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg;
typedef struct tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA;
typedef struct tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw;
typedef struct tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw;
typedef struct tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg;
typedef struct tyTuple_ujsjpB2O9cjj3uDHsXbnSzg tyTuple_ujsjpB2O9cjj3uDHsXbnSzg;
typedef struct tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg;
typedef struct tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ;
typedef struct tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg;
typedef struct NimStringDesc NimStringDesc;
typedef struct tyObject_Mat_rRXFRTYKpgDJ5Kn1m7tKHA tyObject_Mat_rRXFRTYKpgDJ5Kn1m7tKHA;
typedef struct tyObject_Vec_nc2ATn3mNKEC36f9a1o6BCw tyObject_Vec_nc2ATn3mNKEC36f9a1o6BCw;
typedef struct tySequence_6H5Oh5UUvVCLiakt9aTwtUQ tySequence_6H5Oh5UUvVCLiakt9aTwtUQ;
typedef struct tyObject_Event_Uzh9aP43ffUpM9aa6vZvNEug tyObject_Event_Uzh9aP43ffUpM9aa6vZvNEug;
typedef struct tyObject_WindowEventObj_d6XCemaEKzK59bxf1YxrwlA tyObject_WindowEventObj_d6XCemaEKzK59bxf1YxrwlA;
typedef struct tyObject_MouseWheelEventObj_XL6XlXxawDE0K4y7eEOqtg tyObject_MouseWheelEventObj_XL6XlXxawDE0K4y7eEOqtg;
typedef struct tyObject_MouseMotionEventObj_DqkoueH3SlQmFgclFBhMIA tyObject_MouseMotionEventObj_DqkoueH3SlQmFgclFBhMIA;
typedef struct tyObject_SDLException_9c6o5Sg4WWFW32kxEqehq7A tyObject_SDLException_9c6o5Sg4WWFW32kxEqehq7A;
typedef struct Exception Exception;
typedef struct RootObj RootObj;
typedef struct TSafePoint TSafePoint;
typedef struct tyObject_WindowPtrcolonObjectType__8bMU2xl1xmmMvYcskTOB4w tyObject_WindowPtrcolonObjectType__8bMU2xl1xmmMvYcskTOB4w;
typedef struct tyObject_GlContextPtrcolonObjectType__RFk4O9aogXphw3vfXrOizCg tyObject_GlContextPtrcolonObjectType__RFk4O9aogXphw3vfXrOizCg;
typedef struct tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w;
typedef struct tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ;
typedef NF32 tyArray_mXNbtvWKAiZn9bWV4uCjiKg[3];
struct tyObject_Vec_8lp09c9aJ6sSqRDc8uUVfyuA {
tyArray_mXNbtvWKAiZn9bWV4uCjiKg arr;
};
struct TGenericSeq {
NI len;
NI reserved;
};
typedef NU8 tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A;
typedef NU8 tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ;
typedef N_NIMCALL_PTR(void, tyProc_ojoeKfW4VYIm36I9cpDTQIg) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ) (void* p);
struct TNimType {
NI size;
tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A kind;
tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ flags;
TNimType* base;
TNimNode* node;
void* finalizer;
tyProc_ojoeKfW4VYIm36I9cpDTQIg marker;
tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ deepcopy;
};
typedef NU8 tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ;
struct TNimNode {
tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
typedef N_NIMCALL_PTR(void, tyProc_T4eqaYlFJYZUv9aG9b1TV0bQ) (void);
struct tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g {
NI refcount;
TNimType* typ;
};
struct tyObject_GcStack_7fytPA5bBsob6See21YMRA {
void* bottom;
};
struct tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w {
NI len;
NI cap;
tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g** d;
};
typedef tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* tyArray_SiRwrEKZdLgxqz9a9aoVBglg[512];
typedef tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw* tyArray_lh2A89ahMmYg9bCmpVaplLbA[256];
struct tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA {
tyArray_lh2A89ahMmYg9bCmpVaplLbA data;
};
typedef tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* tyArray_0aOLqZchNi8nWtMTi8ND8w[2];
struct tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw {
tyArray_0aOLqZchNi8nWtMTi8ND8w link;
NI key;
NI upperBound;
NI level;
};
struct tyTuple_ujsjpB2O9cjj3uDHsXbnSzg {
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* Field0;
NI Field1;
};
typedef tyTuple_ujsjpB2O9cjj3uDHsXbnSzg tyArray_LzOv2eCDGiceMKQstCLmhw[30];
struct tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg {
NI len;
tyArray_LzOv2eCDGiceMKQstCLmhw chunks;
tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg* next;
};
struct tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg {
NI minLargeObj;
NI maxLargeObj;
tyArray_SiRwrEKZdLgxqz9a9aoVBglg freeSmallChunks;
tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw* llmem;
NI currMem;
NI maxMem;
NI freeMem;
NI lastSize;
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* freeChunksList;
tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA chunkStarts;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* root;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* deleted;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* last;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* freeAvlNodes;
NIM_BOOL locked;
NIM_BOOL blockChunkSizeIncrease;
NI nextChunkSize;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw bottomData;
tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg heapLinks;
};
struct tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg {
NI stackScans;
NI cycleCollections;
NI maxThreshold;
NI maxStackSize;
NI maxStackCells;
NI cycleTableSize;
NI64 maxPause;
};
struct tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ {
NI counter;
NI max;
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg* head;
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg** data;
};
struct tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ {
tyObject_GcStack_7fytPA5bBsob6See21YMRA stack;
NI cycleThreshold;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w zct;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w decStack;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w tempStack;
NI recGcLock;
tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg region;
tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg stat;
tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ marked;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w additionalRoots;
};
struct NimStringDesc {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef NF32 tyArray_9aTCwbdg1cSQimdVd0OEKVw[4];
struct tyObject_Vec_nc2ATn3mNKEC36f9a1o6BCw {
tyArray_9aTCwbdg1cSQimdVd0OEKVw arr;
};
typedef tyObject_Vec_nc2ATn3mNKEC36f9a1o6BCw tyArray_Vwko69bN4O2Unwiy9crf9a1iQ[4];
struct tyObject_Mat_rRXFRTYKpgDJ5Kn1m7tKHA {
tyArray_Vwko69bN4O2Unwiy9crf9a1iQ arr;
};
typedef NI32 tyEnum_EventType_9ayvRjKFMoE6pV9bOp5OUI5w;
typedef NU8 tyArray_Y1pDC6KIrpu9aJMBN9aOQMhw[52];
struct tyObject_Event_Uzh9aP43ffUpM9aa6vZvNEug {
tyEnum_EventType_9ayvRjKFMoE6pV9bOp5OUI5w kind;
tyArray_Y1pDC6KIrpu9aJMBN9aOQMhw padding;
};
typedef N_CDECL_PTR(NU8*, tyProc_J1PDbNq7uKOgh20mdTxcDg) (NI* numkeys);
typedef NI32 tyEnum_Bool32_lrv4aZgVTmBUYdrYUkLMlg;
typedef N_CDECL_PTR(tyEnum_Bool32_lrv4aZgVTmBUYdrYUkLMlg, tyProc_b9aXpKFbsyZ0PIk3aYRVCAA) (tyObject_Event_Uzh9aP43ffUpM9aa6vZvNEug* event);
typedef NU8 tyEnum_WindowEventID_qlyMtQ19b0uMsXgE0vQ3Diw;
struct tyObject_WindowEventObj_d6XCemaEKzK59bxf1YxrwlA {
tyEnum_EventType_9ayvRjKFMoE6pV9bOp5OUI5w kind;
NU32 timestamp;
NU32 windowID;
tyEnum_WindowEventID_qlyMtQ19b0uMsXgE0vQ3Diw event;
NU8 pad1;
NU8 pad2;
NU8 pad3;
int data1;
int data2;
};
typedef NI32 tyEnum_MouseWheelDirection_ndQsZIBTF1N2Cb9c7mV9b2VQ;
struct tyObject_MouseWheelEventObj_XL6XlXxawDE0K4y7eEOqtg {
tyEnum_EventType_9ayvRjKFMoE6pV9bOp5OUI5w kind;
NU32 timestamp;
NU32 windowID;
NU32 which;
int x;
int y;
tyEnum_MouseWheelDirection_ndQsZIBTF1N2Cb9c7mV9b2VQ direction;
};
struct tyObject_MouseMotionEventObj_DqkoueH3SlQmFgclFBhMIA {
tyEnum_EventType_9ayvRjKFMoE6pV9bOp5OUI5w kind;
NU32 timestamp;
NU32 windowID;
NU32 which;
NU32 state;
NI32 x;
NI32 y;
NI32 xrel;
NI32 yrel;
};
typedef NI32 tyEnum_SDL_Return_8wc8or7UFANAtbisKJq7lw;
typedef N_CDECL_PTR(tyEnum_SDL_Return_8wc8or7UFANAtbisKJq7lw, tyProc_fvOXafK39cW5YZA9b9bzinu9cw) (int flags);
struct RootObj {
TNimType* m_type;
};
struct Exception {
  RootObj Sup;
Exception* parent;
NCSTRING name;
NimStringDesc* message;
NimStringDesc* trace;
Exception* up;
};
struct tyObject_SDLException_9c6o5Sg4WWFW32kxEqehq7A {
  Exception Sup;
};
typedef N_CDECL_PTR(NCSTRING, tyProc_09bvyvHFtWbkzL5AHgf0bKw) (void);
typedef long tyArray_TcvIiMAJvcwzNLsZkfnFnQ[25];
typedef struct {
N_NIMCALL_PTR(NIM_BOOL, ClP_0) (Exception* e, void* ClE_0);
void* ClE_0;
} tyProc_KeeAOYBd84Ofsw6Y7LizaQ;
struct TSafePoint {
TSafePoint* prev;
NI status;
jmp_buf context;
NIM_BOOL hasRaiseAction;
tyProc_KeeAOYBd84Ofsw6Y7LizaQ raiseAction;
};
typedef N_CDECL_PTR(NIM_BOOL, tyProc_CS9bxA1KE4RHFQ1vMCkCBmg) (NCSTRING name, NCSTRING value);
typedef N_CDECL_PTR(tyObject_WindowPtrcolonObjectType__8bMU2xl1xmmMvYcskTOB4w*, tyProc_1K9aSViCbSUpZMtRI9aw9a2Rg) (NCSTRING title, int x, int y, int w, int h, NU32 flags);
typedef N_CDECL_PTR(tyEnum_SDL_Return_8wc8or7UFANAtbisKJq7lw, tyProc_gHZVvnv6jeg9cI9brLoWECJw) (tyEnum_Bool32_lrv4aZgVTmBUYdrYUkLMlg enabled);
typedef N_CDECL_PTR(tyObject_GlContextPtrcolonObjectType__RFk4O9aogXphw3vfXrOizCg*, tyProc_A4TgaVzGkRyot8mrE1bD0g) (tyObject_WindowPtrcolonObjectType__8bMU2xl1xmmMvYcskTOB4w* window);
typedef NimStringDesc* tyArray_nHXaesL0DJZHyVS07ARPRA[1];
typedef N_CDECL_PTR(NU32, tyProc_ZBJ5GRli6YRWUmwPMxvXiw) (void);
typedef N_CDECL_PTR(void, tyProc_T629bWTbvDFNyKAaO0BGGIQ) (tyObject_WindowPtrcolonObjectType__8bMU2xl1xmmMvYcskTOB4w* window);
typedef N_CDECL_PTR(void, tyProc_ln4kdL5W9bbX4a1xl8nnVXQ) (void);
struct tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w {
NI prevSize;
NI size;
};
struct tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ {
  tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w Sup;
tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* next;
tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* prev;
tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ* freeList;
NI free;
NI acc;
NF data;
};
struct tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw {
NI size;
NI acc;
tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw* next;
};
struct tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg {
  tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w Sup;
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* next;
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* prev;
NF data;
};
typedef NI tyArray_9a8QARi5WsUggNU9bom7kzTQ[8];
struct tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw {
tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw* next;
NI key;
tyArray_9a8QARi5WsUggNU9bom7kzTQ bits;
};
struct tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg {
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg* next;
NI key;
tyArray_9a8QARi5WsUggNU9bom7kzTQ bits;
};
struct tyObject_WindowPtrcolonObjectType__8bMU2xl1xmmMvYcskTOB4w {
char dummy;
};
struct tyObject_GlContextPtrcolonObjectType__RFk4O9aogXphw3vfXrOizCg {
char dummy;
};
struct tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ {
tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ* next;
NI zeroField;
};
struct tySequence_4Xyxy0Om14N6K1l5e9bUPSQ {
  TGenericSeq Sup;
  NF32 data[SEQ_DECL_SIZE];
};
struct tySequence_sqJcVPBTp6ctoewzQQWnQw {
  TGenericSeq Sup;
  tyObject_Vec_8lp09c9aJ6sSqRDc8uUVfyuA data[SEQ_DECL_SIZE];
};
struct tySequence_6H5Oh5UUvVCLiakt9aTwtUQ {
  TGenericSeq Sup;
  NU8 data[SEQ_DECL_SIZE];
};
static N_INLINE(tyObject_Vec_8lp09c9aJ6sSqRDc8uUVfyuA, vec3_bV33b6rSAdvcVnmP1zcMwQmain)(NF32 x, NF32 y, NF32 z);
static N_INLINE(void, nimFrame)(TFrame* s);
N_NOINLINE(void, stackOverflow_II46IjNZztN9bmbxUD8dt8g)(void);
static N_INLINE(void, popFrame)(void);
N_NIMCALL(void, nimGCvisit)(void* d, NI op);
static N_NIMCALL(void, TM_V45tF8B8NBcxFcjfe7lhBw_2)(void);
N_NIMCALL(void, nimRegisterGlobalMarker)(tyProc_T4eqaYlFJYZUv9aG9b1TV0bQ markerProc);
N_NIMCALL(void, genericSeqAssign)(void* dest, void* src, TNimType* mt);
static N_NIMCALL(void, TM_V45tF8B8NBcxFcjfe7lhBw_5)(void);
static N_INLINE(void, nimGCunrefNoCycle)(void* p);
static N_INLINE(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem)(void* usr);
static N_INLINE(void, rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
N_NOINLINE(void, addZCT_fCDI7oO1NNVXXURtxSzsRw)(tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w* s, tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
N_NIMCALL(void*, newSeqRC1)(TNimType* typ, NI len);
static N_NIMCALL(void, TM_V45tF8B8NBcxFcjfe7lhBw_6)(void);
N_NIMCALL(NimStringDesc*, readFile_T9cm5LIRX2tKEH9aREBZ8A0w)(NimStringDesc* filename);
static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src);
static N_NIMCALL(void, TM_V45tF8B8NBcxFcjfe7lhBw_8)(void);
N_NIMCALL(tyObject_Mat_rRXFRTYKpgDJ5Kn1m7tKHA, mat4_dnl08WbvO2CTNBskwbejJA)(NF32 s);
static N_NIMCALL(void, TM_V45tF8B8NBcxFcjfe7lhBw_10)(void);
N_NIMCALL(void, nimLoadProcs0)(void);
static N_INLINE(void, minuseq__0Q9c9ccOr82GxaUx3qtv9aCoQmain)(NF32* x, NF32 y);
static N_INLINE(void, stareq__0Q9c9ccOr82GxaUx3qtv9aCoQ_2main)(NF32* x, NF32 y);
static N_INLINE(NF32, radians_PIZWPt9cdwGu0FvhY9aY3DEQmain)(NF32 v);
static N_INLINE(void, xeq__t9bqrIhlPr1G09bjH6Ew34uwmain)(tyObject_Vec_8lp09c9aJ6sSqRDc8uUVfyuA* v, NF32 val);
static N_INLINE(void, yeq__t9bqrIhlPr1G09bjH6Ew34uw_2main)(tyObject_Vec_8lp09c9aJ6sSqRDc8uUVfyuA* v, NF32 val);
static N_INLINE(void, zeq__t9bqrIhlPr1G09bjH6Ew34uw_3main)(tyObject_Vec_8lp09c9aJ6sSqRDc8uUVfyuA* v, NF32 val);
N_NIMCALL(tyObject_Vec_8lp09c9aJ6sSqRDc8uUVfyuA, normalize_teBxubc60zLsP82FZ7wr1A)(tyObject_Vec_8lp09c9aJ6sSqRDc8uUVfyuA v);
N_NIMCALL(NF32, length_dcL9bcEajdovXCT1zFH83bA)(tyObject_Vec_8lp09c9aJ6sSqRDc8uUVfyuA v);
static N_INLINE(tyObject_Vec_8lp09c9aJ6sSqRDc8uUVfyuA, star__8Na9bAqu9bNUfUwgkasftDlAvec)(tyObject_Vec_8lp09c9aJ6sSqRDc8uUVfyuA v, NF32 val);
N_NOINLINE(void, raiseIndexError)(void);
static N_INLINE(NI, addInt)(NI a, NI b);
N_NOINLINE(void, raiseOverflow)(void);
static N_INLINE(tyObject_Vec_8lp09c9aJ6sSqRDc8uUVfyuA, star__F5mbSxuiB9b1sFSsWVW2fPwmain)(NF32 val, tyObject_Vec_8lp09c9aJ6sSqRDc8uUVfyuA v);
N_NIMCALL(void, pluseq__jlZsuVE9at9buhm2i2ldI9aMA)(tyObject_Vec_8lp09c9aJ6sSqRDc8uUVfyuA* v, tyObject_Vec_8lp09c9aJ6sSqRDc8uUVfyuA u);
N_NIMCALL(void, minuseq__jlZsuVE9at9buhm2i2ldI9aMA_2)(tyObject_Vec_8lp09c9aJ6sSqRDc8uUVfyuA* v, tyObject_Vec_8lp09c9aJ6sSqRDc8uUVfyuA u);
N_NIMCALL(void, handleInput_9cku33tvANHm87a2gL2qUHQ)(void);
N_NIMCALL(NIM_BOOL, toBool_3fq5Y9cfgYx8q7J9ba6TTYbQ)(tyEnum_Bool32_lrv4aZgVTmBUYdrYUkLMlg some);
N_STDCALL(void, glViewport_yDKviL1Jxz9cvMulIoNt7vQ)(NI32 x, NI32 y, NI32 width, NI32 height);
static N_INLINE(void, pluseq__0Q9c9ccOr82GxaUx3qtv9aCoQquat)(NF32* x, NF32 y);
N_NIMCALL(tyObject_Vec_8lp09c9aJ6sSqRDc8uUVfyuA, cross_u30ZqBLCPuracR4Z1FBPOQ)(tyObject_Vec_8lp09c9aJ6sSqRDc8uUVfyuA v1, tyObject_Vec_8lp09c9aJ6sSqRDc8uUVfyuA v2);
static N_INLINE(tyObject_Vec_8lp09c9aJ6sSqRDc8uUVfyuA, plus__J7vWjOv59bjwwYcDHMIUtEgmain)(tyObject_Vec_8lp09c9aJ6sSqRDc8uUVfyuA v, tyObject_Vec_8lp09c9aJ6sSqRDc8uUVfyuA u);
N_NIMCALL(tyObject_Mat_rRXFRTYKpgDJ5Kn1m7tKHA, lookAt_iN7yJSIyVMaEk9c9azyZAbBQ)(tyObject_Vec_8lp09c9aJ6sSqRDc8uUVfyuA eye, tyObject_Vec_8lp09c9aJ6sSqRDc8uUVfyuA center, tyObject_Vec_8lp09c9aJ6sSqRDc8uUVfyuA up);
N_NIMCALL(tyObject_Mat_rRXFRTYKpgDJ5Kn1m7tKHA, lookAtRH_iN7yJSIyVMaEk9c9azyZAbBQ_2)(tyObject_Vec_8lp09c9aJ6sSqRDc8uUVfyuA eye, tyObject_Vec_8lp09c9aJ6sSqRDc8uUVfyuA center, tyObject_Vec_8lp09c9aJ6sSqRDc8uUVfyuA up);
static N_INLINE(tyObject_Vec_nc2ATn3mNKEC36f9a1o6BCw, vec4_ITdPzFAfjQ2t9c6sbu9bSPiQmat_transform)(tyObject_Vec_8lp09c9aJ6sSqRDc8uUVfyuA v, NF32 w);
static N_INLINE(NF32, x_Xbi8c1XUPkUTWFDNj5l5oQvec)(tyObject_Vec_8lp09c9aJ6sSqRDc8uUVfyuA v);
static N_INLINE(NF32, y_Xbi8c1XUPkUTWFDNj5l5oQ_2vec)(tyObject_Vec_8lp09c9aJ6sSqRDc8uUVfyuA v);
static N_INLINE(NF32, z_Xbi8c1XUPkUTWFDNj5l5oQ_3vec)(tyObject_Vec_8lp09c9aJ6sSqRDc8uUVfyuA v);
N_NIMCALL(void, row0eq__qL9cF9cOCu0hEf9crQaEJdlMg)(tyObject_Mat_rRXFRTYKpgDJ5Kn1m7tKHA* m, tyObject_Vec_nc2ATn3mNKEC36f9a1o6BCw value);
N_NIMCALL(void, row1eq__qL9cF9cOCu0hEf9crQaEJdlMg_2)(tyObject_Mat_rRXFRTYKpgDJ5Kn1m7tKHA* m, tyObject_Vec_nc2ATn3mNKEC36f9a1o6BCw value);
N_NIMCALL(tyObject_Vec_8lp09c9aJ6sSqRDc8uUVfyuA, minus__teBxubc60zLsP82FZ7wr1A_2)(tyObject_Vec_8lp09c9aJ6sSqRDc8uUVfyuA v);
N_NIMCALL(void, row2eq__qL9cF9cOCu0hEf9crQaEJdlMg_3)(tyObject_Mat_rRXFRTYKpgDJ5Kn1m7tKHA* m, tyObject_Vec_nc2ATn3mNKEC36f9a1o6BCw value);
static N_INLINE(tyObject_Vec_nc2ATn3mNKEC36f9a1o6BCw, vec4_AaOb1efTPrDJJ9aKeFHEEGwmat_transform)(NF32 x, NF32 y, NF32 z, NF32 w);
static N_INLINE(void, X5BX5Deq__nmP8mqMhlxbqODgoT9cwyaQmat_transform)(tyObject_Mat_rRXFRTYKpgDJ5Kn1m7tKHA* v, NI ix, NI iy, NF32 value);
N_NIMCALL(tyObject_Mat_rRXFRTYKpgDJ5Kn1m7tKHA, perspective_HDtXEbqPG0MYpwNwpSvogw)(NF32 fovy, NF32 aspect, NF32 zNear, NF32 zFar);
N_NIMCALL(tyObject_Mat_rRXFRTYKpgDJ5Kn1m7tKHA, perspectiveRH_HDtXEbqPG0MYpwNwpSvogw_2)(NF32 fovy, NF32 aspect, NF32 zNear, NF32 zFar);
N_NIMCALL(tyObject_Mat_rRXFRTYKpgDJ5Kn1m7tKHA, translate_e7jN59cKY7Uoow5L49bvCGdw)(tyObject_Mat_rRXFRTYKpgDJ5Kn1m7tKHA* m, tyObject_Vec_8lp09c9aJ6sSqRDc8uUVfyuA v);
static N_INLINE(tyObject_Vec_nc2ATn3mNKEC36f9a1o6BCw, star__UkZJjcWPs0frWwxTW2fkWwmat_transform)(tyObject_Vec_nc2ATn3mNKEC36f9a1o6BCw v, NF32 val);
static N_INLINE(tyObject_Vec_nc2ATn3mNKEC36f9a1o6BCw, plus__XtiXXDU2o8buzgLSxx9aD0wmat_transform)(tyObject_Vec_nc2ATn3mNKEC36f9a1o6BCw v, tyObject_Vec_nc2ATn3mNKEC36f9a1o6BCw u);
static N_INLINE(void, X5BX5Deq__u2pJD47Sl0vMQJcmqqWTgQmat_transform)(tyObject_Mat_rRXFRTYKpgDJ5Kn1m7tKHA* v, NI ix, tyObject_Vec_nc2ATn3mNKEC36f9a1o6BCw c);
N_NIMCALL(tyObject_Mat_rRXFRTYKpgDJ5Kn1m7tKHA, rotate_wNoaEUlwghMGh9a3HFECfQA)(tyObject_Mat_rRXFRTYKpgDJ5Kn1m7tKHA* m, tyObject_Vec_8lp09c9aJ6sSqRDc8uUVfyuA axis, NF32 angle);
static N_INLINE(NF32*, X5BX5D__KG7x1R5fw1Adi9c9bKzkEkeAmat_transform)(tyObject_Vec_8lp09c9aJ6sSqRDc8uUVfyuA* v, NI ix);
static N_INLINE(NF32*, X5BX5D__vrkiyjLlnepZ8jblNrp6Cgmat_transform)(tyObject_Mat_rRXFRTYKpgDJ5Kn1m7tKHA* v, NI ix, NI iy);
N_NIMCALL(NF32*, caddr_jgGzxJqqiHwFCU9bs1j3VOw)(tyObject_Mat_rRXFRTYKpgDJ5Kn1m7tKHA* m);
N_NIMCALL(void, main_9bQIWt54CdTNMd7hgR2Bl9cw)(void);
N_NIMCALL(NIM_BOOL, toBool_9bg9codirrpaPKZJuSwGJgEg)(tyEnum_SDL_Return_8wc8or7UFANAtbisKJq7lw some);
static N_NIMCALL(void, Marker_tyRef_T6kh3mQztDNb9bpesdVnfXw)(void* p, NI op);
N_NIMCALL(void*, newObj)(TNimType* typ, NI size);
static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src);
static N_INLINE(void, copyMem_E1xtACub5WcDa3vbrIXbwgsystem)(void* dest, void* source, NI size);
N_NIMCALL(NimStringDesc*, cstrToNimstr)(NCSTRING str);
N_NIMCALL(NimStringDesc*, rawNewString)(NI space);
static N_INLINE(void, asgnRef)(void** dest, void* src);
static N_INLINE(void, incRef_9cAA5YuQAAC3MVbnGeV86swsystem)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
static N_INLINE(void, decRef_MV4BBk6J1qu70IbBxwEn4wsystem)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
N_NIMCALL(void, raiseException)(Exception* e, NCSTRING ename);
static N_INLINE(void, pushSafePoint)(TSafePoint* s);
N_STDCALL(void, glEnable_XJ9c7bGCtPrHsj9bTWEfLf3A)(NU32 cap);
N_STDCALL(void, glGenVertexArrays_zvqeRPLD9c2eggqLYZ1r3Zg)(NI32 n, NU32* arrays);
N_STDCALL(void, glGenBuffers_B9ax9aWnWORHtXpch5OZqE6g)(NI32 n, NU32* buffers);
N_STDCALL(void, glBindVertexArray_DTfQaj6wT6HQ9c375GwSXmg)(NU32 array);
N_STDCALL(void, glBindBuffer_3rtrqe5eYHMVBLzlqTY63w)(NU32 target, NU32 buffer);
N_STDCALL(void, glBufferData_00Qu57bAXtAMX49bzkHe6aQ)(NU32 target, NI size, void* data, NU32 usage);
N_NIMCALL(NI, mulInt)(NI a, NI b);
N_STDCALL(NU32, glCreateShader_9aq2f5W9ciZ4xHTEIXreS9aDQ)(NU32 type_0);
N_NIMCALL(NCSTRING*, allocCStringArray_TEzwlF389aOWujK0ZU6Ck9bA)(NimStringDesc** a, NI aLen_0);
N_NIMCALL(NimStringDesc*, copyString)(NimStringDesc* src);
N_STDCALL(void, glShaderSource_ucehHh8g6pBlrLrZtUH9akw)(NU32 shader, NI32 count, NCSTRING* string, NI32* length);
N_STDCALL(void, glCompileShader_fdBHJ8ytQFLIIjstacvOaA)(NU32 shader);
N_NIMCALL(void, deallocCStringArray_C6iuca1Cowwvc7xYXRiSig)(NCSTRING* a);
N_STDCALL(void, glGenTextures_WoDI9cP6rS3Osykz9bfiBK6w)(NI32 n, NU32* textures);
N_STDCALL(void, glBindTexture_shJfrHWoymy1BbmsKpC7Xg)(NU32 target, NU32 texture);
N_STDCALL(void, glTexParameteri_MG1n9caM41cv9bizyIOehN3g)(NU32 target, NU32 pname, NI32 param);
N_NIMCALL(void, setFlipVerticallyOnLoad_ayevlb02tzQDH45TRoMJUg)(NIM_BOOL flip);
N_NIMCALL(tySequence_6H5Oh5UUvVCLiakt9aTwtUQ*, load_IpqKxisbLcaIMgU5vJeYeQ)(NimStringDesc* filename, NI* x, NI* y, NI* channels_in_file, NI desired_channels);
N_STDCALL(void, glTexImage2D_G7UzQ8ZECowVV7IoQf5rhg)(NU32 target, NI32 level, NI32 internalformat, NI32 width, NI32 height, NI32 border, NU32 format, NU32 type_0, void* pixels);
static N_INLINE(NI, chckRange)(NI i, NI a, NI b);
N_NOINLINE(void, raiseRangeError)(NI64 val);
N_STDCALL(void, glGenerateMipmap_vsbSjQU85hQuxcKnJrHing)(NU32 target);
N_STDCALL(void, glGetShaderiv_19a4e9byfNWwyylU9b0x0xEfA)(NU32 shader, NU32 pname, NI32* params);
N_NOCONV(void*, alloc_sVm4rDImKK2ZDdylByayiA)(NI size);
N_STDCALL(void, glGetShaderInfoLog_EU6IkXYJzNlAe9ccwJjIPaQ)(NU32 shader, NI32 bufSize, NI32* length, NCSTRING infoLog);
N_STDCALL(NU32, glCreateProgram_CuMrTzE9cxE5PqEhbYT8FwA)(void);
N_STDCALL(void, glAttachShader_6mrqhfMeT2OBe1X8Rfgbug)(NU32 program, NU32 shader);
N_STDCALL(void, glLinkProgram_bYudX2ps2dTBClLz2NbyzA)(NU32 program);
N_STDCALL(void, glDeleteShader_fdBHJ8ytQFLIIjstacvOaA_2)(NU32 shader);
N_STDCALL(void, glVertexAttribPointer_ARjPQ9cnPkJQtADdR9bd9a8Ww)(NU32 index, NI32 size, NU32 type_0, NIM_BOOL normalized, NI32 stride, void* pointer);
N_STDCALL(void, glEnableVertexAttribArray_PNXJR7G6JIj9ajx7Tvz9a1RA)(NU32 index);
N_STDCALL(void, glUseProgram_bYudX2ps2dTBClLz2NbyzA_2)(NU32 program);
N_STDCALL(void, glUniform1i_JXFx8pP9cft9ayhvOovLEZsg)(NI32 location, NI32 v0);
N_STDCALL(NI32, glGetUniformLocation_oSrxPmF9cyUrVZRg4cZ4LjQ)(NU32 program, NCSTRING name);
N_STDCALL(void, glActiveTexture_RDvtxKECOM9aYlw6XzAUstg)(NU32 texture);
N_STDCALL(void, glClearColor_f9bT9as4U8bxdkTUxJK60qlA)(NF32 red, NF32 green, NF32 blue, NF32 alpha);
N_STDCALL(void, glClear_ecjp09clx9c7t3uIhyfuACGQ)(NU32 mask);
static N_INLINE(NF, slash__fu0hCFNNw3xnGgcs2KwTWgsystem)(NI x, NI y);
N_STDCALL(void, glUniformMatrix4fv_m5jOdRl0iATiwQimgINdIw)(NI32 location, NI32 count, NIM_BOOL transpose, NF32* value);
N_STDCALL(void, glDrawArrays_Bw7cKcZtx9bAbZdj5Iw9af9ag)(NU32 mode, NI32 first, NI32 count);
static N_INLINE(void, popSafePoint)(void);
static N_INLINE(void, setFrame)(TFrame* s);
static N_INLINE(void, destroy_sFvfWODyHxg46OuBtGyU8Qmain)(tyObject_WindowPtrcolonObjectType__8bMU2xl1xmmMvYcskTOB4w* window);
N_NIMCALL(void, reraiseException)(void);
static N_INLINE(void, initStackBottomWith)(void* locals);
N_NOINLINE(void, setStackBottom)(void* theStackBottom);
NIM_EXTERNC N_NOINLINE(void, systemInit000)(void);
NIM_EXTERNC N_NOINLINE(void, systemDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_macrosInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_macrosDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_unsignedInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_unsignedDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_parseutilsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_parseutilsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_mathInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_mathDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_algorithmInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_algorithmDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_strutilsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_strutilsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, sdl2_sdl2Init000)(void);
NIM_EXTERNC N_NOINLINE(void, sdl2_sdl2DatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, glm_vecInit000)(void);
NIM_EXTERNC N_NOINLINE(void, glm_vecDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, glm_matInit000)(void);
NIM_EXTERNC N_NOINLINE(void, glm_matDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, glm_globalsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, glm_globalsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, glm_mat_transformInit000)(void);
NIM_EXTERNC N_NOINLINE(void, glm_mat_transformDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, glm_quatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, glm_quatDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, glm_glmInit000)(void);
NIM_EXTERNC N_NOINLINE(void, glm_glmDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_sequtilsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_sequtilsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, x11_xInit000)(void);
NIM_EXTERNC N_NOINLINE(void, x11_xDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, x11_xlibInit000)(void);
NIM_EXTERNC N_NOINLINE(void, x11_xlibDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, x11_keysymInit000)(void);
NIM_EXTERNC N_NOINLINE(void, x11_keysymDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, x11_xutilInit000)(void);
NIM_EXTERNC N_NOINLINE(void, x11_xutilDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_dynlibInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_dynlibDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, opengl_openglInit000)(void);
NIM_EXTERNC N_NOINLINE(void, opengl_openglDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stb_image_componentsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stb_image_componentsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stb_image_readInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stb_image_readDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, NimMainModule)(void);
NIM_EXTERNC N_NOINLINE(void, mainDatInit000)(void);
NIM_BOOL dontQuit_U2RdFTx0yT60ufXikLqvjw;
int screenWidth_BY9awPNjIKMlJgec2Lc40gA;
int screenHeight_Sc15UsbfHjCpDkYtTKu9c6g;
NF32 fov_qo9c6EXFjwbB4sA9aGSC9bfOw;
extern TFrame* framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
tySequence_4Xyxy0Om14N6K1l5e9bUPSQ* vertices_TyXguZdE3Wr74cs0jPlWcg;
extern TNimType NTI_4Xyxy0Om14N6K1l5e9bUPSQ_;
tySequence_sqJcVPBTp6ctoewzQQWnQw* cubePositions_DY5KGuUsgEns7QXZThW7qg;
extern TNimType NTI_sqJcVPBTp6ctoewzQQWnQw_;
extern tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ gch_IcYaEuuWivYAS86vFMTS3Q;
NimStringDesc* vertexShaderSource_0HW1jVrVxaTKp7MceNI5Mg;
extern TNimType NTI_77mFvmsOLKik79ci2hXkHEg_;
NimStringDesc* fragmentShaderSource_deoqY39coXrpzZUsWQG8mEQ;
NU32 vbo_Zpvb8an8dMtCjs2qGFpqpg;
NU32 vao_6tVwy69bGCeGIamJx2r1FYQ;
NU32 ebo_VKEKP64ypASZu1PtKEFGRA;
NU32 vertexShader_FuOrJgFL7KEMYZHzdhVnyg;
NU32 fragmentShader_XR3fpQTsJYtUxKp3GHfXwA;
NU32 shaderProgram_AW1xCBZy74f29b2WWcgMBdQ;
NU32 texture1_p62sE6mYeyuMbuSDveJxdg;
NU32 texture2_jmYdS6PsOWclkVENnQvhKg;
NI width_VBZaFCcrxqDUvUOtWhif4Q;
NI height_raGjlZe6guFLfeYQ9b9b1IDw;
NI channels_OArs5rg89biMeljS74vU2nA;
tySequence_6H5Oh5UUvVCLiakt9aTwtUQ* data_9ck7nDVO3sjueT11inBg3NQ;
extern TNimType NTI_6H5Oh5UUvVCLiakt9aTwtUQ_;
tyObject_Vec_8lp09c9aJ6sSqRDc8uUVfyuA cameraPos_7BlJD9c9b9br6uSqX5HznfcXQ;
tyObject_Vec_8lp09c9aJ6sSqRDc8uUVfyuA cameraFront_NZTsKo9atnVuihWmh3xW4sQ;
tyObject_Vec_8lp09c9aJ6sSqRDc8uUVfyuA cameraUp_H4JTsb9b78aAqrZrhxc0vqA;
tyObject_Mat_rRXFRTYKpgDJ5Kn1m7tKHA model_GLLYWwQIhVraS5S9cW3NRyQ;
NF32 deltaTime_3OQfSEgNwGCaiDv8pkr51Q;
NF32 lastFrame_ZbRny9aCpi9bNNaG2cGj1rew;
NF32 cameraSpeed_8YsPBxY6HPUxeqcG9bD4PKQ;
NF32 yaw_r59aOygQet7RSrZs3ZIUDRw;
NF32 pitch_eErl9bMOJlml9aygm25PvBcQ;
extern tyObject_Event_Uzh9aP43ffUpM9aa6vZvNEug defaultEvent_LbtYyFPe9bpTC9bKZ8rWJeKQ;
extern tyProc_J1PDbNq7uKOgh20mdTxcDg Dl_142464_;
extern tyProc_b9aXpKFbsyZ0PIk3aYRVCAA Dl_142605_;
extern tyProc_fvOXafK39cW5YZA9b9bzinu9cw Dl_141765_;
extern TNimType NTI_bAvOj2UcojKN87yAQLs0aw_;
TNimType NTI_9c6o5Sg4WWFW32kxEqehq7A_;
TNimType NTI_T6kh3mQztDNb9bpesdVnfXw_;
extern tyProc_09bvyvHFtWbkzL5AHgf0bKw Dl_142654_;
extern TSafePoint* excHandler_rqLlY5bs9atDw2OXYqJEn5g;
extern tyProc_CS9bxA1KE4RHFQ1vMCkCBmg Dl_143013_;
extern tyProc_1K9aSViCbSUpZMtRI9aw9a2Rg Dl_142356_;
extern tyProc_gHZVvnv6jeg9cI9brLoWECJw Dl_142531_;
extern tyProc_A4TgaVzGkRyot8mrE1bD0g Dl_142434_;
extern tyProc_ZBJ5GRli6YRWUmwPMxvXiw Dl_142397_;
extern tyProc_T629bWTbvDFNyKAaO0BGGIQ Dl_142456_;
extern tyProc_T629bWTbvDFNyKAaO0BGGIQ Dl_142388_;
extern tyProc_ln4kdL5W9bbX4a1xl8nnVXQ Dl_141777_;
NIM_CONST struct {
  TGenericSeq Sup;
  NF32 data[180];
} TM_V45tF8B8NBcxFcjfe7lhBw_4 = {{180, 180}, {-5.0000000000000000e-01,
-5.0000000000000000e-01,
-5.0000000000000000e-01,
0.0f,
0.0f,
5.0000000000000000e-01f,
-5.0000000000000000e-01,
-5.0000000000000000e-01,
1.0000000000000000e+00f,
0.0f,
5.0000000000000000e-01f,
5.0000000000000000e-01f,
-5.0000000000000000e-01,
1.0000000000000000e+00f,
1.0000000000000000e+00f,
5.0000000000000000e-01f,
5.0000000000000000e-01f,
-5.0000000000000000e-01,
1.0000000000000000e+00f,
1.0000000000000000e+00f,
-5.0000000000000000e-01,
5.0000000000000000e-01f,
-5.0000000000000000e-01,
0.0f,
1.0000000000000000e+00f,
-5.0000000000000000e-01,
-5.0000000000000000e-01,
-5.0000000000000000e-01,
0.0f,
0.0f,
-5.0000000000000000e-01,
-5.0000000000000000e-01,
5.0000000000000000e-01f,
0.0f,
0.0f,
5.0000000000000000e-01f,
-5.0000000000000000e-01,
5.0000000000000000e-01f,
1.0000000000000000e+00f,
0.0f,
5.0000000000000000e-01f,
5.0000000000000000e-01f,
5.0000000000000000e-01f,
1.0000000000000000e+00f,
1.0000000000000000e+00f,
5.0000000000000000e-01f,
5.0000000000000000e-01f,
5.0000000000000000e-01f,
1.0000000000000000e+00f,
1.0000000000000000e+00f,
-5.0000000000000000e-01,
5.0000000000000000e-01f,
5.0000000000000000e-01f,
0.0f,
1.0000000000000000e+00f,
-5.0000000000000000e-01,
-5.0000000000000000e-01,
5.0000000000000000e-01f,
0.0f,
0.0f,
-5.0000000000000000e-01,
5.0000000000000000e-01f,
5.0000000000000000e-01f,
1.0000000000000000e+00f,
0.0f,
-5.0000000000000000e-01,
5.0000000000000000e-01f,
-5.0000000000000000e-01,
1.0000000000000000e+00f,
1.0000000000000000e+00f,
-5.0000000000000000e-01,
-5.0000000000000000e-01,
-5.0000000000000000e-01,
0.0f,
1.0000000000000000e+00f,
-5.0000000000000000e-01,
-5.0000000000000000e-01,
-5.0000000000000000e-01,
0.0f,
1.0000000000000000e+00f,
-5.0000000000000000e-01,
-5.0000000000000000e-01,
5.0000000000000000e-01f,
0.0f,
0.0f,
-5.0000000000000000e-01,
5.0000000000000000e-01f,
5.0000000000000000e-01f,
1.0000000000000000e+00f,
0.0f,
5.0000000000000000e-01f,
5.0000000000000000e-01f,
5.0000000000000000e-01f,
1.0000000000000000e+00f,
0.0f,
5.0000000000000000e-01f,
5.0000000000000000e-01f,
-5.0000000000000000e-01,
1.0000000000000000e+00f,
1.0000000000000000e+00f,
5.0000000000000000e-01f,
-5.0000000000000000e-01,
-5.0000000000000000e-01,
0.0f,
1.0000000000000000e+00f,
5.0000000000000000e-01f,
-5.0000000000000000e-01,
-5.0000000000000000e-01,
0.0f,
1.0000000000000000e+00f,
5.0000000000000000e-01f,
-5.0000000000000000e-01,
5.0000000000000000e-01f,
0.0f,
0.0f,
5.0000000000000000e-01f,
5.0000000000000000e-01f,
5.0000000000000000e-01f,
1.0000000000000000e+00f,
0.0f,
-5.0000000000000000e-01,
-5.0000000000000000e-01,
-5.0000000000000000e-01,
0.0f,
1.0000000000000000e+00f,
5.0000000000000000e-01f,
-5.0000000000000000e-01,
-5.0000000000000000e-01,
1.0000000000000000e+00f,
1.0000000000000000e+00f,
5.0000000000000000e-01f,
-5.0000000000000000e-01,
5.0000000000000000e-01f,
1.0000000000000000e+00f,
0.0f,
5.0000000000000000e-01f,
-5.0000000000000000e-01,
5.0000000000000000e-01f,
1.0000000000000000e+00f,
0.0f,
-5.0000000000000000e-01,
-5.0000000000000000e-01,
5.0000000000000000e-01f,
0.0f,
0.0f,
-5.0000000000000000e-01,
-5.0000000000000000e-01,
-5.0000000000000000e-01,
0.0f,
1.0000000000000000e+00f,
-5.0000000000000000e-01,
5.0000000000000000e-01f,
-5.0000000000000000e-01,
0.0f,
1.0000000000000000e+00f,
5.0000000000000000e-01f,
5.0000000000000000e-01f,
-5.0000000000000000e-01,
1.0000000000000000e+00f,
1.0000000000000000e+00f,
5.0000000000000000e-01f,
5.0000000000000000e-01f,
5.0000000000000000e-01f,
1.0000000000000000e+00f,
0.0f,
5.0000000000000000e-01f,
5.0000000000000000e-01f,
5.0000000000000000e-01f,
1.0000000000000000e+00f,
0.0f,
-5.0000000000000000e-01,
5.0000000000000000e-01f,
5.0000000000000000e-01f,
0.0f,
0.0f,
-5.0000000000000000e-01,
5.0000000000000000e-01f,
-5.0000000000000000e-01,
0.0f,
1.0000000000000000e+00f}};
NIM_CONST tySequence_4Xyxy0Om14N6K1l5e9bUPSQ* TM_V45tF8B8NBcxFcjfe7lhBw_3 = ((tySequence_4Xyxy0Om14N6K1l5e9bUPSQ*)&TM_V45tF8B8NBcxFcjfe7lhBw_4);
STRING_LITERAL(TM_V45tF8B8NBcxFcjfe7lhBw_7, "vertex_shader.vert", 18);
STRING_LITERAL(TM_V45tF8B8NBcxFcjfe7lhBw_9, "fragment_shader.frag", 20);
STRING_LITERAL(TM_V45tF8B8NBcxFcjfe7lhBw_16, "SDL2 initialization failed", 26);
STRING_LITERAL(TM_V45tF8B8NBcxFcjfe7lhBw_17, ", SDL error: ", 13);
STRING_LITERAL(TM_V45tF8B8NBcxFcjfe7lhBw_19, "Linear texture filtering could not be enabled", 45);
STRING_LITERAL(TM_V45tF8B8NBcxFcjfe7lhBw_20, "Window could not be created", 27);
STRING_LITERAL(TM_V45tF8B8NBcxFcjfe7lhBw_23, "container.jpg", 13);
STRING_LITERAL(TM_V45tF8B8NBcxFcjfe7lhBw_24, "awesomeface.png", 15);

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI T1_;
	T1_ = (NI)0;
	{
		if (!(framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw == NIM_NIL)) goto LA4_;
		T1_ = ((NI) 0);
	}
	goto LA2_;
	LA4_: ;
	{
		T1_ = ((NI) ((NI16)((*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).calldepth + ((NI16) 1))));
	}
	LA2_: ;
	(*s).calldepth = ((NI16) (T1_));
	(*s).prev = framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9_;
		stackOverflow_II46IjNZztN9bmbxUD8dt8g();
	}
	LA9_: ;
}

static N_INLINE(void, popFrame)(void) {
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = (*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).prev;
}

static N_INLINE(tyObject_Vec_8lp09c9aJ6sSqRDc8uUVfyuA, vec3_bV33b6rSAdvcVnmP1zcMwQmain)(NF32 x, NF32 y, NF32 z) {
	tyObject_Vec_8lp09c9aJ6sSqRDc8uUVfyuA result;
	tyObject_Vec_8lp09c9aJ6sSqRDc8uUVfyuA T1_;
	nimfr_("vec3", "vec.nim");
	memset((void*)(&result), 0, sizeof(result));
	nimln_(166, "vec.nim");
	memset((void*)(&T1_), 0, sizeof(T1_));
	T1_.arr[0] = x;
	T1_.arr[1] = y;
	T1_.arr[2] = z;
	result = T1_;
	popFrame();
	return result;
}
static N_NIMCALL(void, TM_V45tF8B8NBcxFcjfe7lhBw_2)(void) {
	nimGCvisit((void*)vertices_TyXguZdE3Wr74cs0jPlWcg, 0);
}
static N_NIMCALL(void, TM_V45tF8B8NBcxFcjfe7lhBw_5)(void) {
	nimGCvisit((void*)cubePositions_DY5KGuUsgEns7QXZThW7qg, 0);
}

static N_INLINE(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem)(void* usr) {
	tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* result;
	nimfr_("usrToCell", "gc.nim");
	result = (tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*)0;
	nimln_(138, "gc.nim");
	result = ((tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*) ((NI)((NU64)(((NI) (usr))) - (NU64)(((NI)sizeof(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g))))));
	popFrame();
	return result;
}

static N_INLINE(void, rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c) {
	nimfr_("rtlAddZCT", "gc.nim");
	nimln_(216, "gc.nim");
	addZCT_fCDI7oO1NNVXXURtxSzsRw((&gch_IcYaEuuWivYAS86vFMTS3Q.zct), c);
	popFrame();
}

static N_INLINE(void, nimGCunrefNoCycle)(void* p) {
	tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c;
	nimfr_("nimGCunrefNoCycle", "gc.nim");
	nimln_(255, "gc.nim");
	c = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem(p);
	nimln_(257, "gc.nim");
	{
		(*c).refcount -= ((NI) 8);
		if (!((NU64)((*c).refcount) < (NU64)(((NI) 8)))) goto LA3_;
		nimln_(258, "gc.nim");
		rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system(c);
	}
	LA3_: ;
	popFrame();
}
static N_NIMCALL(void, TM_V45tF8B8NBcxFcjfe7lhBw_6)(void) {
	nimGCvisit((void*)vertexShaderSource_0HW1jVrVxaTKp7MceNI5Mg, 0);
}

static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src) {
	nimfr_("asgnRefNoCycle", "gc.nim");
	nimln_(276, "gc.nim");
	{
		tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c;
		nimln_(378, "system.nim");
		nimln_(276, "gc.nim");
		if (!!((src == NIM_NIL))) goto LA3_;
		nimln_(277, "gc.nim");
		c = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem(src);
		nimln_(278, "gc.nim");
		(*c).refcount += ((NI) 8);
	}
	LA3_: ;
	nimln_(279, "gc.nim");
	{
		tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c_2;
		nimln_(378, "system.nim");
		nimln_(279, "gc.nim");
		if (!!(((*dest) == NIM_NIL))) goto LA7_;
		nimln_(280, "gc.nim");
		c_2 = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem((*dest));
		nimln_(281, "gc.nim");
		{
			(*c_2).refcount -= ((NI) 8);
			if (!((NU64)((*c_2).refcount) < (NU64)(((NI) 8)))) goto LA11_;
			nimln_(282, "gc.nim");
			rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system(c_2);
		}
		LA11_: ;
	}
	LA7_: ;
	nimln_(283, "gc.nim");
	(*dest) = src;
	popFrame();
}
static N_NIMCALL(void, TM_V45tF8B8NBcxFcjfe7lhBw_8)(void) {
	nimGCvisit((void*)fragmentShaderSource_deoqY39coXrpzZUsWQG8mEQ, 0);
}
static N_NIMCALL(void, TM_V45tF8B8NBcxFcjfe7lhBw_10)(void) {
	nimGCvisit((void*)data_9ck7nDVO3sjueT11inBg3NQ, 0);
}

static N_INLINE(void, minuseq__0Q9c9ccOr82GxaUx3qtv9aCoQmain)(NF32* x, NF32 y) {
	nimfr_("-=", "system.nim");
	nimln_(3554, "system.nim");
	(*x) = ((NF32)((*x)) - (NF32)(y));
	popFrame();
}

static N_INLINE(void, stareq__0Q9c9ccOr82GxaUx3qtv9aCoQ_2main)(NF32* x, NF32 y) {
	nimfr_("*=", "system.nim");
	nimln_(3559, "system.nim");
	(*x) = ((NF32)((*x)) * (NF32)(y));
	popFrame();
}

static N_INLINE(NF32, radians_PIZWPt9cdwGu0FvhY9aY3DEQmain)(NF32 v) {
	NF32 result;
	nimfr_("radians", "vec.nim");
	result = (NF32)0;
	nimln_(318, "vec.nim");
	result = ((NF32) (((NF)(((NF)(((NF) (v))) * (NF)(3.1415926535897931e+00))) / (NF)(1.8000000000000000e+02))));
	popFrame();
	return result;
}

static N_INLINE(void, xeq__t9bqrIhlPr1G09bjH6Ew34uwmain)(tyObject_Vec_8lp09c9aJ6sSqRDc8uUVfyuA* v, NF32 val) {
	nimfr_("x=", "vec.nim");
	nimln_(261, "vec.nim");
	(*v).arr[(((NI) 0))- 0] = val;
	popFrame();
}

static N_INLINE(void, yeq__t9bqrIhlPr1G09bjH6Ew34uw_2main)(tyObject_Vec_8lp09c9aJ6sSqRDc8uUVfyuA* v, NF32 val) {
	nimfr_("y=", "vec.nim");
	nimln_(261, "vec.nim");
	(*v).arr[(((NI) 1))- 0] = val;
	popFrame();
}

static N_INLINE(void, zeq__t9bqrIhlPr1G09bjH6Ew34uw_3main)(tyObject_Vec_8lp09c9aJ6sSqRDc8uUVfyuA* v, NF32 val) {
	nimfr_("z=", "vec.nim");
	nimln_(261, "vec.nim");
	(*v).arr[(((NI) 2))- 0] = val;
	popFrame();
}

static N_INLINE(NI, addInt)(NI a, NI b) {
	NI result;
{	result = (NI)0;
	result = (NI)((NU64)(a) + (NU64)(b));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI) 0) <= (NI)(result ^ a));
		if (T3_) goto LA4_;
		T3_ = (((NI) 0) <= (NI)(result ^ b));
		LA4_: ;
		if (!T3_) goto LA5_;
		goto BeforeRet_;
	}
	LA5_: ;
	raiseOverflow();
	}BeforeRet_: ;
	return result;
}

static N_INLINE(tyObject_Vec_8lp09c9aJ6sSqRDc8uUVfyuA, star__8Na9bAqu9bNUfUwgkasftDlAvec)(tyObject_Vec_8lp09c9aJ6sSqRDc8uUVfyuA v, NF32 val) {
	tyObject_Vec_8lp09c9aJ6sSqRDc8uUVfyuA result;
	nimfr_("*", "vec.nim");
	memset((void*)(&result), 0, sizeof(result));
	{
		NI ii;
		NI i;
		ii = (NI)0;
		nimln_(3847, "system.nim");
		i = ((NI) 0);
		{
			nimln_(3848, "system.nim");
			while (1) {
				NI TM_V45tF8B8NBcxFcjfe7lhBw_11;
				if (!(i < ((NI) 3))) goto LA3;
				nimln_(3849, "system.nim");
				ii = i;
				if ((NU)(ii) > (NU)(2)) raiseIndexError();
				nimln_(113, "vec.nim");
				if ((NU)(ii) > (NU)(2)) raiseIndexError();
				result.arr[(ii)- 0] = ((NF32)(v.arr[(ii)- 0]) * (NF32)(val));
				nimln_(3850, "system.nim");
				TM_V45tF8B8NBcxFcjfe7lhBw_11 = addInt(i, ((NI) 1));
				i = (NI)(TM_V45tF8B8NBcxFcjfe7lhBw_11);
			} LA3: ;
		}
	}
	popFrame();
	return result;
}

static N_INLINE(tyObject_Vec_8lp09c9aJ6sSqRDc8uUVfyuA, star__F5mbSxuiB9b1sFSsWVW2fPwmain)(NF32 val, tyObject_Vec_8lp09c9aJ6sSqRDc8uUVfyuA v) {
	tyObject_Vec_8lp09c9aJ6sSqRDc8uUVfyuA result;
	nimfr_("*", "vec.nim");
	memset((void*)(&result), 0, sizeof(result));
	{
		NI ii;
		NI i;
		ii = (NI)0;
		nimln_(3847, "system.nim");
		i = ((NI) 0);
		{
			nimln_(3848, "system.nim");
			while (1) {
				NI TM_V45tF8B8NBcxFcjfe7lhBw_12;
				if (!(i < ((NI) 3))) goto LA3;
				nimln_(3849, "system.nim");
				ii = i;
				if ((NU)(ii) > (NU)(2)) raiseIndexError();
				nimln_(117, "vec.nim");
				if ((NU)(ii) > (NU)(2)) raiseIndexError();
				result.arr[(ii)- 0] = ((NF32)(val) * (NF32)(v.arr[(ii)- 0]));
				nimln_(3850, "system.nim");
				TM_V45tF8B8NBcxFcjfe7lhBw_12 = addInt(i, ((NI) 1));
				i = (NI)(TM_V45tF8B8NBcxFcjfe7lhBw_12);
			} LA3: ;
		}
	}
	popFrame();
	return result;
}

static N_INLINE(void, pluseq__0Q9c9ccOr82GxaUx3qtv9aCoQquat)(NF32* x, NF32 y) {
	nimfr_("+=", "system.nim");
	nimln_(3549, "system.nim");
	(*x) = ((NF32)((*x)) + (NF32)(y));
	popFrame();
}

N_NIMCALL(void, handleInput_9cku33tvANHm87a2gL2qUHQ)(void) {
	tyObject_Event_Uzh9aP43ffUpM9aa6vZvNEug evt;
	NU8* keyState;
	nimfr_("handleInput", "main.nim");
	nimln_(117, "main.nim");
	evt = defaultEvent_LbtYyFPe9bpTC9bKZ8rWJeKQ;
	nimln_(118, "main.nim");
	keyState = Dl_142464_(NIM_NIL);
	{
		nimln_(120, "main.nim");
		while (1) {
			tyEnum_Bool32_lrv4aZgVTmBUYdrYUkLMlg T3_;
			NIM_BOOL T4_;
			T3_ = (tyEnum_Bool32_lrv4aZgVTmBUYdrYUkLMlg)0;
			T3_ = Dl_142605_((&evt));
			T4_ = (NIM_BOOL)0;
			T4_ = toBool_3fq5Y9cfgYx8q7J9ba6TTYbQ(T3_);
			if (!T4_) goto LA2;
			nimln_(121, "main.nim");
			switch (evt.kind) {
			case ((tyEnum_EventType_9ayvRjKFMoE6pV9bOp5OUI5w) 256):
			{
				nimln_(123, "main.nim");
				dontQuit_U2RdFTx0yT60ufXikLqvjw = NIM_FALSE;
			}
			break;
			case ((tyEnum_EventType_9ayvRjKFMoE6pV9bOp5OUI5w) 512):
			{
				tyObject_WindowEventObj_d6XCemaEKzK59bxf1YxrwlA* windowEvent;
				nimln_(125, "main.nim");
				windowEvent = ((tyObject_WindowEventObj_d6XCemaEKzK59bxf1YxrwlA*) ((&evt)));
				nimln_(126, "main.nim");
				{
					if (!((*windowEvent).event == ((tyEnum_WindowEventID_qlyMtQ19b0uMsXgE0vQ3Diw) 5))) goto LA9_;
					nimln_(127, "main.nim");
					screenWidth_BY9awPNjIKMlJgec2Lc40gA = (*windowEvent).data1;
					nimln_(128, "main.nim");
					screenHeight_Sc15UsbfHjCpDkYtTKu9c6g = (*windowEvent).data2;
					nimln_(129, "main.nim");
					glViewport_yDKviL1Jxz9cvMulIoNt7vQ(((NI32) 0), ((NI32) 0), screenWidth_BY9awPNjIKMlJgec2Lc40gA, screenHeight_Sc15UsbfHjCpDkYtTKu9c6g);
				}
				LA9_: ;
			}
			break;
			case ((tyEnum_EventType_9ayvRjKFMoE6pV9bOp5OUI5w) 1027):
			{
				tyObject_MouseWheelEventObj_XL6XlXxawDE0K4y7eEOqtg* wheelEvent;
				nimln_(131, "main.nim");
				wheelEvent = ((tyObject_MouseWheelEventObj_XL6XlXxawDE0K4y7eEOqtg*) ((&evt)));
				nimln_(132, "main.nim");
				{
					NIM_BOOL T14_;
					T14_ = (NIM_BOOL)0;
					T14_ = (1.0000000000000000e+00f <= fov_qo9c6EXFjwbB4sA9aGSC9bfOw);
					if (!(T14_)) goto LA15_;
					T14_ = (fov_qo9c6EXFjwbB4sA9aGSC9bfOw <= 4.5000000000000000e+01f);
					LA15_: ;
					if (!T14_) goto LA16_;
					nimln_(133, "main.nim");
					minuseq__0Q9c9ccOr82GxaUx3qtv9aCoQmain((&fov_qo9c6EXFjwbB4sA9aGSC9bfOw), ((NF32) ((*wheelEvent).y)));
				}
				LA16_: ;
				nimln_(134, "main.nim");
				{
					if (!(fov_qo9c6EXFjwbB4sA9aGSC9bfOw <= 1.0000000000000000e+00f)) goto LA20_;
					nimln_(135, "main.nim");
					fov_qo9c6EXFjwbB4sA9aGSC9bfOw = 1.0000000000000000e+00f;
				}
				LA20_: ;
				nimln_(136, "main.nim");
				{
					if (!(4.5000000000000000e+01f <= fov_qo9c6EXFjwbB4sA9aGSC9bfOw)) goto LA24_;
					nimln_(137, "main.nim");
					fov_qo9c6EXFjwbB4sA9aGSC9bfOw = 4.5000000000000000e+01f;
				}
				LA24_: ;
			}
			break;
			case ((tyEnum_EventType_9ayvRjKFMoE6pV9bOp5OUI5w) 1024):
			{
				tyObject_MouseMotionEventObj_DqkoueH3SlQmFgclFBhMIA* motionEvent;
				NF32 xpos;
				NF32 ypos;
				NF32 sensitivity;
				tyObject_Vec_8lp09c9aJ6sSqRDc8uUVfyuA front;
				NF32 T35_;
				NF32 T36_;
				NF32 T37_;
				NF32 T38_;
				NF32 T39_;
				NF32 T40_;
				NF32 T41_;
				NF32 T42_;
				NF32 T43_;
				NF32 T44_;
				nimln_(141, "main.nim");
				motionEvent = ((tyObject_MouseMotionEventObj_DqkoueH3SlQmFgclFBhMIA*) ((&evt)));
				nimln_(142, "main.nim");
				xpos = ((NF32) ((*motionEvent).xrel));
				nimln_(143, "main.nim");
				ypos = ((NF32) ((*motionEvent).yrel));
				nimln_(146, "main.nim");
				sensitivity = 1.0000000000000001e-01f;
				nimln_(147, "main.nim");
				front = vec3_bV33b6rSAdvcVnmP1zcMwQmain(0.0f, 0.0f, 0.0f);
				nimln_(149, "main.nim");
				{
					if (!(8.9000000000000000e+01f < pitch_eErl9bMOJlml9aygm25PvBcQ)) goto LA29_;
					nimln_(150, "main.nim");
					pitch_eErl9bMOJlml9aygm25PvBcQ = 8.9000000000000000e+01f;
				}
				LA29_: ;
				nimln_(151, "main.nim");
				{
					if (!(pitch_eErl9bMOJlml9aygm25PvBcQ < -8.9000000000000000e+01)) goto LA33_;
					nimln_(152, "main.nim");
					pitch_eErl9bMOJlml9aygm25PvBcQ = -8.9000000000000000e+01;
				}
				LA33_: ;
				nimln_(154, "main.nim");
				stareq__0Q9c9ccOr82GxaUx3qtv9aCoQ_2main((&xpos), sensitivity);
				nimln_(155, "main.nim");
				stareq__0Q9c9ccOr82GxaUx3qtv9aCoQ_2main((&ypos), sensitivity);
				nimln_(156, "main.nim");
				pluseq__0Q9c9ccOr82GxaUx3qtv9aCoQquat((&yaw_r59aOygQet7RSrZs3ZIUDRw), xpos);
				nimln_(157, "main.nim");
				minuseq__0Q9c9ccOr82GxaUx3qtv9aCoQmain((&pitch_eErl9bMOJlml9aygm25PvBcQ), ypos);
				nimln_(159, "main.nim");
				T35_ = (NF32)0;
				T35_ = radians_PIZWPt9cdwGu0FvhY9aY3DEQmain(pitch_eErl9bMOJlml9aygm25PvBcQ);
				T36_ = (NF32)0;
				T36_ = cosf(T35_);
				T37_ = (NF32)0;
				T37_ = radians_PIZWPt9cdwGu0FvhY9aY3DEQmain(yaw_r59aOygQet7RSrZs3ZIUDRw);
				T38_ = (NF32)0;
				T38_ = cosf(T37_);
				xeq__t9bqrIhlPr1G09bjH6Ew34uwmain((&front), ((NF32)(T36_) * (NF32)(T38_)));
				nimln_(160, "main.nim");
				T39_ = (NF32)0;
				T39_ = radians_PIZWPt9cdwGu0FvhY9aY3DEQmain(pitch_eErl9bMOJlml9aygm25PvBcQ);
				T40_ = (NF32)0;
				T40_ = sinf(T39_);
				yeq__t9bqrIhlPr1G09bjH6Ew34uw_2main((&front), T40_);
				nimln_(161, "main.nim");
				T41_ = (NF32)0;
				T41_ = radians_PIZWPt9cdwGu0FvhY9aY3DEQmain(pitch_eErl9bMOJlml9aygm25PvBcQ);
				T42_ = (NF32)0;
				T42_ = cosf(T41_);
				T43_ = (NF32)0;
				T43_ = radians_PIZWPt9cdwGu0FvhY9aY3DEQmain(yaw_r59aOygQet7RSrZs3ZIUDRw);
				T44_ = (NF32)0;
				T44_ = sinf(T43_);
				zeq__t9bqrIhlPr1G09bjH6Ew34uw_3main((&front), ((NF32)(T42_) * (NF32)(T44_)));
				nimln_(162, "main.nim");
				cameraFront_NZTsKo9atnVuihWmh3xW4sQ = normalize_teBxubc60zLsP82FZ7wr1A(front);
			}
			break;
			default:
			{
			}
			break;
			}
		} LA2: ;
	}
	nimln_(168, "main.nim");
	{
		tyObject_Vec_8lp09c9aJ6sSqRDc8uUVfyuA T50_;
		nimln_(378, "system.nim");
		nimln_(168, "main.nim");
		if (!!((keyState[(((NU8) 82))- 0] == ((NI) 0)))) goto LA48_;
		nimln_(169, "main.nim");
		T50_ = star__F5mbSxuiB9b1sFSsWVW2fPwmain(cameraSpeed_8YsPBxY6HPUxeqcG9bD4PKQ, cameraFront_NZTsKo9atnVuihWmh3xW4sQ);
		pluseq__jlZsuVE9at9buhm2i2ldI9aMA((&cameraPos_7BlJD9c9b9br6uSqX5HznfcXQ), T50_);
	}
	LA48_: ;
	nimln_(170, "main.nim");
	{
		tyObject_Vec_8lp09c9aJ6sSqRDc8uUVfyuA T55_;
		nimln_(378, "system.nim");
		nimln_(170, "main.nim");
		if (!!((keyState[(((NU8) 81))- 0] == ((NI) 0)))) goto LA53_;
		nimln_(171, "main.nim");
		T55_ = star__F5mbSxuiB9b1sFSsWVW2fPwmain(cameraSpeed_8YsPBxY6HPUxeqcG9bD4PKQ, cameraFront_NZTsKo9atnVuihWmh3xW4sQ);
		minuseq__jlZsuVE9at9buhm2i2ldI9aMA_2((&cameraPos_7BlJD9c9b9br6uSqX5HznfcXQ), T55_);
	}
	LA53_: ;
	nimln_(172, "main.nim");
	{
		tyObject_Vec_8lp09c9aJ6sSqRDc8uUVfyuA T60_;
		tyObject_Vec_8lp09c9aJ6sSqRDc8uUVfyuA T61_;
		tyObject_Vec_8lp09c9aJ6sSqRDc8uUVfyuA T62_;
		nimln_(378, "system.nim");
		nimln_(172, "main.nim");
		if (!!((keyState[(((NU8) 80))- 0] == ((NI) 0)))) goto LA58_;
		nimln_(173, "main.nim");
		T60_ = cross_u30ZqBLCPuracR4Z1FBPOQ(cameraFront_NZTsKo9atnVuihWmh3xW4sQ, cameraUp_H4JTsb9b78aAqrZrhxc0vqA);
		T61_ = normalize_teBxubc60zLsP82FZ7wr1A(T60_);
		T62_ = star__8Na9bAqu9bNUfUwgkasftDlAvec(T61_, cameraSpeed_8YsPBxY6HPUxeqcG9bD4PKQ);
		minuseq__jlZsuVE9at9buhm2i2ldI9aMA_2((&cameraPos_7BlJD9c9b9br6uSqX5HznfcXQ), T62_);
	}
	LA58_: ;
	nimln_(174, "main.nim");
	{
		tyObject_Vec_8lp09c9aJ6sSqRDc8uUVfyuA T67_;
		tyObject_Vec_8lp09c9aJ6sSqRDc8uUVfyuA T68_;
		tyObject_Vec_8lp09c9aJ6sSqRDc8uUVfyuA T69_;
		nimln_(378, "system.nim");
		nimln_(174, "main.nim");
		if (!!((keyState[(((NU8) 79))- 0] == ((NI) 0)))) goto LA65_;
		nimln_(175, "main.nim");
		T67_ = cross_u30ZqBLCPuracR4Z1FBPOQ(cameraFront_NZTsKo9atnVuihWmh3xW4sQ, cameraUp_H4JTsb9b78aAqrZrhxc0vqA);
		T68_ = normalize_teBxubc60zLsP82FZ7wr1A(T67_);
		T69_ = star__8Na9bAqu9bNUfUwgkasftDlAvec(T68_, cameraSpeed_8YsPBxY6HPUxeqcG9bD4PKQ);
		pluseq__jlZsuVE9at9buhm2i2ldI9aMA((&cameraPos_7BlJD9c9b9br6uSqX5HznfcXQ), T69_);
	}
	LA65_: ;
	nimln_(177, "main.nim");
	{
		nimln_(378, "system.nim");
		nimln_(177, "main.nim");
		if (!!((keyState[(((NU8) 41))- 0] == ((NI) 0)))) goto LA72_;
	}
	LA72_: ;
	popFrame();
}

static N_INLINE(tyObject_Vec_8lp09c9aJ6sSqRDc8uUVfyuA, plus__J7vWjOv59bjwwYcDHMIUtEgmain)(tyObject_Vec_8lp09c9aJ6sSqRDc8uUVfyuA v, tyObject_Vec_8lp09c9aJ6sSqRDc8uUVfyuA u) {
	tyObject_Vec_8lp09c9aJ6sSqRDc8uUVfyuA result;
	nimfr_("+", "vec.nim");
	memset((void*)(&result), 0, sizeof(result));
	{
		NI ii;
		NI i;
		ii = (NI)0;
		nimln_(3847, "system.nim");
		i = ((NI) 0);
		{
			nimln_(3848, "system.nim");
			while (1) {
				NI TM_V45tF8B8NBcxFcjfe7lhBw_13;
				if (!(i < ((NI) 3))) goto LA3;
				nimln_(3849, "system.nim");
				ii = i;
				if ((NU)(ii) > (NU)(2)) raiseIndexError();
				nimln_(109, "vec.nim");
				if ((NU)(ii) > (NU)(2)) raiseIndexError();
				if ((NU)(ii) > (NU)(2)) raiseIndexError();
				result.arr[(ii)- 0] = ((NF32)(v.arr[(ii)- 0]) + (NF32)(u.arr[(ii)- 0]));
				nimln_(3850, "system.nim");
				TM_V45tF8B8NBcxFcjfe7lhBw_13 = addInt(i, ((NI) 1));
				i = (NI)(TM_V45tF8B8NBcxFcjfe7lhBw_13);
			} LA3: ;
		}
	}
	popFrame();
	return result;
}

static N_INLINE(NF32, x_Xbi8c1XUPkUTWFDNj5l5oQvec)(tyObject_Vec_8lp09c9aJ6sSqRDc8uUVfyuA v) {
	NF32 result;
	nimfr_("x", "vec.nim");
	result = (NF32)0;
	nimln_(255, "vec.nim");
	result = v.arr[(((NI) 0))- 0];
	popFrame();
	return result;
}

static N_INLINE(NF32, y_Xbi8c1XUPkUTWFDNj5l5oQ_2vec)(tyObject_Vec_8lp09c9aJ6sSqRDc8uUVfyuA v) {
	NF32 result;
	nimfr_("y", "vec.nim");
	result = (NF32)0;
	nimln_(255, "vec.nim");
	result = v.arr[(((NI) 1))- 0];
	popFrame();
	return result;
}

static N_INLINE(NF32, z_Xbi8c1XUPkUTWFDNj5l5oQ_3vec)(tyObject_Vec_8lp09c9aJ6sSqRDc8uUVfyuA v) {
	NF32 result;
	nimfr_("z", "vec.nim");
	result = (NF32)0;
	nimln_(255, "vec.nim");
	result = v.arr[(((NI) 2))- 0];
	popFrame();
	return result;
}

static N_INLINE(tyObject_Vec_nc2ATn3mNKEC36f9a1o6BCw, vec4_ITdPzFAfjQ2t9c6sbu9bSPiQmat_transform)(tyObject_Vec_8lp09c9aJ6sSqRDc8uUVfyuA v, NF32 w) {
	tyObject_Vec_nc2ATn3mNKEC36f9a1o6BCw result;
	tyObject_Vec_nc2ATn3mNKEC36f9a1o6BCw T1_;
	nimfr_("vec4", "vec.nim");
	memset((void*)(&result), 0, sizeof(result));
	nimln_(158, "vec.nim");
	memset((void*)(&T1_), 0, sizeof(T1_));
	T1_.arr[0] = x_Xbi8c1XUPkUTWFDNj5l5oQvec(v);
	T1_.arr[1] = y_Xbi8c1XUPkUTWFDNj5l5oQ_2vec(v);
	T1_.arr[2] = z_Xbi8c1XUPkUTWFDNj5l5oQ_3vec(v);
	T1_.arr[3] = w;
	result = T1_;
	popFrame();
	return result;
}

static N_INLINE(tyObject_Vec_nc2ATn3mNKEC36f9a1o6BCw, vec4_AaOb1efTPrDJJ9aKeFHEEGwmat_transform)(NF32 x, NF32 y, NF32 z, NF32 w) {
	tyObject_Vec_nc2ATn3mNKEC36f9a1o6BCw result;
	tyObject_Vec_nc2ATn3mNKEC36f9a1o6BCw T1_;
	nimfr_("vec4", "vec.nim");
	memset((void*)(&result), 0, sizeof(result));
	nimln_(157, "vec.nim");
	memset((void*)(&T1_), 0, sizeof(T1_));
	T1_.arr[0] = x;
	T1_.arr[1] = y;
	T1_.arr[2] = z;
	T1_.arr[3] = w;
	result = T1_;
	popFrame();
	return result;
}

static N_INLINE(void, X5BX5Deq__nmP8mqMhlxbqODgoT9cwyaQmat_transform)(tyObject_Mat_rRXFRTYKpgDJ5Kn1m7tKHA* v, NI ix, NI iy, NF32 value) {
	nimfr_("[]=", "mat.nim");
	if ((NU)(ix) > (NU)(3)) raiseIndexError();
	if ((NU)(iy) > (NU)(3)) raiseIndexError();
	nimln_(41, "mat.nim");
	(*v).arr[(ix)- 0].arr[(iy)- 0] = value;
	popFrame();
}

static N_INLINE(tyObject_Vec_nc2ATn3mNKEC36f9a1o6BCw, star__UkZJjcWPs0frWwxTW2fkWwmat_transform)(tyObject_Vec_nc2ATn3mNKEC36f9a1o6BCw v, NF32 val) {
	tyObject_Vec_nc2ATn3mNKEC36f9a1o6BCw result;
	nimfr_("*", "vec.nim");
	memset((void*)(&result), 0, sizeof(result));
	{
		NI ii;
		NI i;
		ii = (NI)0;
		nimln_(3847, "system.nim");
		i = ((NI) 0);
		{
			nimln_(3848, "system.nim");
			while (1) {
				NI TM_V45tF8B8NBcxFcjfe7lhBw_14;
				if (!(i < ((NI) 4))) goto LA3;
				nimln_(3849, "system.nim");
				ii = i;
				if ((NU)(ii) > (NU)(3)) raiseIndexError();
				nimln_(113, "vec.nim");
				if ((NU)(ii) > (NU)(3)) raiseIndexError();
				result.arr[(ii)- 0] = ((NF32)(v.arr[(ii)- 0]) * (NF32)(val));
				nimln_(3850, "system.nim");
				TM_V45tF8B8NBcxFcjfe7lhBw_14 = addInt(i, ((NI) 1));
				i = (NI)(TM_V45tF8B8NBcxFcjfe7lhBw_14);
			} LA3: ;
		}
	}
	popFrame();
	return result;
}

static N_INLINE(tyObject_Vec_nc2ATn3mNKEC36f9a1o6BCw, plus__XtiXXDU2o8buzgLSxx9aD0wmat_transform)(tyObject_Vec_nc2ATn3mNKEC36f9a1o6BCw v, tyObject_Vec_nc2ATn3mNKEC36f9a1o6BCw u) {
	tyObject_Vec_nc2ATn3mNKEC36f9a1o6BCw result;
	nimfr_("+", "vec.nim");
	memset((void*)(&result), 0, sizeof(result));
	{
		NI ii;
		NI i;
		ii = (NI)0;
		nimln_(3847, "system.nim");
		i = ((NI) 0);
		{
			nimln_(3848, "system.nim");
			while (1) {
				NI TM_V45tF8B8NBcxFcjfe7lhBw_15;
				if (!(i < ((NI) 4))) goto LA3;
				nimln_(3849, "system.nim");
				ii = i;
				if ((NU)(ii) > (NU)(3)) raiseIndexError();
				nimln_(109, "vec.nim");
				if ((NU)(ii) > (NU)(3)) raiseIndexError();
				if ((NU)(ii) > (NU)(3)) raiseIndexError();
				result.arr[(ii)- 0] = ((NF32)(v.arr[(ii)- 0]) + (NF32)(u.arr[(ii)- 0]));
				nimln_(3850, "system.nim");
				TM_V45tF8B8NBcxFcjfe7lhBw_15 = addInt(i, ((NI) 1));
				i = (NI)(TM_V45tF8B8NBcxFcjfe7lhBw_15);
			} LA3: ;
		}
	}
	popFrame();
	return result;
}

static N_INLINE(void, X5BX5Deq__u2pJD47Sl0vMQJcmqqWTgQmat_transform)(tyObject_Mat_rRXFRTYKpgDJ5Kn1m7tKHA* v, NI ix, tyObject_Vec_nc2ATn3mNKEC36f9a1o6BCw c) {
	nimfr_("[]=", "mat.nim");
	if ((NU)(ix) > (NU)(3)) raiseIndexError();
	nimln_(34, "mat.nim");
	(*v).arr[(ix)- 0] = c;
	popFrame();
}

static N_INLINE(NF32*, X5BX5D__KG7x1R5fw1Adi9c9bKzkEkeAmat_transform)(tyObject_Vec_8lp09c9aJ6sSqRDc8uUVfyuA* v, NI ix) {
	NF32* result;
	nimfr_("[]", "vec.nim");
	result = (NF32*)0;
	nimln_(151, "vec.nim");
	if ((NU)(ix) > (NU)(2)) raiseIndexError();
	result = (&(*v).arr[(ix)- 0]);
	popFrame();
	return result;
}

static N_INLINE(NF32*, X5BX5D__vrkiyjLlnepZ8jblNrp6Cgmat_transform)(tyObject_Mat_rRXFRTYKpgDJ5Kn1m7tKHA* v, NI ix, NI iy) {
	NF32* result;
	nimfr_("[]", "mat.nim");
	result = (NF32*)0;
	nimln_(45, "mat.nim");
	if ((NU)(ix) > (NU)(3)) raiseIndexError();
	if ((NU)(iy) > (NU)(3)) raiseIndexError();
	result = (&(*v).arr[(ix)- 0].arr[(iy)- 0]);
	popFrame();
	return result;
}
static N_NIMCALL(void, Marker_tyRef_T6kh3mQztDNb9bpesdVnfXw)(void* p, NI op) {
	tyObject_SDLException_9c6o5Sg4WWFW32kxEqehq7A* a;
	a = (tyObject_SDLException_9c6o5Sg4WWFW32kxEqehq7A*)p;
	nimGCvisit((void*)(*a).Sup.parent, op);
	nimGCvisit((void*)(*a).Sup.message, op);
	nimGCvisit((void*)(*a).Sup.trace, op);
	nimGCvisit((void*)(*a).Sup.up, op);
}

static N_INLINE(void, copyMem_E1xtACub5WcDa3vbrIXbwgsystem)(void* dest, void* source, NI size) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memcpy(dest, source, ((size_t) (size)));
}

static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src) {
	copyMem_E1xtACub5WcDa3vbrIXbwgsystem(((void*) ((&(*dest).data[((*dest).Sup.len)- 0]))), ((void*) ((*src).data)), ((NI) ((NI)((*src).Sup.len + ((NI) 1)))));
	(*dest).Sup.len += (*src).Sup.len;
}

static N_INLINE(void, incRef_9cAA5YuQAAC3MVbnGeV86swsystem)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c) {
	nimfr_("incRef", "gc.nim");
	nimln_(196, "gc.nim");
	(*c).refcount = (NI)((NU64)((*c).refcount) + (NU64)(((NI) 8)));
	popFrame();
}

static N_INLINE(void, decRef_MV4BBk6J1qu70IbBxwEn4wsystem)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c) {
	nimfr_("decRef", "gc.nim");
	nimln_(223, "gc.nim");
	{
		(*c).refcount -= ((NI) 8);
		if (!((NU64)((*c).refcount) < (NU64)(((NI) 8)))) goto LA3_;
		nimln_(224, "gc.nim");
		rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system(c);
	}
	LA3_: ;
	popFrame();
}

static N_INLINE(void, asgnRef)(void** dest, void* src) {
	nimfr_("asgnRef", "gc.nim");
	nimln_(269, "gc.nim");
	{
		tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* T5_;
		nimln_(378, "system.nim");
		nimln_(269, "gc.nim");
		if (!!((src == NIM_NIL))) goto LA3_;
		T5_ = (tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*)0;
		T5_ = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem(src);
		incRef_9cAA5YuQAAC3MVbnGeV86swsystem(T5_);
	}
	LA3_: ;
	nimln_(270, "gc.nim");
	{
		tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* T10_;
		nimln_(378, "system.nim");
		nimln_(270, "gc.nim");
		if (!!(((*dest) == NIM_NIL))) goto LA8_;
		T10_ = (tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*)0;
		T10_ = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem((*dest));
		decRef_MV4BBk6J1qu70IbBxwEn4wsystem(T10_);
	}
	LA8_: ;
	nimln_(271, "gc.nim");
	(*dest) = src;
	popFrame();
}

static N_INLINE(void, pushSafePoint)(TSafePoint* s) {
	(*s).hasRaiseAction = NIM_FALSE;
	(*s).prev = excHandler_rqLlY5bs9atDw2OXYqJEn5g;
	excHandler_rqLlY5bs9atDw2OXYqJEn5g = s;
}

static N_INLINE(NI, chckRange)(NI i, NI a, NI b) {
	NI result;
{	result = (NI)0;
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (a <= i);
		if (!(T3_)) goto LA4_;
		T3_ = (i <= b);
		LA4_: ;
		if (!T3_) goto LA5_;
		result = i;
		goto BeforeRet_;
	}
	goto LA1_;
	LA5_: ;
	{
		raiseRangeError(((NI64) (i)));
	}
	LA1_: ;
	}BeforeRet_: ;
	return result;
}

static N_INLINE(NF, slash__fu0hCFNNw3xnGgcs2KwTWgsystem)(NI x, NI y) {
	NF result;
	nimfr_("/", "system.nim");
	result = (NF)0;
	nimln_(3384, "system.nim");
	result = ((NF)(((double) (x))) / (NF)(((double) (y))));
	popFrame();
	return result;
}

static N_INLINE(void, popSafePoint)(void) {
	excHandler_rqLlY5bs9atDw2OXYqJEn5g = (*excHandler_rqLlY5bs9atDw2OXYqJEn5g).prev;
}

static N_INLINE(void, setFrame)(TFrame* s) {
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = s;
}

static N_INLINE(void, destroy_sFvfWODyHxg46OuBtGyU8Qmain)(tyObject_WindowPtrcolonObjectType__8bMU2xl1xmmMvYcskTOB4w* window) {
	nimfr_("destroy", "sdl2.nim");
	nimln_(1742, "sdl2.nim");
	Dl_142388_(window);
	popFrame();
}

N_NIMCALL(void, main_9bQIWt54CdTNMd7hgR2Bl9cw)(void) {
	TSafePoint TM_V45tF8B8NBcxFcjfe7lhBw_18;
	nimfr_("main", "main.nim");
	nimln_(195, "main.nim");
	{
		tyEnum_SDL_Return_8wc8or7UFANAtbisKJq7lw T3_;
		NIM_BOOL T4_;
		tyObject_SDLException_9c6o5Sg4WWFW32kxEqehq7A* e;
		NimStringDesc* T7_;
		NCSTRING T8_;
		NimStringDesc* T9_;
		T3_ = (tyEnum_SDL_Return_8wc8or7UFANAtbisKJq7lw)0;
		T3_ = Dl_141765_(((int) 65535));
		T4_ = (NIM_BOOL)0;
		T4_ = toBool_9bg9codirrpaPKZJuSwGJgEg(T3_);
		if (!!(T4_)) goto LA5_;
		e = (tyObject_SDLException_9c6o5Sg4WWFW32kxEqehq7A*)0;
		nimln_(2702, "system.nim");
		e = (tyObject_SDLException_9c6o5Sg4WWFW32kxEqehq7A*) newObj((&NTI_T6kh3mQztDNb9bpesdVnfXw_), sizeof(tyObject_SDLException_9c6o5Sg4WWFW32kxEqehq7A));
		(*e).Sup.Sup.m_type = (&NTI_9c6o5Sg4WWFW32kxEqehq7A_);
		nimln_(196, "main.nim");
		T7_ = (NimStringDesc*)0;
		nimln_(109, "main.nim");
		T8_ = (NCSTRING)0;
		T8_ = Dl_142654_();
		T9_ = (NimStringDesc*)0;
		T9_ = cstrToNimstr(T8_);
		T7_ = rawNewString(((NimStringDesc*) &TM_V45tF8B8NBcxFcjfe7lhBw_16)->Sup.len + T9_->Sup.len + 13);
appendString(T7_, ((NimStringDesc*) &TM_V45tF8B8NBcxFcjfe7lhBw_16));
appendString(T7_, ((NimStringDesc*) &TM_V45tF8B8NBcxFcjfe7lhBw_17));
appendString(T7_, T9_);
		asgnRefNoCycle((void**) (&(*e).Sup.message), T7_);
		nimln_(2697, "system.nim");
		asgnRef((void**) (&(*e).Sup.parent), NIM_NIL);
		nimln_(108, "main.nim");
		raiseException((Exception*)e, "SDLException");
	}
	LA5_: ;
	nimln_(200, "main.nim");
	pushSafePoint(&TM_V45tF8B8NBcxFcjfe7lhBw_18);
	TM_V45tF8B8NBcxFcjfe7lhBw_18.status = setjmp(TM_V45tF8B8NBcxFcjfe7lhBw_18.context);
	if (TM_V45tF8B8NBcxFcjfe7lhBw_18.status == 0) {
		tyObject_WindowPtrcolonObjectType__8bMU2xl1xmmMvYcskTOB4w* window;
		tyEnum_SDL_Return_8wc8or7UFANAtbisKJq7lw T26_;
		tyObject_GlContextPtrcolonObjectType__RFk4O9aogXphw3vfXrOizCg* T27_;
		TSafePoint TM_V45tF8B8NBcxFcjfe7lhBw_21;
		nimln_(202, "main.nim");
		{
			NIM_BOOL T13_;
			tyObject_SDLException_9c6o5Sg4WWFW32kxEqehq7A* volatile e_2;
			NimStringDesc* T16_;
			NCSTRING T17_;
			NimStringDesc* T18_;
			T13_ = (NIM_BOOL)0;
			T13_ = Dl_143013_("SDL_RENDER_SCALE_QUALITY", "2");
			if (!!(T13_)) goto LA14_;
			e_2 = (tyObject_SDLException_9c6o5Sg4WWFW32kxEqehq7A*)0;
			nimln_(2702, "system.nim");
			e_2 = (tyObject_SDLException_9c6o5Sg4WWFW32kxEqehq7A*) newObj((&NTI_T6kh3mQztDNb9bpesdVnfXw_), sizeof(tyObject_SDLException_9c6o5Sg4WWFW32kxEqehq7A));
			(*e_2).Sup.Sup.m_type = (&NTI_9c6o5Sg4WWFW32kxEqehq7A_);
			nimln_(203, "main.nim");
			T16_ = (NimStringDesc*)0;
			nimln_(109, "main.nim");
			T17_ = (NCSTRING)0;
			T17_ = Dl_142654_();
			T18_ = (NimStringDesc*)0;
			T18_ = cstrToNimstr(T17_);
			T16_ = rawNewString(((NimStringDesc*) &TM_V45tF8B8NBcxFcjfe7lhBw_19)->Sup.len + T18_->Sup.len + 13);
appendString(T16_, ((NimStringDesc*) &TM_V45tF8B8NBcxFcjfe7lhBw_19));
appendString(T16_, ((NimStringDesc*) &TM_V45tF8B8NBcxFcjfe7lhBw_17));
appendString(T16_, T18_);
			asgnRefNoCycle((void**) (&(*e_2).Sup.message), T16_);
			nimln_(2697, "system.nim");
			asgnRef((void**) (&(*e_2).Sup.parent), NIM_NIL);
			nimln_(108, "main.nim");
			raiseException((Exception*)e_2, "SDLException");
		}
		LA14_: ;
		nimln_(205, "main.nim");
		window = Dl_142356_("Our own 2D platformer", ((int) 805240832), ((int) 805240832), screenWidth_BY9awPNjIKMlJgec2Lc40gA, screenHeight_Sc15UsbfHjCpDkYtTKu9c6g, ((unsigned int) 34));
		nimln_(208, "main.nim");
		{
			tyObject_SDLException_9c6o5Sg4WWFW32kxEqehq7A* volatile e_3;
			NimStringDesc* T23_;
			NCSTRING T24_;
			NimStringDesc* T25_;
			if (!(window == 0)) goto LA21_;
			e_3 = (tyObject_SDLException_9c6o5Sg4WWFW32kxEqehq7A*)0;
			nimln_(2702, "system.nim");
			e_3 = (tyObject_SDLException_9c6o5Sg4WWFW32kxEqehq7A*) newObj((&NTI_T6kh3mQztDNb9bpesdVnfXw_), sizeof(tyObject_SDLException_9c6o5Sg4WWFW32kxEqehq7A));
			(*e_3).Sup.Sup.m_type = (&NTI_9c6o5Sg4WWFW32kxEqehq7A_);
			nimln_(208, "main.nim");
			T23_ = (NimStringDesc*)0;
			nimln_(109, "main.nim");
			T24_ = (NCSTRING)0;
			T24_ = Dl_142654_();
			T25_ = (NimStringDesc*)0;
			T25_ = cstrToNimstr(T24_);
			T23_ = rawNewString(((NimStringDesc*) &TM_V45tF8B8NBcxFcjfe7lhBw_20)->Sup.len + T25_->Sup.len + 13);
appendString(T23_, ((NimStringDesc*) &TM_V45tF8B8NBcxFcjfe7lhBw_20));
appendString(T23_, ((NimStringDesc*) &TM_V45tF8B8NBcxFcjfe7lhBw_17));
appendString(T23_, T25_);
			asgnRefNoCycle((void**) (&(*e_3).Sup.message), T23_);
			nimln_(2697, "system.nim");
			asgnRef((void**) (&(*e_3).Sup.parent), NIM_NIL);
			nimln_(108, "main.nim");
			raiseException((Exception*)e_3, "SDLException");
		}
		LA21_: ;
		nimln_(210, "main.nim");
		T26_ = (tyEnum_SDL_Return_8wc8or7UFANAtbisKJq7lw)0;
		T26_ = Dl_142531_(((tyEnum_Bool32_lrv4aZgVTmBUYdrYUkLMlg) 1));
		T26_;
		nimln_(211, "main.nim");
		T27_ = (tyObject_GlContextPtrcolonObjectType__RFk4O9aogXphw3vfXrOizCg*)0;
		T27_ = Dl_142434_(window);
		T27_;
		nimln_(212, "main.nim");
		pushSafePoint(&TM_V45tF8B8NBcxFcjfe7lhBw_21);
		TM_V45tF8B8NBcxFcjfe7lhBw_21.status = setjmp(TM_V45tF8B8NBcxFcjfe7lhBw_21.context);
		if (TM_V45tF8B8NBcxFcjfe7lhBw_21.status == 0) {
			NI T29_;
			NI TM_V45tF8B8NBcxFcjfe7lhBw_22;
			NCSTRING* cstr_vertex;
			tyArray_nHXaesL0DJZHyVS07ARPRA T30_;
			NCSTRING* cstr_fragment;
			tyArray_nHXaesL0DJZHyVS07ARPRA T31_;
			NI32 T44_;
			NI32 T45_;
			nimln_(215, "main.nim");
			glEnable_XJ9c7bGCtPrHsj9bTWEfLf3A(((NU32) 2929));
			nimln_(217, "main.nim");
			glGenVertexArrays_zvqeRPLD9c2eggqLYZ1r3Zg(((NI32) 1), (&vao_6tVwy69bGCeGIamJx2r1FYQ));
			nimln_(218, "main.nim");
			glGenBuffers_B9ax9aWnWORHtXpch5OZqE6g(((NI32) 1), (&vbo_Zpvb8an8dMtCjs2qGFpqpg));
			nimln_(221, "main.nim");
			glBindVertexArray_DTfQaj6wT6HQ9c375GwSXmg(vao_6tVwy69bGCeGIamJx2r1FYQ);
			nimln_(222, "main.nim");
			glBindBuffer_3rtrqe5eYHMVBLzlqTY63w(((NU32) 34962), vbo_Zpvb8an8dMtCjs2qGFpqpg);
			nimln_(224, "main.nim");
			T29_ = (vertices_TyXguZdE3Wr74cs0jPlWcg ? vertices_TyXguZdE3Wr74cs0jPlWcg->Sup.len : 0);
			TM_V45tF8B8NBcxFcjfe7lhBw_22 = mulInt(((NI) 4), T29_);
			if ((NU)(((NI) 0)) >= (NU)(vertices_TyXguZdE3Wr74cs0jPlWcg->Sup.len)) raiseIndexError();
			glBufferData_00Qu57bAXtAMX49bzkHe6aQ(((NU32) 34962), (NI)(TM_V45tF8B8NBcxFcjfe7lhBw_22), ((void*) ((&vertices_TyXguZdE3Wr74cs0jPlWcg->data[((NI) 0)]))), ((NU32) 35044));
			nimln_(227, "main.nim");
			vertexShader_FuOrJgFL7KEMYZHzdhVnyg = glCreateShader_9aq2f5W9ciZ4xHTEIXreS9aDQ(((NU32) 35633));
			nimln_(228, "main.nim");
			fragmentShader_XR3fpQTsJYtUxKp3GHfXwA = glCreateShader_9aq2f5W9ciZ4xHTEIXreS9aDQ(((NU32) 35632));
			nimln_(230, "main.nim");
			memset((void*)T30_, 0, sizeof(T30_));
			T30_[0] = copyString(vertexShaderSource_0HW1jVrVxaTKp7MceNI5Mg);
			cstr_vertex = allocCStringArray_TEzwlF389aOWujK0ZU6Ck9bA(T30_, 1);
			nimln_(231, "main.nim");
			memset((void*)T31_, 0, sizeof(T31_));
			T31_[0] = copyString(fragmentShaderSource_deoqY39coXrpzZUsWQG8mEQ);
			cstr_fragment = allocCStringArray_TEzwlF389aOWujK0ZU6Ck9bA(T31_, 1);
			nimln_(233, "main.nim");
			glShaderSource_ucehHh8g6pBlrLrZtUH9akw(vertexShader_FuOrJgFL7KEMYZHzdhVnyg, ((NI32) 1), cstr_vertex, NIM_NIL);
			nimln_(234, "main.nim");
			glShaderSource_ucehHh8g6pBlrLrZtUH9akw(fragmentShader_XR3fpQTsJYtUxKp3GHfXwA, ((NI32) 1), cstr_fragment, NIM_NIL);
			nimln_(235, "main.nim");
			glCompileShader_fdBHJ8ytQFLIIjstacvOaA(vertexShader_FuOrJgFL7KEMYZHzdhVnyg);
			nimln_(236, "main.nim");
			glCompileShader_fdBHJ8ytQFLIIjstacvOaA(fragmentShader_XR3fpQTsJYtUxKp3GHfXwA);
			nimln_(238, "main.nim");
			deallocCStringArray_C6iuca1Cowwvc7xYXRiSig(cstr_vertex);
			nimln_(239, "main.nim");
			deallocCStringArray_C6iuca1Cowwvc7xYXRiSig(cstr_fragment);
			nimln_(241, "main.nim");
			glGenTextures_WoDI9cP6rS3Osykz9bfiBK6w(((NI32) 1), (&texture1_p62sE6mYeyuMbuSDveJxdg));
			nimln_(242, "main.nim");
			glBindTexture_shJfrHWoymy1BbmsKpC7Xg(((NU32) 3553), texture1_p62sE6mYeyuMbuSDveJxdg);
			nimln_(244, "main.nim");
			glTexParameteri_MG1n9caM41cv9bizyIOehN3g(((NU32) 3553), ((NU32) 10242), ((NI32) 10497));
			nimln_(245, "main.nim");
			glTexParameteri_MG1n9caM41cv9bizyIOehN3g(((NU32) 3553), ((NU32) 10243), ((NI32) 10497));
			nimln_(246, "main.nim");
			glTexParameteri_MG1n9caM41cv9bizyIOehN3g(((NU32) 3553), ((NU32) 10241), ((NI32) 9987));
			nimln_(247, "main.nim");
			glTexParameteri_MG1n9caM41cv9bizyIOehN3g(((NU32) 3553), ((NU32) 10240), ((NI32) 9729));
			nimln_(249, "main.nim");
			setFlipVerticallyOnLoad_ayevlb02tzQDH45TRoMJUg(NIM_TRUE);
			nimln_(251, "main.nim");
			asgnRefNoCycle((void**) (&data_9ck7nDVO3sjueT11inBg3NQ), load_IpqKxisbLcaIMgU5vJeYeQ(((NimStringDesc*) &TM_V45tF8B8NBcxFcjfe7lhBw_23), (&width_VBZaFCcrxqDUvUOtWhif4Q), (&height_raGjlZe6guFLfeYQ9b9b1IDw), (&channels_OArs5rg89biMeljS74vU2nA), ((NI) 0)));
			nimln_(254, "main.nim");
			if ((NU)(((NI) 0)) >= (NU)(data_9ck7nDVO3sjueT11inBg3NQ->Sup.len)) raiseIndexError();
			glTexImage2D_G7UzQ8ZECowVV7IoQf5rhg(((NU32) 3553), ((NI32) 0), ((NI32) 6407), ((NI32)chckRange(width_VBZaFCcrxqDUvUOtWhif4Q, ((NI32) (-2147483647 -1)), ((NI32) 2147483647))), ((NI32)chckRange(height_raGjlZe6guFLfeYQ9b9b1IDw, ((NI32) (-2147483647 -1)), ((NI32) 2147483647))), ((NI32) 0), ((NU32) 6407), ((NU32) 5121), ((void*) ((&data_9ck7nDVO3sjueT11inBg3NQ->data[((NI) 0)]))));
			nimln_(255, "main.nim");
			glGenerateMipmap_vsbSjQU85hQuxcKnJrHing(((NU32) 3553));
			nimln_(257, "main.nim");
			asgnRefNoCycle((void**) (&data_9ck7nDVO3sjueT11inBg3NQ), load_IpqKxisbLcaIMgU5vJeYeQ(((NimStringDesc*) &TM_V45tF8B8NBcxFcjfe7lhBw_24), (&width_VBZaFCcrxqDUvUOtWhif4Q), (&height_raGjlZe6guFLfeYQ9b9b1IDw), (&channels_OArs5rg89biMeljS74vU2nA), ((NI) 0)));
			nimln_(260, "main.nim");
			glGenTextures_WoDI9cP6rS3Osykz9bfiBK6w(((NI32) 1), (&texture2_jmYdS6PsOWclkVENnQvhKg));
			nimln_(261, "main.nim");
			glBindTexture_shJfrHWoymy1BbmsKpC7Xg(((NU32) 3553), texture2_jmYdS6PsOWclkVENnQvhKg);
			nimln_(263, "main.nim");
			if ((NU)(((NI) 0)) >= (NU)(data_9ck7nDVO3sjueT11inBg3NQ->Sup.len)) raiseIndexError();
			glTexImage2D_G7UzQ8ZECowVV7IoQf5rhg(((NU32) 3553), ((NI32) 0), ((NI32) 6407), ((NI32)chckRange(width_VBZaFCcrxqDUvUOtWhif4Q, ((NI32) (-2147483647 -1)), ((NI32) 2147483647))), ((NI32)chckRange(height_raGjlZe6guFLfeYQ9b9b1IDw, ((NI32) (-2147483647 -1)), ((NI32) 2147483647))), ((NI32) 0), ((NU32) 6408), ((NU32) 5121), ((void*) ((&data_9ck7nDVO3sjueT11inBg3NQ->data[((NI) 0)]))));
			nimln_(265, "main.nim");
			glGenerateMipmap_vsbSjQU85hQuxcKnJrHing(((NU32) 3553));
			nimln_(267, "main.nim");
			{
				NI32 r;
				NI32 logLen;
				NIM_CHAR* logStr;
				void* T36_;
				NimStringDesc* T37_;
				r = (NI32)0;
				nimln_(182, "main.nim");
				glGetShaderiv_19a4e9byfNWwyylU9b0x0xEfA(vertexShader_FuOrJgFL7KEMYZHzdhVnyg, ((NU32) 35713), (&r));
				if (!!(((NIM_BOOL)chckRange(r, NIM_FALSE, NIM_TRUE)))) goto LA34_;
				nimln_(268, "main.nim");
				logLen = (NI32)0;
				nimln_(188, "main.nim");
				glGetShaderiv_19a4e9byfNWwyylU9b0x0xEfA(vertexShader_FuOrJgFL7KEMYZHzdhVnyg, ((NU32) 35716), (&logLen));
				nimln_(189, "main.nim");
				T36_ = (void*)0;
				T36_ = alloc_sVm4rDImKK2ZDdylByayiA(((NI)chckRange(logLen, ((NI) 0), ((NI) IL64(9223372036854775807)))));
				logStr = ((NIM_CHAR*) (T36_));
				nimln_(190, "main.nim");
				glGetShaderInfoLog_EU6IkXYJzNlAe9ccwJjIPaQ(vertexShader_FuOrJgFL7KEMYZHzdhVnyg, logLen, (&logLen), ((NCSTRING) (logStr)));
				nimln_(191, "main.nim");
				T37_ = (NimStringDesc*)0;
				T37_ = cstrToNimstr(((NCSTRING) (logStr)));
				printf("%s\012", T37_? (T37_)->data:"nil");
				fflush(stdout);
			}
			LA34_: ;
			nimln_(270, "main.nim");
			{
				NI32 r_2;
				NI32 logLen_2;
				NIM_CHAR* logStr_2;
				void* T42_;
				NimStringDesc* T43_;
				r_2 = (NI32)0;
				nimln_(182, "main.nim");
				glGetShaderiv_19a4e9byfNWwyylU9b0x0xEfA(fragmentShader_XR3fpQTsJYtUxKp3GHfXwA, ((NU32) 35713), (&r_2));
				if (!!(((NIM_BOOL)chckRange(r_2, NIM_FALSE, NIM_TRUE)))) goto LA40_;
				nimln_(271, "main.nim");
				logLen_2 = (NI32)0;
				nimln_(188, "main.nim");
				glGetShaderiv_19a4e9byfNWwyylU9b0x0xEfA(fragmentShader_XR3fpQTsJYtUxKp3GHfXwA, ((NU32) 35716), (&logLen_2));
				nimln_(189, "main.nim");
				T42_ = (void*)0;
				T42_ = alloc_sVm4rDImKK2ZDdylByayiA(((NI)chckRange(logLen_2, ((NI) 0), ((NI) IL64(9223372036854775807)))));
				logStr_2 = ((NIM_CHAR*) (T42_));
				nimln_(190, "main.nim");
				glGetShaderInfoLog_EU6IkXYJzNlAe9ccwJjIPaQ(fragmentShader_XR3fpQTsJYtUxKp3GHfXwA, logLen_2, (&logLen_2), ((NCSTRING) (logStr_2)));
				nimln_(191, "main.nim");
				T43_ = (NimStringDesc*)0;
				T43_ = cstrToNimstr(((NCSTRING) (logStr_2)));
				printf("%s\012", T43_? (T43_)->data:"nil");
				fflush(stdout);
			}
			LA40_: ;
			nimln_(274, "main.nim");
			shaderProgram_AW1xCBZy74f29b2WWcgMBdQ = glCreateProgram_CuMrTzE9cxE5PqEhbYT8FwA();
			nimln_(275, "main.nim");
			glAttachShader_6mrqhfMeT2OBe1X8Rfgbug(shaderProgram_AW1xCBZy74f29b2WWcgMBdQ, vertexShader_FuOrJgFL7KEMYZHzdhVnyg);
			nimln_(276, "main.nim");
			glAttachShader_6mrqhfMeT2OBe1X8Rfgbug(shaderProgram_AW1xCBZy74f29b2WWcgMBdQ, fragmentShader_XR3fpQTsJYtUxKp3GHfXwA);
			nimln_(277, "main.nim");
			glLinkProgram_bYudX2ps2dTBClLz2NbyzA(shaderProgram_AW1xCBZy74f29b2WWcgMBdQ);
			nimln_(278, "main.nim");
			glDeleteShader_fdBHJ8ytQFLIIjstacvOaA_2(vertexShader_FuOrJgFL7KEMYZHzdhVnyg);
			nimln_(279, "main.nim");
			glDeleteShader_fdBHJ8ytQFLIIjstacvOaA_2(fragmentShader_XR3fpQTsJYtUxKp3GHfXwA);
			nimln_(281, "main.nim");
			glVertexAttribPointer_ARjPQ9cnPkJQtADdR9bd9a8Ww(((NU32) 0), ((NI32) 3), ((NU32) 5126), NIM_FALSE, ((NI32) 20), ((void*) 0));
			nimln_(282, "main.nim");
			glEnableVertexAttribArray_PNXJR7G6JIj9ajx7Tvz9a1RA(((NU32) 0));
			nimln_(284, "main.nim");
			glVertexAttribPointer_ARjPQ9cnPkJQtADdR9bd9a8Ww(((NU32) 1), ((NI32) 2), ((NU32) 5126), NIM_FALSE, ((NI32) 20), ((void*) 12));
			nimln_(285, "main.nim");
			glEnableVertexAttribArray_PNXJR7G6JIj9ajx7Tvz9a1RA(((NU32) 1));
			nimln_(287, "main.nim");
			glUseProgram_bYudX2ps2dTBClLz2NbyzA_2(shaderProgram_AW1xCBZy74f29b2WWcgMBdQ);
			nimln_(288, "main.nim");
			T44_ = (NI32)0;
			T44_ = glGetUniformLocation_oSrxPmF9cyUrVZRg4cZ4LjQ(shaderProgram_AW1xCBZy74f29b2WWcgMBdQ, "texture1");
			glUniform1i_JXFx8pP9cft9ayhvOovLEZsg(T44_, ((NI32) 0));
			nimln_(289, "main.nim");
			T45_ = (NI32)0;
			T45_ = glGetUniformLocation_oSrxPmF9cyUrVZRg4cZ4LjQ(shaderProgram_AW1xCBZy74f29b2WWcgMBdQ, "texture2");
			glUniform1i_JXFx8pP9cft9ayhvOovLEZsg(T45_, ((NI32) 1));
			nimln_(292, "main.nim");
			glActiveTexture_RDvtxKECOM9aYlw6XzAUstg(((NU32) 33984));
			nimln_(293, "main.nim");
			glBindTexture_shJfrHWoymy1BbmsKpC7Xg(((NU32) 3553), texture1_p62sE6mYeyuMbuSDveJxdg);
			nimln_(295, "main.nim");
			glActiveTexture_RDvtxKECOM9aYlw6XzAUstg(((NU32) 33985));
			nimln_(296, "main.nim");
			glBindTexture_shJfrHWoymy1BbmsKpC7Xg(((NU32) 3553), texture2_jmYdS6PsOWclkVENnQvhKg);
			{
				nimln_(300, "main.nim");
				while (1) {
					NF currentFrame;
					NU32 T48_;
					tyObject_Mat_rRXFRTYKpgDJ5Kn1m7tKHA view;
					tyObject_Vec_8lp09c9aJ6sSqRDc8uUVfyuA T49_;
					tyObject_Mat_rRXFRTYKpgDJ5Kn1m7tKHA projection;
					NF32 T50_;
					NF T51_;
					NI32 T61_;
					NF32* T62_;
					NI32 T63_;
					NF32* T64_;
					if (!dontQuit_U2RdFTx0yT60ufXikLqvjw) goto LA47;
					nimln_(302, "main.nim");
					handleInput_9cku33tvANHm87a2gL2qUHQ();
					nimln_(304, "main.nim");
					glClearColor_f9bT9as4U8bxdkTUxJK60qlA(2.0000000000000001e-01, 2.9999999999999999e-01, 2.9999999999999999e-01, 1.0000000000000000e+00);
					nimln_(305, "main.nim");
					glClear_ecjp09clx9c7t3uIhyfuACGQ(((NU32) 16640));
					nimln_(306, "main.nim");
					glBindVertexArray_DTfQaj6wT6HQ9c375GwSXmg(vao_6tVwy69bGCeGIamJx2r1FYQ);
					nimln_(307, "main.nim");
					T48_ = (NU32)0;
					T48_ = Dl_142397_();
					currentFrame = ((NF) (T48_));
					nimln_(308, "main.nim");
					deltaTime_3OQfSEgNwGCaiDv8pkr51Q = ((NF32) (((NF)(currentFrame) - (NF)(((NF) (lastFrame_ZbRny9aCpi9bNNaG2cGj1rew))))));
					nimln_(309, "main.nim");
					lastFrame_ZbRny9aCpi9bNNaG2cGj1rew = ((NF32) (currentFrame));
					nimln_(310, "main.nim");
					cameraSpeed_8YsPBxY6HPUxeqcG9bD4PKQ = ((NF32)(2.0000000000000000e-02f) * (NF32)(deltaTime_3OQfSEgNwGCaiDv8pkr51Q));
					nimln_(313, "main.nim");
					T49_ = plus__J7vWjOv59bjwwYcDHMIUtEgmain(cameraPos_7BlJD9c9b9br6uSqX5HznfcXQ, cameraFront_NZTsKo9atnVuihWmh3xW4sQ);
					view = lookAt_iN7yJSIyVMaEk9c9azyZAbBQ(cameraPos_7BlJD9c9b9br6uSqX5HznfcXQ, T49_, cameraUp_H4JTsb9b78aAqrZrhxc0vqA);
					nimln_(314, "main.nim");
					T50_ = (NF32)0;
					T50_ = radians_PIZWPt9cdwGu0FvhY9aY3DEQmain(fov_qo9c6EXFjwbB4sA9aGSC9bfOw);
					T51_ = (NF)0;
					T51_ = slash__fu0hCFNNw3xnGgcs2KwTWgsystem(((NI) (screenWidth_BY9awPNjIKMlJgec2Lc40gA)), ((NI) (screenHeight_Sc15UsbfHjCpDkYtTKu9c6g)));
					projection = perspective_HDtXEbqPG0MYpwNwpSvogw(T50_, ((NF32) (T51_)), 1.0000000000000001e-01f, 1.0000000000000000e+02f);
					{
						NI i;
						tyObject_Vec_8lp09c9aJ6sSqRDc8uUVfyuA position;
						NI volatile i_2;
						i = (NI)0;
						memset((void*)(&position), 0, sizeof(position));
						nimln_(2178, "system.nim");
						i_2 = ((NI) 0);
						{
							nimln_(2179, "system.nim");
							while (1) {
								NI T55_;
								NF angle;
								NU32 T56_;
								NF32 T57_;
								tyObject_Vec_8lp09c9aJ6sSqRDc8uUVfyuA T58_;
								NI32 T59_;
								NF32* T60_;
								NI TM_V45tF8B8NBcxFcjfe7lhBw_25;
								T55_ = (cubePositions_DY5KGuUsgEns7QXZThW7qg ? cubePositions_DY5KGuUsgEns7QXZThW7qg->Sup.len : 0);
								if (!(i_2 < T55_)) goto LA54;
								nimln_(2180, "system.nim");
								i = i_2;
								if ((NU)(i_2) >= (NU)(cubePositions_DY5KGuUsgEns7QXZThW7qg->Sup.len)) raiseIndexError();
								position = cubePositions_DY5KGuUsgEns7QXZThW7qg->data[i_2];
								nimln_(317, "main.nim");
								model_GLLYWwQIhVraS5S9cW3NRyQ = mat4_dnl08WbvO2CTNBskwbejJA(1.0000000000000000e+00f);
								nimln_(318, "main.nim");
								model_GLLYWwQIhVraS5S9cW3NRyQ = translate_e7jN59cKY7Uoow5L49bvCGdw((&model_GLLYWwQIhVraS5S9cW3NRyQ), position);
								nimln_(319, "main.nim");
								T56_ = (NU32)0;
								T56_ = Dl_142397_();
								T57_ = (NF32)0;
								T57_ = radians_PIZWPt9cdwGu0FvhY9aY3DEQmain(5.0000000000000000e+00f);
								angle = ((NF)(((NF)(((NF)(((NF) (i))) * (NF)(((NF) (T56_))))) / (NF)(1.0000000000000000e+02))) * (NF)(((NF) (T57_))));
								nimln_(320, "main.nim");
								T58_ = vec3_bV33b6rSAdvcVnmP1zcMwQmain(1.0000000000000000e+00f, 2.9999999999999999e-01f, 5.0000000000000000e-01f);
								model_GLLYWwQIhVraS5S9cW3NRyQ = rotate_wNoaEUlwghMGh9a3HFECfQA((&model_GLLYWwQIhVraS5S9cW3NRyQ), T58_, ((NF32) (angle)));
								nimln_(322, "main.nim");
								T59_ = (NI32)0;
								T59_ = glGetUniformLocation_oSrxPmF9cyUrVZRg4cZ4LjQ(shaderProgram_AW1xCBZy74f29b2WWcgMBdQ, "model");
								T60_ = (NF32*)0;
								T60_ = caddr_jgGzxJqqiHwFCU9bs1j3VOw((&model_GLLYWwQIhVraS5S9cW3NRyQ));
								glUniformMatrix4fv_m5jOdRl0iATiwQimgINdIw(T59_, ((NI32) 1), NIM_FALSE, T60_);
								nimln_(324, "main.nim");
								glDrawArrays_Bw7cKcZtx9bAbZdj5Iw9af9ag(((NU32) 4), ((NI32) 0), ((NI32) 36));
								nimln_(2181, "system.nim");
								TM_V45tF8B8NBcxFcjfe7lhBw_25 = addInt(i_2, ((NI) 1));
								i_2 = (NI)(TM_V45tF8B8NBcxFcjfe7lhBw_25);
							} LA54: ;
						}
					}
					nimln_(327, "main.nim");
					T61_ = (NI32)0;
					T61_ = glGetUniformLocation_oSrxPmF9cyUrVZRg4cZ4LjQ(shaderProgram_AW1xCBZy74f29b2WWcgMBdQ, "projection");
					T62_ = (NF32*)0;
					T62_ = caddr_jgGzxJqqiHwFCU9bs1j3VOw((&projection));
					glUniformMatrix4fv_m5jOdRl0iATiwQimgINdIw(T61_, ((NI32) 1), NIM_FALSE, T62_);
					nimln_(328, "main.nim");
					T63_ = (NI32)0;
					T63_ = glGetUniformLocation_oSrxPmF9cyUrVZRg4cZ4LjQ(shaderProgram_AW1xCBZy74f29b2WWcgMBdQ, "view");
					T64_ = (NF32*)0;
					T64_ = caddr_jgGzxJqqiHwFCU9bs1j3VOw((&view));
					glUniformMatrix4fv_m5jOdRl0iATiwQimgINdIw(T63_, ((NI32) 1), NIM_FALSE, T64_);
					nimln_(329, "main.nim");
					glBindVertexArray_DTfQaj6wT6HQ9c375GwSXmg(((NU32) 0));
					nimln_(330, "main.nim");
					Dl_142456_(window);
				} LA47: ;
			}
			popSafePoint();
		}
		else {
			popSafePoint();
			setFrame((TFrame*)&FR_);
		}
		{
			nimln_(212, "main.nim");
			destroy_sFvfWODyHxg46OuBtGyU8Qmain(window);
		}
		if (TM_V45tF8B8NBcxFcjfe7lhBw_21.status != 0) reraiseException();
		popSafePoint();
	}
	else {
		popSafePoint();
		setFrame((TFrame*)&FR_);
	}
	{
		nimln_(200, "main.nim");
		Dl_141777_();
	}
	if (TM_V45tF8B8NBcxFcjfe7lhBw_18.status != 0) reraiseException();
	popFrame();
}

static N_INLINE(void, initStackBottomWith)(void* locals) {
	setStackBottom(locals);
}
void PreMainInner(void) {
	systemInit000();
	stdlib_macrosDatInit000();
	stdlib_unsignedDatInit000();
	stdlib_parseutilsDatInit000();
	stdlib_mathDatInit000();
	stdlib_algorithmDatInit000();
	stdlib_strutilsDatInit000();
	sdl2_sdl2DatInit000();
	glm_vecDatInit000();
	glm_matDatInit000();
	glm_globalsDatInit000();
	glm_mat_transformDatInit000();
	glm_quatDatInit000();
	glm_glmDatInit000();
	stdlib_sequtilsDatInit000();
	x11_xDatInit000();
	x11_xlibDatInit000();
	x11_keysymDatInit000();
	x11_xutilDatInit000();
	stdlib_dynlibDatInit000();
	opengl_openglDatInit000();
	stb_image_componentsDatInit000();
	stb_image_readDatInit000();
	mainDatInit000();
	stdlib_macrosInit000();
	stdlib_unsignedInit000();
	stdlib_parseutilsInit000();
	stdlib_mathInit000();
	stdlib_algorithmInit000();
	stdlib_strutilsInit000();
	sdl2_sdl2Init000();
	glm_vecInit000();
	glm_matInit000();
	glm_globalsInit000();
	glm_mat_transformInit000();
	glm_quatInit000();
	glm_glmInit000();
	stdlib_sequtilsInit000();
	x11_xInit000();
	x11_xlibInit000();
	x11_keysymInit000();
	x11_xutilInit000();
	stdlib_dynlibInit000();
	opengl_openglInit000();
	stb_image_componentsInit000();
	stb_image_readInit000();
}

void PreMain(void) {
	void (*volatile inner)(void);
	systemDatInit000();
	inner = PreMainInner;
	initStackBottomWith((void *)&inner);
	(*inner)();
}

int cmdCount;
char** cmdLine;
char** gEnv;
N_CDECL(void, NimMainInner)(void) {
	NimMainModule();
}

N_CDECL(void, NimMain)(void) {
	void (*volatile inner)(void);
	PreMain();
	inner = NimMainInner;
	initStackBottomWith((void *)&inner);
	(*inner)();
}

int main(int argc, char** args, char** env) {
	cmdLine = args;
	cmdCount = argc;
	gEnv = env;
	NimMain();
	return nim_program_result;
}

NIM_EXTERNC N_NOINLINE(void, NimMainModule)(void) {
	nimfr_("main", "main.nim");
nimRegisterGlobalMarker(TM_V45tF8B8NBcxFcjfe7lhBw_2);
nimRegisterGlobalMarker(TM_V45tF8B8NBcxFcjfe7lhBw_5);
nimRegisterGlobalMarker(TM_V45tF8B8NBcxFcjfe7lhBw_6);
nimRegisterGlobalMarker(TM_V45tF8B8NBcxFcjfe7lhBw_8);
nimRegisterGlobalMarker(TM_V45tF8B8NBcxFcjfe7lhBw_10);
	nimln_(11, "main.nim");
	dontQuit_U2RdFTx0yT60ufXikLqvjw = NIM_TRUE;
	nimln_(12, "main.nim");
	screenWidth_BY9awPNjIKMlJgec2Lc40gA = ((int) 800);
	nimln_(13, "main.nim");
	screenHeight_Sc15UsbfHjCpDkYtTKu9c6g = ((int) 600);
	nimln_(14, "main.nim");
	fov_qo9c6EXFjwbB4sA9aGSC9bfOw = 4.5000000000000000e+01f;
	nimln_(17, "main.nim");
	genericSeqAssign((&vertices_TyXguZdE3Wr74cs0jPlWcg), TM_V45tF8B8NBcxFcjfe7lhBw_3, (&NTI_4Xyxy0Om14N6K1l5e9bUPSQ_));
	nimln_(60, "main.nim");
	if (cubePositions_DY5KGuUsgEns7QXZThW7qg) { nimGCunrefNoCycle(cubePositions_DY5KGuUsgEns7QXZThW7qg); cubePositions_DY5KGuUsgEns7QXZThW7qg = NIM_NIL; }
	cubePositions_DY5KGuUsgEns7QXZThW7qg = (tySequence_sqJcVPBTp6ctoewzQQWnQw*) newSeqRC1((&NTI_sqJcVPBTp6ctoewzQQWnQw_), 10);
	nimln_(61, "main.nim");
	cubePositions_DY5KGuUsgEns7QXZThW7qg->data[0] = vec3_bV33b6rSAdvcVnmP1zcMwQmain(0.0f, 0.0f, 0.0f);
	nimln_(62, "main.nim");
	cubePositions_DY5KGuUsgEns7QXZThW7qg->data[1] = vec3_bV33b6rSAdvcVnmP1zcMwQmain(2.0000000000000000e+00f, 5.0000000000000000e+00f, -1.5000000000000000e+01);
	nimln_(63, "main.nim");
	cubePositions_DY5KGuUsgEns7QXZThW7qg->data[2] = vec3_bV33b6rSAdvcVnmP1zcMwQmain(-1.5000000000000000e+00, -2.2000000000000002e+00, -2.5000000000000000e+00);
	nimln_(64, "main.nim");
	cubePositions_DY5KGuUsgEns7QXZThW7qg->data[3] = vec3_bV33b6rSAdvcVnmP1zcMwQmain(-3.7999999999999998e+00, -2.0000000000000000e+00, -1.2300000000000001e+01);
	nimln_(65, "main.nim");
	cubePositions_DY5KGuUsgEns7QXZThW7qg->data[4] = vec3_bV33b6rSAdvcVnmP1zcMwQmain(2.3999999999999999e+00f, -4.0000000000000002e-01, -3.5000000000000000e+00);
	nimln_(66, "main.nim");
	cubePositions_DY5KGuUsgEns7QXZThW7qg->data[5] = vec3_bV33b6rSAdvcVnmP1zcMwQmain(-1.7000000000000000e+00, 3.0000000000000000e+00f, -7.5000000000000000e+00);
	nimln_(67, "main.nim");
	cubePositions_DY5KGuUsgEns7QXZThW7qg->data[6] = vec3_bV33b6rSAdvcVnmP1zcMwQmain(1.3000000000000000e+00f, -2.0000000000000000e+00, -2.5000000000000000e+00);
	nimln_(68, "main.nim");
	cubePositions_DY5KGuUsgEns7QXZThW7qg->data[7] = vec3_bV33b6rSAdvcVnmP1zcMwQmain(1.5000000000000000e+00f, 2.0000000000000000e+00f, -2.5000000000000000e+00);
	nimln_(69, "main.nim");
	cubePositions_DY5KGuUsgEns7QXZThW7qg->data[8] = vec3_bV33b6rSAdvcVnmP1zcMwQmain(1.5000000000000000e+00f, 2.0000000000000001e-01f, -1.5000000000000000e+00);
	nimln_(70, "main.nim");
	cubePositions_DY5KGuUsgEns7QXZThW7qg->data[9] = vec3_bV33b6rSAdvcVnmP1zcMwQmain(-1.3000000000000000e+00, 1.0000000000000000e+00f, -1.5000000000000000e+00);
	nimln_(81, "main.nim");
	asgnRefNoCycle((void**) (&vertexShaderSource_0HW1jVrVxaTKp7MceNI5Mg), readFile_T9cm5LIRX2tKEH9aREBZ8A0w(((NimStringDesc*) &TM_V45tF8B8NBcxFcjfe7lhBw_7)));
	nimln_(82, "main.nim");
	asgnRefNoCycle((void**) (&fragmentShaderSource_deoqY39coXrpzZUsWQG8mEQ), readFile_T9cm5LIRX2tKEH9aREBZ8A0w(((NimStringDesc*) &TM_V45tF8B8NBcxFcjfe7lhBw_9)));
	nimln_(94, "main.nim");
	cameraPos_7BlJD9c9b9br6uSqX5HznfcXQ = vec3_bV33b6rSAdvcVnmP1zcMwQmain(0.0f, 0.0f, 2.9999999999999999e-01f);
	nimln_(95, "main.nim");
	cameraFront_NZTsKo9atnVuihWmh3xW4sQ = vec3_bV33b6rSAdvcVnmP1zcMwQmain(0.0f, 0.0f, -1.0000000000000000e+00);
	nimln_(96, "main.nim");
	cameraUp_H4JTsb9b78aAqrZrhxc0vqA = vec3_bV33b6rSAdvcVnmP1zcMwQmain(0.0f, 1.0000000000000000e+00f, 0.0f);
	nimln_(97, "main.nim");
	model_GLLYWwQIhVraS5S9cW3NRyQ = mat4_dnl08WbvO2CTNBskwbejJA(1.0000000000000000e+00f);
	nimln_(98, "main.nim");
	deltaTime_3OQfSEgNwGCaiDv8pkr51Q = 0.0f;
	nimln_(99, "main.nim");
	lastFrame_ZbRny9aCpi9bNNaG2cGj1rew = 0.0f;
	nimln_(100, "main.nim");
	cameraSpeed_8YsPBxY6HPUxeqcG9bD4PKQ = 2.5000000000000000e+00f;
	nimln_(101, "main.nim");
	yaw_r59aOygQet7RSrZs3ZIUDRw = -9.0000000000000000e+01;
	nimln_(102, "main.nim");
	pitch_eErl9bMOJlml9aygm25PvBcQ = 0.0f;
	nimln_(106, "main.nim");
	nimLoadProcs0();
	nimln_(332, "main.nim");
	main_9bQIWt54CdTNMd7hgR2Bl9cw();
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, mainDatInit000)(void) {
static TNimNode TM_V45tF8B8NBcxFcjfe7lhBw_0[1];
NTI_9c6o5Sg4WWFW32kxEqehq7A_.size = sizeof(tyObject_SDLException_9c6o5Sg4WWFW32kxEqehq7A);
NTI_9c6o5Sg4WWFW32kxEqehq7A_.kind = 17;
NTI_9c6o5Sg4WWFW32kxEqehq7A_.base = (&NTI_bAvOj2UcojKN87yAQLs0aw_);
TM_V45tF8B8NBcxFcjfe7lhBw_0[0].len = 0; TM_V45tF8B8NBcxFcjfe7lhBw_0[0].kind = 2;
NTI_9c6o5Sg4WWFW32kxEqehq7A_.node = &TM_V45tF8B8NBcxFcjfe7lhBw_0[0];
NTI_T6kh3mQztDNb9bpesdVnfXw_.size = sizeof(tyObject_SDLException_9c6o5Sg4WWFW32kxEqehq7A*);
NTI_T6kh3mQztDNb9bpesdVnfXw_.kind = 22;
NTI_T6kh3mQztDNb9bpesdVnfXw_.base = (&NTI_9c6o5Sg4WWFW32kxEqehq7A_);
NTI_T6kh3mQztDNb9bpesdVnfXw_.marker = Marker_tyRef_T6kh3mQztDNb9bpesdVnfXw;
}

